import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    backgroundColor: "#FBF3EC",
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  root: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  background: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  backgroundImage: {
    opacity: 0.98,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,247,240,0.72)",
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 28,
    gap: 8,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  profileCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#EBCFC0",
    backgroundColor: "#FFF8F0",
    padding: 16,
    gap: 12,
    shadowColor: "#C7A899",
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  lockedProfileHint: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  lockedProfileBadge: {
    minHeight: 24,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F2C7D7",
    backgroundColor: "#FFF0F6",
    alignItems: "center",
    justifyContent: "center",
  },
  lockedProfileBadgeText: {
    color: "#C0587B",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "800",
  },
  lockedProfileHintText: {
    flex: 1,
    color: "#A65D78",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  profileTopRow: {
    flexDirection: "row",
    gap: 14,
  },
  photoWrap: {
    width: 92,
    height: 92,
    borderRadius: 18,
    backgroundColor: "#F0E3DB",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  photoImage: {
    width: 92,
    height: 92,
  },
  summary: {
    flex: 1,
    gap: 7,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  childName: {
    color: "#243142",
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "700",
    flex: 1,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
  },
  statsChip: {
    minWidth: 0,
    flex: 1,
    gap: 2,
    paddingVertical: 0,
    paddingHorizontal: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  statsLabel: {
    color: "#6A7889",
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "600",
  },
  statsValue: {
    color: "#243142",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  statusPillsRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 2,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 7,
    paddingHorizontal: 11,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D8E9D7",
    backgroundColor: "#F4FBF4",
  },
  statusPillDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#67B66E",
  },
  statusPillText: {
    color: "#47765A",
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "600",
  },
  editButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 38,
    height: 38,
    flexShrink: 0,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E9CBBE",
    backgroundColor: "#FFF7F0",
  },
  editButtonPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  sectionTitle: {
    marginTop: 4,
    color: "#243142",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
  },
  journalGrid: {
    gap: 6,
  },
  journalRow: {
    flexDirection: "row",
    gap: 6,
  },
  journalItem: {
    flex: 1,
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#EFD7CB",
    backgroundColor: "#FFF9F2",
    shadowColor: "#C7A899",
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  journalItemPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  journalIconWrap: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  journalItemLabel: {
    flex: 1,
    color: "#243142",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "600",
  },
  notesBlock: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EBCFC0",
    backgroundColor: "#FFF8F0",
    padding: 12,
    gap: 6,
  },
  notesPressed: {
    opacity: 0.9,
  },
  disabledCard: {
    opacity: 0.6,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  infoOptional: {
    color: "#9AA7B3",
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "600",
  },
  infoDivider: {
    height: 1,
    backgroundColor: "#F0DDD4",
    marginVertical: 2,
  },
  notesTitle: {
    color: "#243142",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "700",
  },
  notesBody: {
    color: "#46576A",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
  },
  exportCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E9CBBE",
    backgroundColor: "#FFF9F2",
    padding: 16,
    shadowColor: "#C7A899",
    shadowOpacity: 0.07,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  exportPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  exportIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D4C6",
    backgroundColor: "#FFF2E8",
    alignItems: "center",
    justifyContent: "center",
  },
  exportTextWrap: {
    flex: 1,
    gap: 3,
  },
  exportTitle: {
    color: "#243142",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "700",
  },
  exportCaption: {
    color: "#6A7889",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "500",
  },
});
