import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 15,
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  background: {
    flex: 1,
  },
  backgroundImage: {
    opacity: 0.98,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,247,242,0.30)",
  },
  root: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 48,
    paddingHorizontal: 16,
    paddingBottom: 34,
    gap: 12,
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#31485C",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
  },
  titleWrap: {
    gap: 0,
  },
  subtitle: {
    color: "#6F7E8D",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "500",
    maxWidth: 290,
  },
  heroCard: {
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFFDF9",
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    shadowColor: "#C7A899",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  avatarWrap: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: "#F4E4DC",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  avatarImage: {
    width: 94,
    height: 94,
  },
  heroInfo: {
    flex: 1,
    gap: 8,
  },
  childName: {
    color: "#23364A",
    fontSize: 31,
    lineHeight: 35,
    fontWeight: "800",
  },
  childMeta: {
    color: "#6F7E8D",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "500",
  },
  photoButton: {
    alignSelf: "flex-start",
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#F3B2A6",
    backgroundColor: "#FFF8F4",
  },
  photoButtonPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.985 }],
  },
  photoButtonText: {
    color: "#F47667",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  sectionWrap: {
    gap: 10,
  },
  sectionTitle: {
    color: "#23364A",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
  },
  cardList: {
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFFDF9",
    overflow: "hidden",
  },
  listRow: {
    minHeight: 72,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  listRowMultiline: {
    minHeight: 84,
    paddingVertical: 16,
  },
  rowDivider: {
    height: 1.5,
    backgroundColor: "#F0DDD4",
    marginHorizontal: 16,
  },
  rowTextWrap: {
    flex: 1,
    gap: 4,
  },
  rowLabel: {
    color: "#23364A",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
  rowDescription: {
    color: "#6F7E8D",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    maxWidth: 215,
  },
  rowValueWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    maxWidth: 142,
  },
  rowValue: {
    color: "#6F7E8D",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "500",
    textAlign: "right",
    flexShrink: 1,
  },
  inlineInput: {
    minWidth: 118,
    color: "#6F7E8D",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "500",
    textAlign: "right",
    padding: 0,
    marginRight: 2,
  },
  rowPressed: {
    opacity: 0.88,
    backgroundColor: "#FFF7F1",
  },
  settingToggleWrap: {
    marginLeft: 8,
  },
  actionsWrap: {
    gap: 12,
    marginTop: 4,
  },
  saveButton: {
    minHeight: 62,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#F47667",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  saveButtonPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  saveGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  saveLabel: {
    color: "#FFFFFF",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
  },
  deleteButton: {
    minHeight: 58,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#F07D68",
    backgroundColor: "rgba(255,253,249,0.86)",
  },
  deleteButtonPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.99 }],
  },
  deleteLabel: {
    color: "#F07D68",
    fontSize: 17,
    lineHeight: 20,
    fontWeight: "700",
  },
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 40,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.24)",
  },
  sheetCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFFCF8",
    paddingTop: 14,
    paddingHorizontal: 18,
    paddingBottom: 38,
    minHeight: 420,
    shadowColor: "#B98E7E",
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -8 },
  },
  dateSheetCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFFCF8",
    paddingTop: 14,
    paddingHorizontal: 18,
    paddingBottom: 34,
    height: 520,
    shadowColor: "#B98E7E",
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -8 },
  },
  textEditorSheetCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFFCF8",
    paddingTop: 14,
    paddingHorizontal: 18,
    paddingBottom: 24,
    minHeight: 352,
    shadowColor: "#B98E7E",
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -8 },
  },
  sheetDragZone: {
    paddingBottom: 14,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 54,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#E8D1C7",
    marginBottom: 12,
  },
  sheetTitle: {
    color: "#23364A",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
  },
  sheetSubtitle: {
    marginTop: 4,
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
  },
  avatarOptionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  avatarOption: {
    width: "22.7%",
    aspectRatio: 1,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFF8F4",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarOptionSelected: {
    borderColor: "#F38A7B",
    backgroundColor: "#FFEDE7",
  },
  avatarOptionPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.97 }],
  },
  avatarOptionImage: {
    width: "84%",
    height: "84%",
  },
  datePickerPreview: {
    marginBottom: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F0DDD4",
    backgroundColor: "#FFF8F4",
    alignItems: "center",
  },
  datePickerPreviewText: {
    color: "#23364A",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "700",
  },
  dateColumns: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  dateColumn: {
    flex: 1,
    maxHeight: 196,
  },
  datePill: {
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    backgroundColor: "#FFF8F4",
    borderWidth: 1,
    borderColor: "#F0DDD4",
  },
  datePillSelected: {
    backgroundColor: "#FFEDE7",
    borderColor: "#F38A7B",
  },
  datePillText: {
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  datePillTextSelected: {
    color: "#23364A",
  },
  sheetApplyButton: {
    marginTop: 8,
    minHeight: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  sheetTextarea: {
    minHeight: 144,
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0DDD4",
    backgroundColor: "#FFF8F4",
    color: "#23364A",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "500",
  },
});
