import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 12,
    backgroundColor: "#FBF3EC",
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#FBF3EC",
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.72)",
  },
  root: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 36,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  topChrome: {
    marginBottom: 16,
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  subtitle: {
    color: "#6F7C8C",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "500",
    maxWidth: 320,
  },
  section: {
    marginBottom: 12,
  },
  periodTabsWrap: {
    minHeight: 58,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F1D9CF",
    backgroundColor: "#FFFDFC",
    overflow: "hidden",
    paddingRight: 6,
  },
  periodTabs: {
    paddingLeft: 6,
    paddingRight: 12,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  periodTab: {
    minHeight: 44,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    flexShrink: 0,
  },
  periodTabActive: {
    backgroundColor: "#FFE8E1",
  },
  periodTabPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  periodTabText: {
    color: "#55677B",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    textAlign: "center",
  },
  periodTabTextActive: {
    color: "#FF7E73",
    fontWeight: "700",
  },
  summaryCard: {
    minHeight: 240,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: "#EED6CB",
    backgroundColor: "#FFF8F3",
    padding: 22,
    flexDirection: "row",
    overflow: "hidden",
    shadowColor: "#D7AFA0",
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
    marginBottom: 20,
  },
  summaryCopy: {
    flex: 1,
    paddingRight: 8,
  },
  summaryTitle: {
    color: "#1E2A38",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginBottom: 10,
  },
  summaryInsights: {
    gap: 14,
  },
  summaryHighlightsList: {
    gap: 12,
    marginTop: 18,
  },
  insightRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  insightIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.58)",
  },
  insightCopy: {
    flex: 1,
    gap: 2,
  },
  insightTitle: {
    color: "#1E2A38",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
  insightSubtitle: {
    color: "#6F7C8C",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  summaryVisual: {
    width: 112,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  decorBadge: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    shadowColor: "#D7AFA0",
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    zIndex: 2,
  },
  decorHeartTop: {
    width: 34,
    height: 34,
    top: 18,
    right: 10,
    transform: [{ rotate: "-10deg" }],
  },
  decorLeafTopLeft: {
    width: 28,
    height: 28,
    top: 28,
    left: -4,
    transform: [{ rotate: "-28deg" }],
  },
  decorHeartLeft: {
    width: 24,
    height: 24,
    top: 96,
    left: -4,
    transform: [{ rotate: "-14deg" }],
  },
  decorLeafRight: {
    width: 38,
    height: 38,
    top: 82,
    right: -8,
    transform: [{ rotate: "18deg" }],
  },
  decorLeafLowerRight: {
    width: 24,
    height: 24,
    bottom: 68,
    right: -2,
    transform: [{ rotate: "20deg" }],
  },
  decorHeartBottom: {
    width: 22,
    height: 22,
    bottom: 34,
    right: 28,
    transform: [{ rotate: "10deg" }],
  },
  decorHeartBottomLeft: {
    width: 18,
    height: 18,
    bottom: 42,
    left: 0,
    transform: [{ rotate: "-10deg" }],
  },
  decorLeafMidLeft: {
    width: 18,
    height: 18,
    top: 124,
    left: 4,
    transform: [{ rotate: "-16deg" }],
  },
  decorHeartMidRight: {
    width: 18,
    height: 18,
    top: 122,
    right: 10,
    transform: [{ rotate: "14deg" }],
  },
  decorLeafBottomCenter: {
    width: 18,
    height: 18,
    bottom: 22,
    left: 42,
    transform: [{ rotate: "12deg" }],
  },
  decorLeafNearFeet: {
    width: 16,
    height: 16,
    bottom: 18,
    right: 6,
    transform: [{ rotate: "18deg" }],
  },
  summaryAvatar: {
    width: 120,
    height: 152,
    marginTop: 28,
  },
  episodesSection: {
    marginTop: 2,
  },
  sectionTitle: {
    color: "#1E2A38",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginBottom: 8,
  },
  sectionHelper: {
    color: "#6F7C8C",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    marginBottom: 16,
  },
  episodesList: {
    gap: 12,
  },
  episodeRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  episodeLeftColumn: {
    width: 88,
  },
  episodeCenterColumn: {
    width: 18,
    alignItems: "center",
  },
  episodeTimelineAxis: {
    width: 10,
    height: 96,
    alignItems: "center",
    justifyContent: "flex-start",
    position: "relative",
  },
  episodeSwipeWrap: {
    flex: 1,
    minHeight: 96,
  },
  episodeTimelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#FF9C92",
    position: "absolute",
    top: 8,
    zIndex: 1,
  },
  episodeTimelineLine: {
    position: "absolute",
    width: 2,
    top: 20,
    bottom: 8,
    backgroundColor: "#F3D5CA",
  },
  episodeCard: {
    flex: 1,
    minHeight: 96,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    padding: 12,
    marginLeft: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  dateBadge: {
    width: 78,
    minHeight: 96,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    padding: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  dateBadgeMonth: {
    color: "#66758A",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 3,
  },
  dateBadgeDay: {
    color: "#1E2A38",
    fontSize: 17,
    lineHeight: 20,
    fontWeight: "800",
    textAlign: "center",
  },
  episodeCopy: {
    flex: 1,
    minWidth: 0,
  },
  episodeMeta: {
    color: "#6F7C8C",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    marginBottom: 4,
  },
  episodeTitle: {
    color: "#1E2A38",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "400",
    fontFamily: journalTypography.display,
    marginBottom: 4,
  },
  episodeSubtitle: {
    color: "#526273",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  confirmOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    zIndex: 60,
  },
  confirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(22, 32, 43, 0.24)",
  },
  confirmCard: {
    width: "100%",
    borderRadius: 28,
    backgroundColor: "#FFFCF8",
    padding: 22,
    borderWidth: 1,
    borderColor: "#EED8CE",
  },
  confirmTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: "#1E2A3A",
  },
  confirmDescription: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
    color: "#6B7585",
  },
  confirmActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  confirmButtonSecondary: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E7D7CE",
    backgroundColor: "#FFFDFC",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPrimary: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: "#F08A74",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  confirmButtonSecondaryText: {
    color: "#31475C",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
  },
  confirmButtonPrimaryText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
  },
});
