import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 12,
  },
  background: {
    flex: 1,
  },
  backgroundImage: {
    opacity: 0.98,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,246,240,0.40)",
  },
  root: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  topChrome: {
    marginBottom: 6,
  },
  backLink: {
    alignSelf: "flex-start",
    minHeight: 30,
    justifyContent: "center",
    marginBottom: 12,
  },
  backLinkText: {
    color: "#31485C",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
  },
  title: {
    color: "#23364A",
    fontSize: 34,
    lineHeight: 37,
    fontWeight: "700",
    letterSpacing: -0.9,
    marginBottom: 10,
  },
  subtitle: {
    color: "#6F7E8D",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "500",
    maxWidth: 300,
  },
  section: {
    marginTop: 24,
  },
  sectionTitle: {
    color: "#23364A",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    marginBottom: 12,
  },
  periodField: {
    minHeight: 64,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFFDF9",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  periodFieldOpen: {
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  periodLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  periodIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFF1EC",
    alignItems: "center",
    justifyContent: "center",
  },
  periodValue: {
    color: "#23364A",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
    letterSpacing: -0.3,
  },
  periodHelper: {
    color: "#6F7E8D",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    marginTop: 10,
    maxWidth: 310,
  },
  periodDropdown: {
    marginTop: 8,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFFDF9",
    overflow: "hidden",
  },
  periodDropdownItem: {
    minHeight: 48,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  periodDropdownItemActive: {
    backgroundColor: "#FFF6F2",
  },
  periodDropdownItemPressed: {
    opacity: 0.88,
  },
  periodDropdownText: {
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  periodDropdownTextActive: {
    color: "#F47667",
  },
  periodDropdownDivider: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 0,
    height: 1,
    backgroundColor: "#F0DED6",
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
    marginTop: 16,
  },
  metricCard: {
    width: "30.5%",
    minHeight: 118,
    borderRadius: 22,
    borderWidth: 2,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 14,
    justifyContent: "space-between",
  },
  metricChip: {
    alignSelf: "flex-start",
    minHeight: 24,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 9,
  },
  metricChipDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  metricChipText: {
    color: "#23364A",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "600",
  },
  metricValue: {
    color: "#23364A",
    fontSize: 23,
    lineHeight: 26,
    fontWeight: "700",
    letterSpacing: -0.4,
    marginTop: 14,
  },
  metricSubtext: {
    color: "#6F7E8D",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    marginTop: 3,
  },
  episodesHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  episodesList: {
    gap: 12,
  },
  episodeCard: {
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFFDF9",
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  episodeCopy: {
    flex: 1,
  },
  episodeMeta: {
    color: "#6F7E8D",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    marginBottom: 5,
  },
  episodeTitle: {
    color: "#23364A",
    fontSize: 20,
    lineHeight: 23,
    fontWeight: "700",
    letterSpacing: -0.3,
    marginBottom: 6,
  },
  episodeClosed: {
    color: "#6F7E8D",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    marginBottom: 4,
  },
  episodeDescription: {
    color: "#6F7E8D",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  episodeAction: {
    minWidth: 74,
    minHeight: 38,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#EBC0B0",
    backgroundColor: "#FFFDF9",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
  },
  episodeActionText: {
    color: "#23364A",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "600",
  },
});
