import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 14,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.52)",
  },
  root: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 36,
    gap: 8,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  headerBlock: {
    marginTop: 6,
    marginBottom: 18,
  },
  title: {
    color: "#1E2A38",
    fontSize: 32,
    lineHeight: 36,
    fontWeight: "800",
    letterSpacing: -0.8,
    marginBottom: 8,
  },
  subtitle: {
    color: "#6F7C8C",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "500",
    maxWidth: 320,
  },
  selectorAvatarWrap: {
    width: 56,
    height: 56,
    borderRadius: 20,
    backgroundColor: "#F7E6DD",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginRight: 14,
  },
  selectorAvatar: {
    width: 56,
    height: 56,
  },
  selectorCopy: {
    flex: 1,
    gap: 3,
  },
  selectorTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  selectorName: {
    color: "#1E2A38",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    flexShrink: 1,
  },
  selectorDate: {
    color: "#6F7C8C",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  selectorCardCompact: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  episodeChip: {
    minHeight: 28,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D9C7FC",
    backgroundColor: "#F1EAFE",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  episodeChipText: {
    color: "#4D397A",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "700",
  },
  summaryCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EED6CB",
    backgroundColor: "#FFFDFC",
    padding: 20,
    marginBottom: 14,
    shadowColor: "#D7AFA0",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  summaryLines: {
    gap: 8,
    marginTop: 10,
  },
  summaryLine: {
    color: "#526273",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
  },
  summaryTipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 2,
  },
  progressTip: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: "center",
  },
  summaryTip: {
    minWidth: "48%",
    maxWidth: "48%",
  },
  progressTipContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  progressTipIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  progressTipMedicineAssetIcon: {
    width: 20,
    height: 20,
  },
  progressTipText: {
    color: "#1E2A38",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
    flexShrink: 1,
  },
  temperatureSection: {
    marginTop: 2,
  },
  temperatureTitle: {
    color: "#1E2A38",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginBottom: 12,
  },
  temperatureCard: {
    minHeight: 172,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EFC9BC",
    borderStyle: "dashed",
    backgroundColor: "rgba(255,253,252,0.72)",
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    overflow: "hidden",
  },
  temperatureCopy: {
    flex: 1,
    paddingRight: 12,
  },
  temperatureText: {
    color: "#526273",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
  },
  temperatureArtWrap: {
    width: 96,
    height: 112,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  temperatureArt: {
    width: 88,
    height: 104,
  },
});
