import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 12,
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 1,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.52)",
  },
  root: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 36,
    gap: 8,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  topChrome: {
    marginBottom: 18,
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  subtitle: {
    color: "#6F7C8C",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "500",
    maxWidth: 320,
  },
  section: {
    marginBottom: 20,
  },
  periodField: {
    minHeight: 64,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#EED6CB",
    backgroundColor: "#FFFDFC",
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  periodFieldOpen: {
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  periodLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  periodIconBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#FFE8E1",
    alignItems: "center",
    justifyContent: "center",
  },
  periodValue: {
    color: "#1E2A38",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    letterSpacing: -0.3,
  },
  periodHelper: {
    color: "#6F7C8C",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    marginTop: 10,
    marginLeft: 4,
  },
  periodDropdown: {
    marginTop: 8,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#EED6CB",
    backgroundColor: "#FFFDFC",
    overflow: "hidden",
  },
  periodDropdownItem: {
    minHeight: 48,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  periodDropdownItemActive: {
    backgroundColor: "#FFF7F2",
  },
  periodDropdownItemPressed: {
    opacity: 0.88,
  },
  periodDropdownText: {
    color: "#6F7C8C",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  periodDropdownTextActive: {
    color: "#FF7E73",
  },
  periodDropdownDivider: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: 0,
    height: 1,
    backgroundColor: "#F3E2DA",
  },
  summaryCard: {
    minHeight: 240,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: "#EED6CB",
    backgroundColor: "#FFF8F3",
    padding: 22,
    flexDirection: "row",
    overflow: "hidden",
    shadowColor: "#D7AFA0",
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
    marginBottom: 18,
  },
  summaryCopy: {
    flex: 1,
    paddingRight: 8,
  },
  summaryTitle: {
    color: "#1E2A38",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginBottom: 18,
  },
  summaryInsights: {
    gap: 14,
  },
  insightRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  insightIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  insightCopy: {
    flex: 1,
    gap: 2,
  },
  insightTitle: {
    color: "#1E2A38",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
  insightSubtitle: {
    color: "#6F7C8C",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  summaryVisual: {
    width: 112,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  decorBadge: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    shadowColor: "#D7AFA0",
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    zIndex: 2,
  },
  decorHeartTop: {
    width: 34,
    height: 34,
    top: 22,
    right: 14,
    transform: [{ rotate: "-10deg" }],
  },
  decorLeafTopLeft: {
    width: 28,
    height: 28,
    top: 34,
    left: 0,
    transform: [{ rotate: "-28deg" }],
  },
  decorHeartLeft: {
    width: 24,
    height: 24,
    top: 96,
    left: -4,
    transform: [{ rotate: "-14deg" }],
  },
  decorLeafRight: {
    width: 38,
    height: 38,
    top: 82,
    right: -8,
    transform: [{ rotate: "18deg" }],
  },
  decorLeafLowerRight: {
    width: 26,
    height: 26,
    bottom: 42,
    right: 2,
    transform: [{ rotate: "24deg" }],
  },
  decorHeartBottom: {
    width: 30,
    height: 30,
    bottom: 8,
    right: 28,
    transform: [{ rotate: "12deg" }],
  },
  decorHeartBottomLeft: {
    width: 22,
    height: 22,
    bottom: 28,
    left: 12,
    transform: [{ rotate: "-8deg" }],
  },
  summaryAvatar: {
    width: 120,
    height: 152,
    marginTop: 28,
  },
  highlightsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 28,
  },
  highlightCell: {
    width: "48.6%",
  },
  highlightCellFull: {
    width: "100%",
  },
  highlightCard: {
    minHeight: 136,
    borderRadius: 24,
    borderWidth: 1.5,
    padding: 14,
    gap: 12,
    shadowColor: "#D7AFA0",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  highlightIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  highlightTextBlock: {
    flex: 1,
    justifyContent: "space-between",
  },
  highlightLabel: {
    color: "#6F7C8C",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  highlightValue: {
    color: "#1E2A38",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  episodesSection: {
    marginTop: 2,
  },
  sectionTitle: {
    color: "#1E2A38",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginBottom: 8,
  },
  sectionHelper: {
    color: "#6F7C8C",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    marginBottom: 16,
  },
  episodesList: {
    gap: 14,
  },
  episodeCard: {
    borderRadius: 24,
    borderWidth: 2,
    borderColor: "#EED6CB",
    backgroundColor: "#FFFDFC",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  dateBadge: {
    width: 62,
    height: 72,
    borderRadius: 20,
    backgroundColor: "#FFE8E1",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  dateBadgeMonth: {
    color: "#31475C",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    marginBottom: 2,
  },
  dateBadgeDay: {
    color: "#1E2A38",
    fontSize: 26,
    lineHeight: 28,
    fontWeight: "800",
  },
  episodeCopy: {
    flex: 1,
    minWidth: 0,
  },
  episodeMeta: {
    color: "#6F7C8C",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  episodeTitle: {
    color: "#1E2A38",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    marginBottom: 4,
  },
  episodeSubtitle: {
    color: "#526273",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  episodeAction: {
    minHeight: 42,
    minWidth: 82,
    paddingHorizontal: 14,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: "#E6BFAF",
    backgroundColor: "#FFFDFC",
    alignItems: "center",
    justifyContent: "center",
  },
  episodeActionPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  episodeActionText: {
    color: "#1E2A38",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
});
