import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 14,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.52)",
  },
  root: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 36,
    gap: 8,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  headerBlock: {
    marginTop: 6,
    marginBottom: 18,
  },
  title: {
    color: "#1E2A38",
    fontSize: 32,
    lineHeight: 36,
    fontWeight: "800",
    letterSpacing: -0.8,
    marginBottom: 8,
  },
  subtitle: {
    color: "#6F7C8C",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "500",
    maxWidth: 320,
  },
  selectorCard: {
    minHeight: 84,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: "#EED6CB",
    backgroundColor: "#FFFDFC",
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  selectorAvatarWrap: {
    width: 56,
    height: 56,
    borderRadius: 20,
    backgroundColor: "#F7E6DD",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginRight: 14,
  },
  selectorAvatar: {
    width: 56,
    height: 56,
  },
  selectorCopy: {
    flex: 1,
    gap: 3,
  },
  selectorName: {
    color: "#1E2A38",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
  },
  selectorDate: {
    color: "#6F7C8C",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  episodeChip: {
    alignSelf: "flex-start",
    minHeight: 38,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#D9C7FC",
    backgroundColor: "#F1EAFE",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  episodeChipText: {
    color: "#4D397A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  summaryCard: {
    borderRadius: 28,
    borderWidth: 2,
    borderColor: "#EED6CB",
    backgroundColor: "#FFFDFC",
    padding: 20,
    marginBottom: 14,
    shadowColor: "#D7AFA0",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  summaryTitle: {
    color: "#1E2A38",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginBottom: 12,
  },
  summaryLines: {
    gap: 8,
  },
  summaryLine: {
    color: "#526273",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
  },
  infoCardsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  infoCard: {
    flex: 1,
    minHeight: 106,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: "#EED6CB",
    backgroundColor: "#FFFDFC",
    padding: 16,
    justifyContent: "space-between",
  },
  infoLabel: {
    color: "#6F7C8C",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
  },
  infoValue: {
    color: "#1E2A38",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  progressCard: {
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: "#DDC9FA",
    padding: 20,
    marginBottom: 18,
  },
  progressTitle: {
    color: "#1E2A38",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginBottom: 16,
  },
  progressRow: {
    flexDirection: "row",
  },
  progressColumn: {
    flex: 1,
    alignItems: "flex-start",
    position: "relative",
    minHeight: 68,
    paddingRight: 10,
  },
  progressValue: {
    color: "#1E2A38",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    marginBottom: 4,
  },
  progressLabel: {
    color: "#6F7C8C",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  progressDivider: {
    position: "absolute",
    right: 0,
    top: 6,
    bottom: 6,
    width: 1,
    backgroundColor: "rgba(221,201,250,0.75)",
  },
  temperatureSection: {
    marginTop: 2,
  },
  temperatureTitle: {
    color: "#1E2A38",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    letterSpacing: -0.4,
    marginBottom: 12,
  },
  temperatureCard: {
    minHeight: 172,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: "#EFC9BC",
    borderStyle: "dashed",
    backgroundColor: "rgba(255,253,252,0.72)",
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    overflow: "hidden",
  },
  temperatureCopy: {
    flex: 1,
    paddingRight: 12,
  },
  temperatureText: {
    color: "#526273",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
  },
  temperatureArtWrap: {
    width: 96,
    height: 112,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  temperatureArtGlow: {
    position: "absolute",
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: "rgba(255,217,207,0.55)",
    bottom: 10,
  },
  temperatureArt: {
    width: 88,
    height: 104,
  },
});
