import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 16,
    backgroundColor: "#FBF3EC",
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#FBF3EC",
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.72)",
  },
  root: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  keyboardAvoiding: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 36,
    gap: 10,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  headerBlock: {
    marginTop: 4,
    marginBottom: 10,
  },
  title: {
    color: "#1E2A38",
    fontSize: 27,
    lineHeight: 31,
    fontWeight: "700",
    letterSpacing: -0.7,
    marginBottom: 4,
  },
  subtitle: {
    color: "#6F7C8C",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    maxWidth: 260,
  },
  formCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFFDF9",
    padding: 18,
    shadowColor: "#C7A899",
    shadowOpacity: 0.07,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  sectionTitle: {
    color: "#23364A",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    marginBottom: 10,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: "#F0DED6",
    marginBottom: 4,
  },
  optionRow: {
    flexDirection: "row",
    gap: 10,
  },
  optionChip: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F2E2D9",
    backgroundColor: "#FFFAF7",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  compactOptionChip: {
    minHeight: 44,
  },
  optionChipActive: {
    borderColor: "#EFCFC2",
    backgroundColor: "#FFF2EB",
  },
  optionChipPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  optionChipText: {
    color: "#7E6E68",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "600",
  },
  optionChipTextActive: {
    color: "#F26F6C",
  },
  rowsList: {
    gap: 0,
  },
  inputRow: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  inputShell: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EACFC3",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    minWidth: 128,
  },
  inputField: {
    width: 54,
    paddingVertical: 0,
    color: "#23364A",
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "600",
    textAlign: "right",
  },
  inputSuffix: {
    color: "#8C6E67",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "600",
  },
  row: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  rowPressable: {
    borderRadius: 16,
  },
  rowPressablePressed: {
    opacity: 0.92,
  },
  rowLabel: {
    color: "#23364A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  rowValueWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    maxWidth: "52%",
  },
  rowValue: {
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "500",
    textAlign: "right",
    flexShrink: 1,
  },
  rowHelper: {
    color: "#9AA4B1",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    marginTop: -8,
    marginBottom: 10,
  },
  rowDivider: {
    height: 1,
    backgroundColor: "#F0DED6",
  },
  secondaryPickerLink: {
    alignSelf: "flex-start",
    marginTop: 12,
    paddingVertical: 4,
  },
  secondaryPickerLinkPressed: {
    opacity: 0.82,
  },
  secondaryPickerLinkText: {
    color: "#8C6E67",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "600",
  },
  notesCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFF8F1",
    padding: 16,
    gap: 6,
  },
  notesTitle: {
    color: "#23364A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  notesBody: {
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
  },
  saveButton: {
    minHeight: 60,
    borderRadius: 22,
    backgroundColor: "#F26F6C",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#F47667",
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    marginTop: 4,
  },
  saveButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
  },
  pickerOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 30,
  },
  pickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(30,42,56,0.18)",
  },
  pickerSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: "#FFFDF9",
    paddingTop: 14,
    paddingHorizontal: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderColor: "#EBCFC4",
    gap: 12,
  },
  pickerSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  pickerSheetTitle: {
    color: "#23364A",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "700",
  },
  pickerCloseButton: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF4EE",
  },
  pickerCloseButtonPressed: {
    opacity: 0.9,
  },
  pickerCloseButtonText: {
    color: "#F26F6C",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "700",
  },
  datePickerPreview: {
    marginBottom: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F0DDD4",
    backgroundColor: "#FFF8F4",
    alignItems: "center",
  },
  datePickerPreviewText: {
    color: "#23364A",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "700",
  },
  dateColumns: {
    flexDirection: "row",
    gap: 10,
  },
  dateColumn: {
    flex: 1,
    maxHeight: 220,
  },
  dateColumnContent: {
    paddingBottom: 12,
  },
  datePill: {
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    backgroundColor: "#FFF8F4",
    borderWidth: 1,
    borderColor: "#F0DDD4",
  },
  datePillSelected: {
    backgroundColor: "#FFEDE7",
    borderColor: "#F38A7B",
  },
  datePillText: {
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  datePillTextSelected: {
    color: "#23364A",
  },
});
