import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 16,
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.52)",
  },
  root: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 36,
    gap: 10,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  headerBlock: {
    marginTop: 6,
    marginBottom: 14,
  },
  title: {
    color: "#1E2A38",
    fontSize: 31,
    lineHeight: 35,
    fontWeight: "800",
    letterSpacing: -0.7,
    marginBottom: 8,
  },
  subtitle: {
    color: "#6F7C8C",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "500",
    maxWidth: 320,
  },
  childCard: {
    minHeight: 96,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFFDF9",
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: "#C7A899",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  childAvatarWrap: {
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: "#F3E4DB",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  childAvatar: {
    width: 58,
    height: 58,
  },
  childCopy: {
    flex: 1,
    gap: 3,
  },
  childName: {
    color: "#23364A",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "800",
  },
  childDate: {
    color: "#6F7E8D",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
  },
  headerArt: {
    width: 42,
    height: 42,
  },
  headerIconFallback: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#EEF9F1",
    alignItems: "center",
    justifyContent: "center",
  },
  summaryChip: {
    alignSelf: "flex-start",
    minHeight: 38,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#F0D5CA",
    backgroundColor: "#FFF5EF",
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  summaryChipText: {
    color: "#A36E61",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  formCard: {
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFFDF9",
    padding: 18,
    shadowColor: "#C7A899",
    shadowOpacity: 0.07,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  sectionTitle: {
    color: "#23364A",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    marginBottom: 12,
  },
  rowsList: {
    gap: 0,
  },
  row: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  rowLabel: {
    color: "#23364A",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
  },
  rowValueWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    maxWidth: "52%",
  },
  rowValue: {
    color: "#6F7E8D",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "500",
    textAlign: "right",
    flexShrink: 1,
  },
  rowHelper: {
    color: "#9AA4B1",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    marginTop: -8,
    marginBottom: 10,
  },
  rowDivider: {
    height: 1,
    backgroundColor: "#F0DED6",
  },
  notesCard: {
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#EBCFC4",
    backgroundColor: "#FFF8F1",
    padding: 16,
    gap: 6,
  },
  notesTitle: {
    color: "#23364A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  notesBody: {
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
  },
  saveButton: {
    minHeight: 60,
    borderRadius: 22,
    backgroundColor: "#F26F6C",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#F47667",
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    marginTop: 4,
  },
  saveButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
  },
});
