import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const styles = StyleSheet.create({
  screenRoot: {
    flex: 1,
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EBCABD",
    backgroundColor: "#FFEDE3",
    paddingTop: 14,
    paddingRight: 16,
    paddingBottom: 14,
    paddingLeft: 16,
    marginBottom: 22,
    shadowColor: "#DFAE9A",
    shadowOpacity: 0.14,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    minHeight: 140,
    marginBottom: 14,
  },
  heroCopy: {
    flex: 1,
    paddingRight: 10,
    paddingTop: 4,
  },
  heroTitle: {
    color: "#1E2A38",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    letterSpacing: -0.4,
    marginBottom: 5,
    maxWidth: 176,
  },
  heroSubtitle: {
    color: "#66758A",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    maxWidth: 164,
  },
  heroVisual: {
    width: 136,
    height: 128,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  heroDecorAsset: {
    position: "absolute",
    width: 208,
    height: 194,
    top: -18,
    right: -24,
    opacity: 0.98,
  },
  metricsPanel: {
    borderRadius: 24,
    backgroundColor: "#FFFDFC",
    borderWidth: 1,
    borderColor: "#F1D9CF",
    paddingVertical: 12,
    paddingHorizontal: 8,
    flexDirection: "row",
  },
  metricColumn: {
    flex: 1,
    position: "relative",
  },
  metricInner: {
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    minHeight: 100,
    paddingHorizontal: 4,
  },
  metricIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#FFF0EA",
    alignItems: "center",
    justifyContent: "center",
  },
  metricDivider: {
    position: "absolute",
    right: 0,
    top: 16,
    bottom: 16,
    width: 1,
    backgroundColor: "#F6E7E0",
  },
  metricValue: {
    color: "#FF6E61",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  metricLabel: {
    color: "#66758A",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    textAlign: "center",
  },
  historyTitle: {
    color: "#1E2A38",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    letterSpacing: -0.4,
    marginBottom: 14,
  },
  timelineList: {
    gap: 12,
  },
  timelineRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  timelineLeftColumn: {
    width: 86,
  },
  timeCard: {
    minHeight: 96,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    padding: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  timeValue: {
    color: "#1E2A38",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    marginBottom: 2,
  },
  dayValue: {
    color: "#66758A",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
    textAlign: "center",
  },
  timelineCenterColumn: {
    width: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineSwipeRow: {
    flex: 1,
    minWidth: 0,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#FF9C92",
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: "#F3D5CA",
    marginTop: 6,
    marginBottom: 14,
  },
  entryCard: {
    flex: 1,
    minHeight: 96,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  entryCardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
    backgroundColor: "#FFF7F1",
  },
  entryBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  entryCopy: {
    flex: 1,
    minWidth: 0,
  },
  entryTitle: {
    color: "#1E2A38",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    marginBottom: 2,
  },
  entryMeta: {
    color: "#66758A",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  confirmOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    zIndex: 60,
  },
  confirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(22, 32, 43, 0.24)",
  },
  confirmCard: {
    width: "100%",
    borderRadius: 28,
    backgroundColor: "#FFFCF8",
    padding: 22,
    borderWidth: 1,
    borderColor: "#EED8CE",
  },
  confirmTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: "#1E2A3A",
    fontFamily: journalTypography.display,
  },
  confirmDescription: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
    color: "#6B7585",
    fontFamily: journalTypography.body,
  },
  confirmActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  confirmButtonSecondary: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E7D7CE",
    backgroundColor: "#FFFDFC",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPrimary: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: "#F08A74",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  confirmButtonSecondaryText: {
    color: "#31475C",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  confirmButtonPrimaryText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
});
