import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  background: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255,248,241,0.56)",
  },
  screen: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 54,
    paddingHorizontal: 16,
    paddingBottom: 138,
  },
  header: {
    paddingHorizontal: 2,
    marginBottom: 20,
    gap: 8,
  },
  title: {
    color: "#252B35",
    fontSize: 42,
    lineHeight: 44,
    fontWeight: "800",
    letterSpacing: -1.6,
  },
  subtitle: {
    maxWidth: 310,
    color: "#6F7178",
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "500",
  },
  profileCard: {
    position: "relative",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#EBCFC0",
    backgroundColor: "#FFF8F0",
    padding: 16,
    gap: 12,
    shadowColor: "#C7A899",
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  profileCardCollapsed: {
    gap: 0,
    paddingBottom: 16,
  },
  accountTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
  },
  avatar: {
    width: 92,
    height: 92,
    borderRadius: 18,
    backgroundColor: "#F0E3DB",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  avatarText: {
    color: "#F2685A",
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "800",
  },
  accountCopy: {
    flex: 1,
    gap: 6,
    paddingTop: 6,
  },
  accountName: {
    color: "#252B35",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  accountFamily: {
    color: "#5F636B",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    flexShrink: 1,
  },
  accountRole: {
    color: "#6A7889",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
  },
  accountMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  accountRolePill: {
    minHeight: 26,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#F0DDD5",
    backgroundColor: "#FFF6EF",
    alignItems: "center",
    justifyContent: "center",
  },
  accountRolePillText: {
    color: "#8A766E",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "700",
  },
  accountTopPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.992 }],
  },
  collapseChevron: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#FFF2E8",
    borderWidth: 1,
    borderColor: "#F3DDD2",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: 2,
  },
  profileDetails: {
    marginTop: 2,
    gap: 10,
  },
  profileEditRow: {
    minHeight: 68,
    paddingHorizontal: 2,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profileEditLead: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  profileEditLeadName: {
    backgroundColor: "#FDEADF",
  },
  profileEditLeadFamily: {
    backgroundColor: "#E8F6EE",
  },
  profileEditLeadRelationship: {
    backgroundColor: "#FFF2E1",
  },
  profileEditLeadPhone: {
    backgroundColor: "#EAF1FF",
  },
  profileEditCopy: {
    flex: 1,
    gap: 4,
  },
  profileEditLabel: {
    color: "#23364A",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    flex: 1,
  },
  profileEditValueWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
    maxWidth: "52%",
  },
  profileEditAccessory: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF2E8",
    borderWidth: 1,
    borderColor: "#F3DDD2",
    flexShrink: 0,
  },
  profileEditInput: {
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    paddingVertical: 0,
    paddingHorizontal: 0,
    textAlign: "right",
    flexShrink: 1,
    minWidth: 80,
  },
  profileEditDivider: {
    height: 1.5,
    backgroundColor: "#F0DDD4",
    marginHorizontal: 2,
  },
  sectionTitle: {
    marginTop: 18,
    marginBottom: 8,
    color: "#243142",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
  },
  navSection: {
    gap: 10,
  },
  navCard: {
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: "#EFDDD2",
    backgroundColor: "rgba(255,249,244,0.94)",
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  navItem: {
    minHeight: 72,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  navItemPressed: {
    backgroundColor: "rgba(252,235,228,0.72)",
  },
  navItemLead: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  navItemLeadFamily: {
    backgroundColor: "#FDEADF",
  },
  navItemLeadSettings: {
    backgroundColor: "#EAF1FF",
  },
  navItemLeadSupport: {
    backgroundColor: "#E8F6EE",
  },
  navItemLeadTerms: {
    backgroundColor: "#FFF2E1",
  },
  navItemLeadPrivacy: {
    backgroundColor: "#F5ECFF",
  },
  navItemCopy: {
    flex: 1,
    gap: 4,
  },
  navItemTitle: {
    color: "#252B35",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
  navItemSubtitle: {
    color: "#7A7F87",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  logoutWrap: {
    marginTop: 20,
    alignItems: "center",
  },
  logoutButton: {
    width: "100%",
    minHeight: 58,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: "#F1C7BD",
    backgroundColor: "#FFF4F0",
    alignItems: "center",
    justifyContent: "center",
  },
  logoutText: {
    color: "#E06356",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  inlineActionButtonPressed: {
    opacity: 0.88,
  },
  confirmOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(30,42,56,0.18)",
  },
  confirmCard: {
    width: "86%",
    maxWidth: 340,
    borderRadius: 28,
    backgroundColor: "#FFFDF9",
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderWidth: 1.5,
    borderColor: "#EBCFC4",
    shadowColor: "#CFAE9F",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  confirmContent: {
    gap: 16,
  },
  confirmTitle: {
    color: "#252B35",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    letterSpacing: -0.4,
    textAlign: "center",
  },
  confirmActions: {
    flexDirection: "row",
    gap: 10,
  },
  confirmButtonSecondary: {
    flex: 1,
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#E9D7CE",
    backgroundColor: "#FFF8F3",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPrimary: {
    flex: 1,
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#F0C8BC",
    backgroundColor: "#FFF0E9",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  confirmButtonSecondaryText: {
    color: "#6F7178",
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "700",
  },
  confirmButtonPrimaryText: {
    color: "#F26F6C",
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "800",
  },
});
