import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "transparent",
  },
  animatedLayer: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  gradient: {
    flex: 1,
  },
  keyboardAvoiding: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 54,
    paddingHorizontal: 16,
    paddingBottom: 132,
  },
  topBar: {
    minHeight: 44,
  },
  backLink: {
    minHeight: 34,
    justifyContent: "center",
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  hero: {
    marginTop: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
  },
  heroCopy: {
    flex: 1,
    gap: 10,
  },
  heroTitle: {
    color: "#172033",
    fontSize: 34,
    lineHeight: 38,
    fontWeight: "800",
    letterSpacing: -0.8,
    fontFamily: journalTypography.display,
  },
  heroSubtitle: {
    color: "#5F6B7A",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  heroArt: {
    width: 88,
    height: 88,
    borderRadius: 26,
    backgroundColor: "#F1F7FF",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    borderWidth: 1,
    borderColor: "#DCE9F8",
  },
  heroArtSuccess: {
    backgroundColor: "#EAF7F0",
    borderColor: "#CDEBDD",
  },
  heroArtIcon: {
    width: 54,
    height: 54,
  },
  searchCard: {
    marginTop: 24,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.86)",
    padding: 18,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  cardHeaderIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "#F1EBFF",
    borderWidth: 1,
    borderColor: "#DDD2FA",
    alignItems: "center",
    justifyContent: "center",
  },
  cardHeaderTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  searchInputWrap: {
    marginTop: 18,
    minHeight: 52,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchInput: {
    flex: 1,
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    paddingVertical: 0,
  },
  categoryRow: {
    marginTop: 16,
    gap: 8,
  },
  categoryScrollContent: {
    gap: 8,
    paddingRight: 4,
  },
  categoryChip: {
    minHeight: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#F4E3D9",
    backgroundColor: "#FFF0E8",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  categoryChipIcon: {
    width: 16,
    height: 16,
    flexShrink: 0,
  },
  categoryChipText: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  helperText: {
    marginTop: 14,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  emptyCard: {
    marginTop: 18,
    minHeight: 96,
    borderRadius: 26,
    backgroundColor: "#FFF5EF",
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  emptyArt: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: "#F1EBFF",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  emptyCopy: {
    flex: 1,
  },
  emptyTitle: {
    color: "#172033",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  emptySubtitle: {
    marginTop: 4,
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  benefitsCard: {
    marginTop: 18,
    borderRadius: 28,
    backgroundColor: "#EEF6FF",
    padding: 20,
    borderWidth: 1,
    borderColor: "#DCE9F8",
    flexDirection: "row",
    gap: 16,
  },
  benefitsCopy: {
    flex: 1,
  },
  benefitsArt: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  benefitsTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  benefitsItem: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  benefitsItemText: {
    flex: 1,
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  resultList: {
    marginTop: 18,
    gap: 10,
  },
  resultCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.86)",
    padding: 14,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  resultCardSelected: {
    borderColor: "#F3B8AC",
  },
  resultRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  resultArt: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  resultArtImage: {
    width: 44,
    height: 44,
  },
  resultCopy: {
    flex: 1,
    gap: 4,
  },
  resultTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  resultSubtitle: {
    color: "#5F6B7A",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  resultMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 2,
  },
  resultExpandedBlock: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#F4E3D9",
    gap: 10,
  },
  resultExpandedInline: {
    gap: 4,
  },
  resultExpandedLabel: {
    color: "#172033",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  resultExpandedText: {
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  resultExpandedHint: {
    color: "#8A94A6",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  resultExpandedAction: {
    marginTop: 2,
    minHeight: 42,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F2C2B8",
    backgroundColor: "#FFF7F1",
    alignItems: "center",
    justifyContent: "center",
  },
  resultExpandedActionPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  resultExpandedActionText: {
    color: "#F26F6C",
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  metaChip: {
    minHeight: 22,
    borderRadius: 11,
    paddingHorizontal: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EEE7FF",
  },
  metaChipText: {
    color: "#8B6FE8",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  selectedCard: {
    marginTop: 20,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.88)",
    padding: 18,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  selectedHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  selectedCopy: {
    flex: 1,
  },
  selectedTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  selectedSubtitle: {
    marginTop: 6,
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  selectedHint: {
    marginTop: 12,
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  fieldBlock: {
    marginTop: 16,
  },
  inlineFieldRow: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  inlineFieldLabelWrap: {
    width: 116,
    flexShrink: 0,
  },
  fieldLabel: {
    color: "#172033",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    marginBottom: 7,
  },
  inlineDateField: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  dateRow: {
    minHeight: 46,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  dateText: {
    flex: 1,
    color: "#172033",
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  datePlaceholderText: {
    color: "#A0A8B5",
  },
  textareaWrap: {
    minHeight: 72,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingTop: 9,
    paddingRight: 13,
    paddingBottom: 9,
    paddingLeft: 13,
  },
  textarea: {
    minHeight: 44,
    color: "#172033",
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    paddingVertical: 0,
  },
  footer: {
    marginTop: 22,
  },
  primaryButtonWrap: {
    minHeight: 58,
    borderRadius: 29,
    overflow: "hidden",
    shadowColor: "#F56565",
    shadowOpacity: 0.24,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
  },
  primaryButton: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonPressed: {
    opacity: 0.94,
  },
  primaryIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  sheetOverlay: {
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 18,
  },
  sheetBackdrop: {
    backgroundColor: "rgba(23, 32, 51, 0.26)",
  },
  sheetDragZone: {
    alignItems: "center",
    paddingTop: 10,
    paddingHorizontal: 20,
  },
  sheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#E7D6CE",
    marginBottom: 14,
  },
  sheetTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  sheetSubtitle: {
    marginTop: 8,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    textAlign: "center",
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  customValueSheetCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFDFB",
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 18,
  },
  customValueInput: {
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    marginTop: 18,
    paddingHorizontal: 14,
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  customValueActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  sheetSingleAction: {
    marginTop: 16,
  },
  customValueCancelButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFF7F2",
    alignItems: "center",
    justifyContent: "center",
  },
  customValueCancelText: {
    color: "#5F6B7A",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  customValueSaveButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 24,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  customValueSaveGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
  },
  customValueSaveText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  secondaryButtonPressed: {
    opacity: 0.9,
  },
});
