import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const medicineCabinetOverviewStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#FFF7F1",
  },
  addChoiceOverlay: {
    justifyContent: "flex-end",
  },
  addChoiceBackdrop: {
    backgroundColor: "rgba(15,23,42,0.32)",
  },
  addChoiceSheetCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFFCF8",
    paddingTop: 14,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderColor: "#EED8CE",
  },
  addChoiceDragZone: {
    paddingHorizontal: 16,
  },
  addChoiceHandle: {
    alignSelf: "center",
    width: 46,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#DDC8BE",
    marginBottom: 14,
  },
  addChoiceTitle: {
    color: "#1E2A3A",
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  addChoiceSubtitle: {
    marginTop: 6,
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  addChoicePanel: {
    marginTop: 16,
    marginHorizontal: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingHorizontal: 14,
    paddingVertical: 6,
    shadowColor: "#172033",
    shadowOpacity: 0.08,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
  },
  addChoiceOption: {
    minHeight: 82,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F4E3D9",
  },
  addChoiceOptionLast: {
    borderBottomWidth: 0,
  },
  addChoiceOptionPressed: {
    opacity: 0.88,
  },
  addChoiceOptionCopy: {
    flex: 1,
    gap: 4,
  },
  addChoiceOptionTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  addChoiceOptionHint: {
    color: "#6E7889",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  addChoiceOptionAction: {
    color: "#F56565",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  manualCreateOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 40,
  },
  transientNoticeWrap: {
    position: "absolute",
    top: 64,
    left: 16,
    right: 16,
    alignItems: "center",
    zIndex: 90,
  },
  transientNoticeCard: {
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderWidth: 1,
    borderColor: "#D7EEDF",
    shadowColor: "#172033",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  transientNoticeIconWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#E7F7EF",
    alignItems: "center",
    justifyContent: "center",
  },
  transientNoticeText: {
    color: "#172033",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  detailsSheetFields: {
    gap: 14,
    marginTop: 18,
  },
  fieldBlock: {
    gap: 7,
  },
  fieldLabel: {
    color: "#172033",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  dateRow: {
    minHeight: 46,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  dateText: {
    flex: 1,
    color: "#172033",
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  datePlaceholderText: {
    color: "#A0A8B5",
  },
  sheetOverlay: {
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 18,
  },
  sheetBackdrop: {
    backgroundColor: "rgba(23, 32, 51, 0.26)",
  },
  sheetDragZone: {
    alignItems: "center",
    paddingTop: 10,
    paddingHorizontal: 20,
  },
  sheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#E7D6CE",
    marginBottom: 14,
  },
  sheetTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  sheetSubtitle: {
    marginTop: 8,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    textAlign: "center",
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  customValueSheetCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFDFB",
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 18,
  },
  customValueActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  customValueCancelButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFF7F2",
    alignItems: "center",
    justifyContent: "center",
  },
  customValueCancelText: {
    color: "#5F6B7A",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  customValueSaveButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 24,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  customValueSaveGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
  },
  customValueSaveText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  secondaryButtonPressed: {
    opacity: 0.9,
  },
  primaryButtonPressed: {
    opacity: 0.94,
  },
  gradient: {
    flex: 1,
  },
  decorationTop: {
    position: "absolute",
    top: -72,
    right: -28,
    width: 186,
    height: 186,
    borderRadius: 93,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  decorationMiddle: {
    position: "absolute",
    top: 224,
    left: -44,
    width: 136,
    height: 136,
    borderRadius: 68,
    backgroundColor: "rgba(255,240,232,0.58)",
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 60,
  },
  screen: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 58,
    paddingHorizontal: 22,
    paddingBottom: 132,
    gap: 14,
  },
  header: {
    gap: 18,
  },
  headerControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  moduleIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "rgba(23, 32, 51, 0.08)",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  iconButtonGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.75)",
    alignItems: "center",
    justifyContent: "center",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  titleGroup: {
    flex: 1,
    gap: 6,
    paddingRight: 4,
  },
  title: {
    color: "#172033",
    fontSize: 42,
    lineHeight: 44,
    fontWeight: "800",
    letterSpacing: -1.6,
    fontFamily: journalTypography.display,
  },
  subtitle: {
    color: "#5F6B7A",
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  notificationsPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 18,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F0CFC4",
    backgroundColor: "rgba(255,255,255,0.55)",
  },
  notificationsLabel: {
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  infoLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoLineText: {
    flex: 1,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  infoLineTextStrong: {
    color: "#172033",
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  summaryCard: {
    marginTop: 6,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.78)",
    padding: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  statTile: {
    width: "48%",
    minHeight: 72,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "transparent",
    paddingHorizontal: 11,
    paddingVertical: 10,
    justifyContent: "space-between",
    gap: 6,
  },
  statTileActive: {
    borderWidth: 1,
  },
  statTilePressed: {
    opacity: 0.92,
  },
  statHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 6,
  },
  statCopy: {
    flex: 1,
    gap: 2,
  },
  statIconImage: {
    width: 28,
    height: 28,
  },
  statValue: {
    color: "#172033",
    fontSize: 20,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.display,
    letterSpacing: -0.3,
  },
  statTitle: {
    color: "#172033",
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  statHint: {
    color: "#6E7889",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  searchBar: {
    marginTop: 8,
    minHeight: 58,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.82)",
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchInput: {
    flex: 1,
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    paddingVertical: 0,
    fontFamily: journalTypography.body,
  },
  sectionHeader: {
    marginTop: 6,
    gap: 2,
  },
  sectionTitle: {
    color: "#172033",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  sectionSubtitle: {
    color: "#8A94A6",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  list: {
    gap: 10,
  },
  swipeCardWrap: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 24,
    backgroundColor: "#FFFCF8",
  },
  swipeDeleteActionWrap: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: 92,
    overflow: "hidden",
  },
  swipeDeleteAction: {
    flex: 1,
    borderRadius: 24,
    backgroundColor: "#E86A6A",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  swipeDeleteActionPressed: {
    opacity: 0.92,
  },
  swipeDeleteActionText: {
    color: "#FFFFFF",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  swipeCardAnimatedLayer: {
    zIndex: 1,
    borderRadius: 24,
    backgroundColor: "#FFFCF8",
  },
  medicineCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFCF8",
    paddingTop: 12,
    paddingRight: 14,
    paddingBottom: 12,
    paddingLeft: 14,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  medicineCardExpanded: {
    paddingBottom: 16,
  },
  medicineCardPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.96,
  },
  medicineCardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  medicineArtCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  medicineArtImage: {
    width: 44,
    height: 44,
  },
  medicineInfo: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  medicineTitle: {
    color: "#172033",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "800",
    fontFamily: journalTypography.display,
    letterSpacing: -0.2,
  },
  medicineSubtitle: {
    color: "#8A94A6",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 5,
    marginTop: 3,
  },
  tag: {
    minHeight: 20,
    borderRadius: 10,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  tagText: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  medicineRight: {
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
  },
  statusBadge: {
    minHeight: 30,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
    maxWidth: 96,
  },
  statusText: {
    textAlign: "center",
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  cardExpandedSection: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#F4E3D9",
    gap: 12,
  },
  cardExpandedBlock: {
    gap: 4,
  },
  cardExpandedLabel: {
    color: "#172033",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  cardExpandedText: {
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  cardExpandedFactsRow: {
    flexDirection: "row",
    gap: 8,
  },
  cardExpandedFactCard: {
    flex: 1,
    minHeight: 62,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderWidth: 1,
  },
  cardExpandedFactCardDanger: {
    backgroundColor: "#FFF0F0",
    borderColor: "#F3CACA",
  },
  cardExpandedFactCardWarning: {
    backgroundColor: "#FFF6E8",
    borderColor: "#F4DEC0",
  },
  cardExpandedFactLabel: {
    color: "#8A94A6",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  cardExpandedFactValue: {
    marginTop: 4,
    color: "#172033",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  cardExpandedAction: {
    width: "100%",
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.72)",
    alignItems: "center",
    justifyContent: "center",
  },
  cardExpandedActionPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  cardExpandedActionText: {
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  primaryCta: {
    marginTop: 8,
    minHeight: 74,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#F2C2B8",
    backgroundColor: "#FFF7F1",
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  primaryCtaPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.9,
  },
  primaryCtaIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F26F6C",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryCtaLabel: {
    color: "#F26F6C",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "800",
    fontFamily: journalTypography.body,
  },
  emptyCard: {
    marginTop: 8,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.78)",
    padding: 24,
    alignItems: "center",
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  emptyIconCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "#FFF0E8",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    color: "#172033",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
    textAlign: "center",
    fontFamily: journalTypography.display,
  },
  emptyDescription: {
    marginTop: 8,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    textAlign: "center",
    fontFamily: journalTypography.body,
  },
  emptyButton: {
    marginTop: 18,
    minHeight: 48,
    borderRadius: 24,
    paddingHorizontal: 18,
    backgroundColor: "#F56565",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
    fontFamily: journalTypography.body,
  },
});
