import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const medicineCabinetOverviewStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#FFF7F1",
  },
  gradient: {
    flex: 1,
  },
  decorationTop: {
    position: "absolute",
    top: -72,
    right: -28,
    width: 186,
    height: 186,
    borderRadius: 93,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  decorationMiddle: {
    position: "absolute",
    top: 224,
    left: -44,
    width: 136,
    height: 136,
    borderRadius: 68,
    backgroundColor: "rgba(255,240,232,0.58)",
  },
  screen: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 58,
    paddingHorizontal: 22,
    paddingBottom: 188,
    gap: 14,
  },
  header: {
    gap: 18,
  },
  headerControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  moduleIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "rgba(23, 32, 51, 0.08)",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  iconButtonGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.75)",
    alignItems: "center",
    justifyContent: "center",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  titleGroup: {
    flex: 1,
    gap: 6,
    paddingRight: 4,
  },
  title: {
    color: "#172033",
    fontSize: 42,
    lineHeight: 44,
    fontWeight: "800",
    letterSpacing: -1.6,
    fontFamily: journalTypography.display,
  },
  subtitle: {
    color: "#5F6B7A",
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  notificationsPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 18,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F0CFC4",
    backgroundColor: "rgba(255,255,255,0.55)",
  },
  notificationsLabel: {
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  infoLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoLineText: {
    flex: 1,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  infoLineTextStrong: {
    color: "#172033",
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  summaryCard: {
    marginTop: 6,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.78)",
    padding: 14,
    flexDirection: "row",
    gap: 10,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  statTile: {
    flex: 1,
    minHeight: 76,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: "space-between",
  },
  statTileActive: {
    borderWidth: 1.5,
    borderColor: "#F0B8AC",
  },
  statIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  statNumber: {
    color: "#172033",
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "800",
    fontFamily: journalTypography.display,
    letterSpacing: -0.5,
  },
  statLabel: {
    color: "#5F6B7A",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  searchBar: {
    marginTop: 8,
    minHeight: 58,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.82)",
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchInput: {
    flex: 1,
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    paddingVertical: 0,
    fontFamily: journalTypography.body,
  },
  filterRowContent: {
    paddingRight: 4,
    gap: 8,
  },
  filterChip: {
    minHeight: 38,
    borderRadius: 19,
    borderWidth: 1,
    paddingHorizontal: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    justifyContent: "center",
  },
  filterChipText: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  sectionHeader: {
    marginTop: 6,
    gap: 2,
  },
  sectionTitle: {
    color: "#172033",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  sectionSubtitle: {
    color: "#8A94A6",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  list: {
    gap: 10,
  },
  medicineCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.86)",
    paddingTop: 12,
    paddingRight: 14,
    paddingBottom: 12,
    paddingLeft: 14,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  medicineCardPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.96,
  },
  medicineCardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  medicineArtCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  medicineInfo: {
    flex: 1,
    gap: 4,
  },
  medicineTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.display,
    letterSpacing: -0.2,
  },
  medicineSubtitle: {
    color: "#8A94A6",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 2,
  },
  tag: {
    minHeight: 22,
    borderRadius: 11,
    paddingHorizontal: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  tagText: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  medicineRight: {
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 8,
  },
  statusBadge: {
    minHeight: 34,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
    maxWidth: 108,
  },
  statusText: {
    textAlign: "center",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  primaryCta: {
    marginTop: 8,
    minHeight: 58,
    borderRadius: 29,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "rgba(245, 101, 101, 0.24)",
    shadowOpacity: 0.32,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
  },
  primaryCtaPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.94,
  },
  primaryCtaIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryCtaLabel: {
    color: "#FFFFFF",
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.body,
  },
  emptyCard: {
    marginTop: 8,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.78)",
    padding: 24,
    alignItems: "center",
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  emptyIconCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "#FFF0E8",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    color: "#172033",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
    textAlign: "center",
    fontFamily: journalTypography.display,
  },
  emptyDescription: {
    marginTop: 8,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    textAlign: "center",
    fontFamily: journalTypography.body,
  },
  emptyButton: {
    marginTop: 18,
    minHeight: 48,
    borderRadius: 24,
    paddingHorizontal: 18,
    backgroundColor: "#F56565",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
    fontFamily: journalTypography.body,
  },
});
