import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "transparent",
  },
  frame: {
    flex: 1,
  },
  keyboardAvoiding: {
    flex: 1,
  },
  backgroundStepLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
    transform: [{ translateX: 0 }, { scale: 1 }],
    opacity: 1,
  },
  foregroundStepLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
    shadowColor: "#172033",
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: -8, height: 0 },
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  gradient: {
    flex: 1,
  },
  decorationTop: {
    position: "absolute",
    top: -82,
    right: -30,
    width: 194,
    height: 194,
    borderRadius: 97,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  decorationBottom: {
    position: "absolute",
    left: -44,
    bottom: 112,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(255,240,232,0.62)",
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingTop: 54,
    paddingHorizontal: 16,
    paddingBottom: 120,
  },
  topBar: {
    minHeight: 44,
  },
  backLink: {
    minHeight: 34,
    justifyContent: "center",
  },
  backLinkPressed: {
    opacity: 0.8,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  header: {
    marginTop: 12,
  },
  title: {
    color: "#172033",
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "800",
    letterSpacing: -0.6,
    fontFamily: journalTypography.display,
  },
  progressRow: {
    marginTop: 16,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
  },
  progressStepWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  progressStep: {
    flex: 1,
    minHeight: 34,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "transparent",
    paddingHorizontal: 9,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  progressStepActive: {
    backgroundColor: "#FFF0E8",
    borderColor: "#F0D8CC",
  },
  progressConnector: {
    width: 12,
    height: 1,
    backgroundColor: "#F0D8CC",
    marginHorizontal: 3,
  },
  progressConnectorPlaceholder: {
    opacity: 0,
  },
  progressNumberBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  progressNumberBadgeActive: {
    backgroundColor: "#F56565",
    borderColor: "#F56565",
  },
  progressNumberBadgeCompleted: {
    backgroundColor: "#FFF0E8",
    borderColor: "#F0D8CC",
  },
  progressNumberBadgeInactive: {
    backgroundColor: "#FFF7F1",
    borderColor: "#F0D8CC",
  },
  progressNumberText: {
    fontSize: 10,
    lineHeight: 10,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  progressNumberTextActive: {
    color: "#FFFFFF",
  },
  progressNumberTextCompleted: {
    color: "#E85050",
  },
  progressNumberTextInactive: {
    color: "#B8A59C",
  },
  progressStepLabel: {
    flexShrink: 1,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    textAlign: "center",
    letterSpacing: -0.1,
  },
  progressStepLabelActive: {
    color: "#172033",
  },
  progressStepLabelInactive: {
    color: "#9A8D87",
  },
  sectionCard: {
    marginTop: 20,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.84)",
    padding: 18,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  sectionCardUsage: {
    marginTop: 20,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#DDD0FB",
    backgroundColor: "rgba(245,240,255,0.92)",
    padding: 18,
    shadowColor: "#172033",
    shadowOpacity: 0.05,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
  },
  sectionCardStorage: {
    marginTop: 20,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#CDEBDD",
    backgroundColor: "rgba(255,255,255,0.84)",
    padding: 18,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 8 },
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionHeaderIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sectionAccent: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#F56565",
  },
  sectionTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  fieldBlock: {
    marginTop: 16,
  },
  inlineFieldRow: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  inlineFieldLabelWrap: {
    width: 128,
    flexShrink: 0,
  },
  fieldLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 7,
  },
  fieldLabelStandalone: {
    marginBottom: 7,
  },
  fieldLabelIcon: {
    flexShrink: 0,
  },
  fieldLabel: {
    color: "#172033",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  inputWrap: {
    minHeight: 46,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingHorizontal: 13,
    paddingVertical: 6,
    justifyContent: "center",
  },
  input: {
    flex: 1,
    color: "#172033",
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    paddingVertical: 0,
    includeFontPadding: false,
  },
  textareaWrap: {
    minHeight: 72,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingTop: 9,
    paddingRight: 13,
    paddingBottom: 9,
    paddingLeft: 13,
  },
  textarea: {
    minHeight: 44,
    color: "#172033",
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    paddingVertical: 0,
    includeFontPadding: false,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  categoryCard: {
    flexBasis: "47%",
    flexGrow: 1,
    minHeight: 60,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 10,
  },
  categoryCardActive: {
    borderColor: "#F56565",
    backgroundColor: "#FFF0E8",
  },
  categoryCardPressed: {
    opacity: 0.9,
  },
  categoryCardIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  categoryCardIconImage: {
    width: 18,
    height: 18,
  },
  categoryCardIconImageSkin: {
    width: 21,
    height: 21,
  },
  categoryCardLabel: {
    flexShrink: 1,
    color: "#172033",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    textAlign: "center",
  },
  previewCardCompact: {
    marginTop: 14,
    minHeight: 78,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.82)",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  previewCardFinal: {
    marginTop: 16,
    minHeight: 82,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.82)",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  previewMediaCircleCompact: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#F1EBFF",
    alignItems: "center",
    justifyContent: "center",
  },
  previewMediaCircleFinal: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#F1EBFF",
    alignItems: "center",
    justifyContent: "center",
  },
  previewImageCompact: {
    width: 42,
    height: 42,
  },
  previewImageFinal: {
    width: 44,
    height: 44,
  },
  previewCopy: {
    flex: 1,
    gap: 2,
  },
  previewTitle: {
    color: "#172033",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  previewSubtitle: {
    color: "#8A94A6",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  inlineDateField: {
    flex: 1,
    minHeight: 46,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  sheetOverlay: {
    justifyContent: "flex-end",
  },
  sheetBackdrop: {
    backgroundColor: "rgba(22, 32, 43, 0.24)",
  },
  customValueSheetCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFFCF8",
    paddingTop: 14,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderColor: "#EED8CE",
  },
  sheetDragZone: {
    paddingHorizontal: 16,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 46,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#DDC8BE",
    marginBottom: 14,
  },
  sheetTitle: {
    color: "#1E2A3A",
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  sheetSubtitle: {
    marginTop: 6,
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  customValueInput: {
    marginTop: 16,
    marginHorizontal: 16,
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingHorizontal: 14,
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    includeFontPadding: false,
  },
  customValueActions: {
    marginTop: 16,
    marginHorizontal: 16,
    flexDirection: "row",
    gap: 12,
  },
  customValueCancelButton: {
    width: 108,
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F56565",
    backgroundColor: "rgba(255,255,255,0.58)",
    alignItems: "center",
    justifyContent: "center",
  },
  customValueCancelText: {
    color: "#F56565",
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  customValueSaveButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 24,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  customValueSaveGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  customValueSaveText: {
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  dateInput: {
    flex: 1,
    color: "#172033",
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    paddingVertical: 0,
    includeFontPadding: false,
  },
  datePlaceholderText: {
    color: "#A0A8B5",
  },
  helperText: {
    marginTop: 6,
    color: "#8A94A6",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  footer: {
    marginTop: 16,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 2,
    paddingBottom: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "transparent",
  },
  secondaryButton: {
    width: 104,
    minHeight: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#F56565",
    backgroundColor: "rgba(255,255,255,0.58)",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonPressed: {
    opacity: 0.86,
  },
  secondaryButtonText: {
    color: "#F56565",
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  primaryButtonGradient: {
    flex: 1,
    minHeight: 52,
    borderRadius: 26,
    shadowColor: "rgba(245, 101, 101, 0.24)",
    shadowOpacity: 0.32,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 26,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  primaryButtonDisabled: {
    opacity: 0.92,
  },
  primaryButtonPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.985 }],
  },
  primaryButtonIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
});
