import type { AppLanguage } from "@shared/i18n";

export const settingsCopy = {
  ru: {
    title: "Настройки",
    subtitle: "Язык, тема, уведомления и безопасность.",
    mobileHint: "Язык, тема, уведомления и безопасность аккаунта.",
    pushConfigCheckFailed: "Не удалось быстро проверить настройки push на сервере.",
    reminderSaveFailed: "Не удалось сохранить время дополнительного напоминания.",
    devicePushCheckFailed: "Не удалось быстро проверить push на этом устройстве.",
    passwordUpdated: "Пароль обновлён.",
    passwordChangeFailed: "Не удалось сменить пароль.",
    pushServerNotReady: "Push-уведомления ещё не настроены на сервере.",
    pushUnsupported: "На этом устройстве push-уведомления недоступны.",
    permissionTimeout: "Устройство не завершило запрос разрешения на уведомления.",
    permissionDenied: "Устройство не дало разрешение на уведомления.",
    nativePermissionBlockedTitle: "Уведомления выключены в iOS",
    nativePermissionBlockedDescription:
      "Откройте настройки iPhone и включите уведомления для приложения.",
    openSystemSettings: "Открыть настройки",
    nativePermissionManualHint:
      "Если настройки не открылись автоматически: iPhone → Настройки → PillPath → Уведомления.",
    subscribeTimeout: "Не удалось завершить подписку устройства на push.",
    serverAcceptFailed: "Сервер не принял подписку устройства.",
    enablePushFailed: "Не удалось включить уведомления на этом устройстве.",
    disablePushFailed: "Не удалось отключить уведомления.",
    fillAllPasswordFields: "Заполните все поля пароля.",
    passwordsMismatch: "Новый пароль и подтверждение не совпадают.",
    passwordTooShort: "Новый пароль должен быть не короче 8 символов.",
    changePassword: "Сменить пароль",
    changePasswordHint: "Обновите пароль для входа в аккаунт.",
    recoveryCode: "Код восстановления",
    recoveryCodeHint:
      "Фраза для восстановления доступа внутри приложения, пока нет сброса пароля по письму.",
    recoveryCodeLockedHint: "Кодовая фраза для смены пароля установлена.",
    recoveryCodeLabel: "Новый код восстановления",
    recoveryCodePlaceholder: "Например: quiet-river-42",
    recoveryCodeTooShort: "Код восстановления должен быть не короче 8 символов.",
    recoveryCodeUpdated: "Код восстановления сохранён.",
    recoveryCodeConfigured: "Уже настроена",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmNewPassword: "Повтори новый пароль",
    saving: "Сохраняем…",
    updatePassword: "Обновить пароль",
    medicationPlans: "Планы лекарств",
    medicationPlansHint: "Как показывать интервал в планах: в часах или в минутах.",
    hours: "Часы",
    minutes: "Минуты",
    hoursShort: "Часы",
    minutesShort: "Мин.",
    interfaceLanguage: "Язык",
    interfaceLanguageHint: "Выберите язык интерфейса приложения.",
    interfaceTheme: "Тема",
    interfaceThemeHint: "Светлая, тёмная или автоматически как в системе.",
    themeLight: "Светлая",
    themeDark: "Тёмная",
    themeAuto: "Авто",
    themeShortLight: "День",
    themeShortDark: "Ночь",
    themeShortAuto: "Авто",
    chooseTheme: "Выберите тему",
    chooseThemeAria: "Выбор темы",
    intervalUnitTitle: "Единица интервала",
    chooseLanguage: "Выберите язык",
    chooseLanguageAria: "Выбор языка",
    chooseAction: "Выбрать",
    notifications: "Уведомления",
    notificationsHint:
      "Выберите, по каким категориям получать push и за сколько минут напоминать заранее.",
    testPushTitle: "Тестовый push",
    testPushHint: "Dev-only отправка уведомления на текущие подписки аккаунта.",
    testPushSending: "Отправляем тестовый push...",
    testPushSent: "Тестовый push отправлен. Подписок: {{count}}.",
    testPushNoSubscriptions: "У аккаунта нет активных push-подписок.",
    testPushFailed: "Тестовый push не отправлен",
    liveActivities: "Live Activity",
    liveActivitiesHint:
      "Живой статус на iPhone: большая карточка на экране блокировки и компактная бровь в Dynamic Island.",
    liveActivitiesAppleOnly:
      "На iPhone Live Activity показывает карточку на локскрине и компактную бровь сверху в Dynamic Island.",
    liveActivitiesSleep: "Сон на экране блокировки",
    liveActivitiesSleepHint: "Показывать большой таймер, пока сессия сна активна.",
    liveActivitiesFeeding: "Кормление на экране блокировки",
    liveActivitiesFeedingHint: "Показывать большой таймер активного кормления.",
    liveActivitiesIllness: "Болезнь на экране блокировки",
    liveActivitiesIllnessHint: "Показывать активный эпизод болезни для доступных вам детей.",
    liveActivitiesPreviewLabel: "Превью",
    liveActivitiesSleepPreviewTitle: "Сон",
    liveActivitiesFeedingPreviewTitle: "Кормление",
    liveActivitiesIllnessPreviewTitle: "Болезнь",
    liveActivitiesSleepPreviewStatus: "Идёт сон",
    liveActivitiesFeedingPreviewStatus: "Идёт кормление",
    liveActivitiesIllnessPreviewStatus: "Идёт наблюдение",
    liveActivitiesIllnessPreviewTimer: "3 день",
    liveActivitiesIllnessPreviewDetails: "Маша · Дать Нурофен в 23:10",
    liveActivitiesPreviewFromLockScreen: "Тап открывает нужного ребёнка в разделе «Дети»",
    liveActivitiesPreviewOpen: "Открыть",
    liveActivitiesLockedReason: "Откройте Live Activities в Plus.",
    liveActivitiesUpgrade: "Подключить Plus",
    childrenReminders: "По детям",
    pillboxReminders: "По таблетнице",
    childrenRemindersSoftText: "Полностью включить или выключить push по детям.",
    pillboxRemindersSoftText: "Полностью включить или выключить push по таблетнице.",
    pushServerMissing: "Push на сервере пока не настроен.",
    disableNotifications: "Выключить уведомления",
    enableNotifications: "Включить уведомления",
    minShort: "мин",
    cabinetReminders: "По аптечке",
    cabinetRemindersSoftText: "Напомнить заранее проверить аптечку.",
    confirmDisableNotifications: "Точно выключить push-уведомления на этом устройстве?",
    cancel: "Отмена",
    confirmDisable: "Да, выключить",
    days10: "За 10 дней",
    days7: "За 7 дней",
    days3: "За 3 дня",
    dangerZone: "Опасная зона",
    dangerZoneHint: "Эти действия нельзя отменить.",
    subscriptionSection: "Подписка",
    subscriptionSectionHint:
      "Проверяйте статус Plus, восстанавливайте покупки и открывайте системное управление подпиской.",
    subscriptionStatusLabel: "Статус подписки",
    subscriptionManageAction: "Управлять подпиской",
    subscriptionRestorePurchases: "Восстановить покупки",
    subscriptionStatusInactive: "Plus не активна",
    subscriptionStatusTrialing: "Пробный период Plus",
    subscriptionStatusActive: "Plus активна",
    subscriptionStatusGrace: "Проблема с оплатой, доступ пока сохранён",
    subscriptionStatusCanceled: "Автопродление выключено, доступ ещё действует",
    subscriptionStatusExpired: "Plus истекла",
    deleteAccount: "Удалить аккаунт",
    deleteAccountDescription: "Вы выйдете из приложения, а доступ к аккаунту будет закрыт.",
    deleteAccountConfirmTitle: "Точно удалить аккаунт?",
    deleteAccountConfirmDescription:
      "Аккаунт будет деактивирован. Вход в него станет недоступен, восстановление не предусмотрено.",
    deleteAccountConfirmAction: "Да, удалить аккаунт",
    deleteAccountFailed: "Не удалось удалить аккаунт.",
    cancelSubscription: "Отменить подписку",
    cancelSubscriptionDescription:
      "Если позже захотите удалить семью, сначала отключите автопродление. Доступ Plus сохранится до конца оплаченного периода.",
    deleteFamily: "Удалить семью",
    deleteFamilyDescription: "Удалит семью и отключит доступ для всех участников.",
    deleteFamilyBlockedDescription:
      "Семью нельзя удалить, пока у неё ещё действует Plus. Даже если продление уже отменено, доступ сохраняется до конца оплаченного периода.",
    subscriptionAutoRenewOn: "Автопродление: включено",
    subscriptionAutoRenewOff: "Автопродление: выключено",
    subscriptionActiveUntil: "Доступ до",
    deleteFamilyConfirmTitle: "Точно удалить семью?",
    deleteFamilyConfirmDescription: "Все аккаунты семьи будут деактивированы. Действие необратимо.",
    deleteFamilyConfirmAction: "Да, удалить семью",
    deleteFamilyBlockedTitle: "Семью пока нельзя удалить",
    deleteFamilyBlockedConfirmDescription:
      "У семьи ещё действует период доступа Plus. Простая отмена продления не выключает доступ сразу: сначала дождитесь окончания периода, и только потом удаляйте семью.",
    deleteFamilyBlockedConfirmAction: "Управлять подпиской",
    deleteFamilyFailed: "Не удалось удалить семью.",
    settingsBack: "← Настройки",
    moreBack: "← Ещё",
    showPassword: "Показать пароль",
    hidePassword: "Скрыть пароль",
  },
  en: {
    title: "Settings",
    subtitle: "Language, theme, reminders and security.",
    mobileHint: "Language, theme, notifications and account security.",
    pushConfigCheckFailed: "Could not quickly verify push settings on the server.",
    reminderSaveFailed: "Could not save the advance reminder time.",
    devicePushCheckFailed: "Could not quickly verify push on this device.",
    passwordUpdated: "Password updated.",
    passwordChangeFailed: "Could not change the password.",
    pushServerNotReady: "Push notifications are not configured on the server yet.",
    pushUnsupported: "Push notifications are not available on this device.",
    permissionTimeout: "The device did not finish the notification permission request.",
    permissionDenied: "The device did not grant notification permission.",
    nativePermissionBlockedTitle: "Notifications are off in iOS",
    nativePermissionBlockedDescription:
      "Open iPhone settings and enable notifications for the app.",
    openSystemSettings: "Open Settings",
    nativePermissionManualHint:
      "If Settings did not open automatically: iPhone → Settings → PillPath → Notifications.",
    subscribeTimeout: "Could not finish subscribing this device to push.",
    serverAcceptFailed: "The server did not accept the device subscription.",
    enablePushFailed: "Could not enable notifications on this device.",
    disablePushFailed: "Could not disable notifications.",
    fillAllPasswordFields: "Fill in all password fields.",
    passwordsMismatch: "New password and confirmation do not match.",
    passwordTooShort: "The new password must be at least 8 characters long.",
    changePassword: "Change password",
    changePasswordHint: "Update the password used to sign in.",
    recoveryCode: "Recovery code",
    recoveryCodeHint:
      "A recovery phrase used inside the app while email-based password reset is not available yet.",
    recoveryCodeLockedHint: "The recovery phrase for password reset is set.",
    recoveryCodeLabel: "New recovery code",
    recoveryCodePlaceholder: "Example: quiet-river-42",
    recoveryCodeTooShort: "Recovery code must be at least 8 characters long.",
    recoveryCodeUpdated: "Recovery code saved.",
    recoveryCodeConfigured: "Already set",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmNewPassword: "Repeat new password",
    saving: "Saving…",
    updatePassword: "Update password",
    medicationPlans: "Medication plans",
    medicationPlansHint: "How to show interval values in plans: hours or minutes.",
    hours: "Hours",
    minutes: "Minutes",
    hoursShort: "Hours",
    minutesShort: "Min.",
    interfaceLanguage: "Language",
    interfaceLanguageHint: "Choose the language used across the app interface.",
    interfaceTheme: "Theme",
    interfaceThemeHint: "Light, dark, or automatically follow the system.",
    themeLight: "Light",
    themeDark: "Dark",
    themeAuto: "Auto",
    themeShortLight: "Day",
    themeShortDark: "Night",
    themeShortAuto: "Auto",
    chooseTheme: "Choose theme",
    chooseThemeAria: "Choose theme",
    intervalUnitTitle: "Interval unit",
    chooseLanguage: "Choose language",
    chooseLanguageAria: "Choose language",
    chooseAction: "Select",
    notifications: "Notifications",
    notificationsHint:
      "Choose which categories can send push and how early advance reminders should arrive.",
    testPushTitle: "Test push",
    testPushHint: "Dev-only notification to the current account subscriptions.",
    testPushSending: "Sending test push...",
    testPushSent: "Test push sent. Subscriptions: {{count}}.",
    testPushNoSubscriptions: "This account has no active push subscriptions.",
    testPushFailed: "Test push failed",
    liveActivities: "Live Activity",
    liveActivitiesHint:
      "A live status on iPhone: a large card on the lock screen and a compact eyebrow in Dynamic Island.",
    liveActivitiesAppleOnly:
      "On iPhone, Live Activity shows a lock screen card and a compact top eyebrow in Dynamic Island.",
    liveActivitiesSleep: "Sleep on the lock screen",
    liveActivitiesSleepHint: "Show a large timer while a sleep session is active.",
    liveActivitiesFeeding: "Feeding on the lock screen",
    liveActivitiesFeedingHint: "Show a large timer for an active feeding session.",
    liveActivitiesIllness: "Illness on the lock screen",
    liveActivitiesIllnessHint: "Show the active illness episode for children you can access.",
    liveActivitiesPreviewLabel: "Preview",
    liveActivitiesSleepPreviewTitle: "Sleep",
    liveActivitiesFeedingPreviewTitle: "Feeding",
    liveActivitiesIllnessPreviewTitle: "Illness",
    liveActivitiesSleepPreviewStatus: "Sleep in progress",
    liveActivitiesFeedingPreviewStatus: "Feeding in progress",
    liveActivitiesIllnessPreviewStatus: "Tracking in progress",
    liveActivitiesIllnessPreviewTimer: "Day 3",
    liveActivitiesIllnessPreviewDetails: "Mia · Give Nurofen at 11:10 PM",
    liveActivitiesPreviewFromLockScreen: "Tap opens the right child in the Children section",
    liveActivitiesPreviewOpen: "Open",
    liveActivitiesLockedReason: "Unlock Live Activities in Plus.",
    liveActivitiesUpgrade: "Get Plus",
    childrenReminders: "For children",
    pillboxReminders: "For pillbox",
    childrenRemindersSoftText: "Turn all children push notifications on or off.",
    pillboxRemindersSoftText: "Turn all pillbox push notifications on or off.",
    pushServerMissing: "Push is not configured on the server yet.",
    disableNotifications: "Turn off notifications",
    enableNotifications: "Turn on notifications",
    minShort: "min",
    cabinetReminders: "For cabinet",
    cabinetRemindersSoftText: "Remind me to check the cabinet.",
    confirmDisableNotifications: "Turn off push notifications on this device?",
    cancel: "Cancel",
    confirmDisable: "Yes, turn off",
    days10: "10 days before",
    days7: "7 days before",
    days3: "3 days before",
    dangerZone: "Danger zone",
    dangerZoneHint: "These actions cannot be undone.",
    subscriptionSection: "Subscription",
    subscriptionSectionHint:
      "Check Plus status, restore purchases, and open the system subscription management screen.",
    subscriptionStatusLabel: "Subscription status",
    subscriptionManageAction: "Manage subscription",
    subscriptionRestorePurchases: "Restore purchases",
    subscriptionStatusInactive: "Plus is not active",
    subscriptionStatusTrialing: "Plus trial is active",
    subscriptionStatusActive: "Plus is active",
    subscriptionStatusGrace: "Billing issue, access is still active",
    subscriptionStatusCanceled: "Auto-renew is off, access is still active",
    subscriptionStatusExpired: "Plus has expired",
    deleteAccount: "Delete account",
    deleteAccountDescription: "You will be signed out and access to this account will be removed.",
    deleteAccountConfirmTitle: "Delete account permanently?",
    deleteAccountConfirmDescription:
      "The account will be deactivated. Login will no longer be possible.",
    deleteAccountConfirmAction: "Yes, delete account",
    deleteAccountFailed: "Could not delete the account.",
    cancelSubscription: "Cancel subscription",
    cancelSubscriptionDescription:
      "If you plan to delete the family later, disable auto-renew first. Plus access will remain until the end of the paid period.",
    deleteFamily: "Delete family",
    deleteFamilyDescription: "Deletes the family and removes access for all members.",
    deleteFamilyBlockedDescription:
      "The family cannot be deleted while Plus access is still active. Even if renewal is already canceled, access remains until the end of the paid period.",
    subscriptionAutoRenewOn: "Auto-renew: on",
    subscriptionAutoRenewOff: "Auto-renew: off",
    subscriptionActiveUntil: "Access until",
    deleteFamilyConfirmTitle: "Delete family completely?",
    deleteFamilyConfirmDescription:
      "All family accounts will be deactivated. This action cannot be undone.",
    deleteFamilyConfirmAction: "Yes, delete family",
    deleteFamilyBlockedTitle: "This family cannot be deleted yet",
    deleteFamilyBlockedConfirmDescription:
      "The family still has an active Plus access period. Canceling renewal does not remove access immediately: wait until the period ends, then delete the family.",
    deleteFamilyBlockedConfirmAction: "Manage subscription",
    deleteFamilyFailed: "Could not delete the family.",
    settingsBack: "← Settings",
    moreBack: "← More",
    showPassword: "Show password",
    hidePassword: "Hide password",
  },
} satisfies Record<AppLanguage, Record<string, string>>;

export function tSettings(language: AppLanguage, key: keyof (typeof settingsCopy)["ru"]) {
  return settingsCopy[language][key];
}
