import type { AppLanguage } from "@shared/i18n";

export const settingsCopy = {
  ru: {
    title: "Настройки",
    subtitle: "Язык, тема, уведомления и безопасность.",
    pushConfigCheckFailed: "Не удалось быстро проверить настройки push на сервере.",
    reminderSaveFailed: "Не удалось сохранить время дополнительного напоминания.",
    devicePushCheckFailed: "Не удалось быстро проверить push на этом устройстве.",
    passwordUpdated: "Пароль обновлён.",
    passwordChangeFailed: "Не удалось сменить пароль.",
    pushServerNotReady: "Push-уведомления ещё не настроены на сервере.",
    pushUnsupported: "На этом устройстве push-уведомления недоступны.",
    permissionTimeout: "Браузер не завершил запрос разрешения на уведомления.",
    permissionDenied: "Браузер не дал разрешение на уведомления.",
    nativePermissionBlockedTitle: "Уведомления выключены в iOS",
    nativePermissionBlockedDescription:
      "PillPath больше не может показать системный запрос. Откройте настройки iPhone и включите уведомления для приложения.",
    openSystemSettings: "Открыть настройки",
    nativePermissionManualHint:
      "Если настройки не открылись автоматически: iPhone → Настройки → PillPath → Уведомления.",
    subscribeTimeout: "Не удалось завершить подписку устройства на push.",
    serverAcceptFailed: "Сервер не принял подписку устройства.",
    enablePushFailed: "Не удалось включить уведомления на этом устройстве.",
    disablePushFailed: "Не удалось отключить уведомления.",
    fillAllPasswordFields: "Заполните все поля пароля.",
    passwordsMismatch: "Новый пароль и подтверждение не совпадают.",
    passwordTooShort: "Новый пароль должен быть не короче 6 символов.",
    changePassword: "Сменить пароль",
    changePasswordHint: "Открывается только когда нужно, чтобы не перегружать экран.",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmNewPassword: "Повтори новый пароль",
    saving: "Сохраняем…",
    updatePassword: "Обновить пароль",
    medicationPlans: "Планы лекарств",
    medicationPlansHint: "Как показывать интервал в планах: в часах или в минутах.",
    hours: "Часы",
    minutes: "Минуты",
    appSettings: "Настройки приложения",
    appSettingsHint: "Язык интерфейса и тема для вашего аккаунта.",
    interfaceLanguage: "Язык",
    interfaceTheme: "Тема",
    themeLight: "Светлая",
    themeDark: "Тёмная",
    themeAuto: "Авто",
    notifications: "Уведомления",
    notificationsHint:
      "Пуш в момент события приходит всегда. Здесь вы настраиваете дополнительные уведомления.",
    childrenReminders: "Уведомление по детям",
    pillboxReminders: "Уведомление по таблетнице",
    childrenRemindersSoftText: "Мягкое напоминание заранее, чтобы спокойно подготовиться.",
    pillboxRemindersSoftText: "Короткий сигнал заранее, чтобы не держать всё в голове.",
    pushServerMissing: "Серверная отправка push пока не настроена.",
    disableNotifications: "Выключить уведомления",
    enableNotifications: "Включить уведомления",
    reminderOn: "Вкл",
    reminderOff: "Выкл",
    minShort: "мин",
    cabinetReminders: "Уведомление по аптечке",
    cabinetRemindersSoftText: "Напомним заранее, чтобы вы успели проверить аптечку дома.",
    notificationsStatusOn: "Активно",
    notificationsStatusOff: "Неактивно",
    confirmDisableNotifications: "Точно выключить push-уведомления на этом устройстве?",
    cancel: "Отмена",
    confirmDisable: "Да, выключить",
    days10: "За 10 дней",
    days7: "За 7 дней",
    days3: "За 3 дня",
    dangerZone: "Опасная зона",
    dangerZoneHint:
      "Удаление аккаунта необратимо. Если вы единственный участник семьи, семейные данные тоже будут удалены.",
    deleteAccount: "Удалить аккаунт",
    deleteAccountDescription:
      "После удаления аккаунта вы сразу выйдете из приложения. Если вы единственный owner, права owner автоматически перейдут следующему участнику.",
    deleteAccountConfirmTitle: "Точно удалить аккаунт?",
    deleteAccountConfirmDescription:
      "Аккаунт будет деактивирован. Вход в него станет недоступен, восстановление не предусмотрено.",
    deleteAccountConfirmAction: "Да, удалить аккаунт",
    deleteAccountFailed: "Не удалось удалить аккаунт.",
    deleteFamily: "Удалить семью полностью",
    deleteFamilyDescription:
      "Удаляет доступ ко всем аккаунтам семьи. Все участники будут разлогинены и деактивированы.",
    deleteFamilyConfirmTitle: "Точно удалить семью?",
    deleteFamilyConfirmDescription: "Все аккаунты семьи будут деактивированы. Действие необратимо.",
    deleteFamilyConfirmAction: "Да, удалить семью",
    deleteFamilyFailed: "Не удалось удалить семью.",
  },
  en: {
    title: "Settings",
    subtitle: "Language, theme, reminders and security.",
    pushConfigCheckFailed: "Could not quickly verify push settings on the server.",
    reminderSaveFailed: "Could not save the advance reminder time.",
    devicePushCheckFailed: "Could not quickly verify push on this device.",
    passwordUpdated: "Password updated.",
    passwordChangeFailed: "Could not change the password.",
    pushServerNotReady: "Push notifications are not configured on the server yet.",
    pushUnsupported: "Push notifications are not available on this device.",
    permissionTimeout: "The browser did not finish the notification permission request.",
    permissionDenied: "The browser did not grant notification permission.",
    nativePermissionBlockedTitle: "Notifications are off in iOS",
    nativePermissionBlockedDescription:
      "PillPath cannot show the system prompt again. Open iPhone settings and enable notifications for the app.",
    openSystemSettings: "Open Settings",
    nativePermissionManualHint:
      "If Settings did not open automatically: iPhone → Settings → PillPath → Notifications.",
    subscribeTimeout: "Could not finish subscribing this device to push.",
    serverAcceptFailed: "The server did not accept the device subscription.",
    enablePushFailed: "Could not enable notifications on this device.",
    disablePushFailed: "Could not disable notifications.",
    fillAllPasswordFields: "Fill in all password fields.",
    passwordsMismatch: "New password and confirmation do not match.",
    passwordTooShort: "The new password must be at least 6 characters long.",
    changePassword: "Change password",
    changePasswordHint: "Keep this collapsed until needed.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmNewPassword: "Repeat new password",
    saving: "Saving…",
    updatePassword: "Update password",
    medicationPlans: "Medication plans",
    medicationPlansHint: "How to show interval values in plans: hours or minutes.",
    hours: "Hours",
    minutes: "Minutes",
    appSettings: "App settings",
    appSettingsHint: "Interface language and app theme for your account.",
    interfaceLanguage: "Language",
    interfaceTheme: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeAuto: "Auto",
    notifications: "Notifications",
    notificationsHint:
      "The push at the event time is always sent. Here you configure additional reminders.",
    childrenReminders: "Child reminders",
    pillboxReminders: "Pillbox reminders",
    childrenRemindersSoftText: "A gentle early reminder so you can prepare calmly.",
    pillboxRemindersSoftText: "A short early heads-up, so you do not keep everything in mind.",
    pushServerMissing: "Server-side push delivery is not configured yet.",
    disableNotifications: "Turn off notifications",
    enableNotifications: "Turn on notifications",
    reminderOn: "On",
    reminderOff: "Off",
    minShort: "min",
    cabinetReminders: "Cabinet reminders",
    cabinetRemindersSoftText: "An early reminder so you have time to review your home cabinet.",
    notificationsStatusOn: "On",
    notificationsStatusOff: "Inactive",
    confirmDisableNotifications: "Turn off push notifications on this device?",
    cancel: "Cancel",
    confirmDisable: "Yes, turn off",
    days10: "10 days before",
    days7: "7 days before",
    days3: "3 days before",
    dangerZone: "Danger zone",
    dangerZoneHint:
      "Account deletion is irreversible. If you are the only family member, family data will be deleted too.",
    deleteAccount: "Delete account",
    deleteAccountDescription:
      "After deletion, you will be signed out immediately. If you are the only owner, owner rights are reassigned automatically.",
    deleteAccountConfirmTitle: "Delete account permanently?",
    deleteAccountConfirmDescription:
      "The account will be deactivated. Login will no longer be possible.",
    deleteAccountConfirmAction: "Yes, delete account",
    deleteAccountFailed: "Could not delete the account.",
    deleteFamily: "Delete family completely",
    deleteFamilyDescription:
      "Removes access for all family accounts. All members will be signed out and deactivated.",
    deleteFamilyConfirmTitle: "Delete family completely?",
    deleteFamilyConfirmDescription:
      "All family accounts will be deactivated. This action cannot be undone.",
    deleteFamilyConfirmAction: "Yes, delete family",
    deleteFamilyFailed: "Could not delete the family.",
  },
} satisfies Record<AppLanguage, Record<string, string>>;

export function tSettings(language: AppLanguage, key: keyof (typeof settingsCopy)["ru"]) {
  return settingsCopy[language][key];
}
