import type { AppLanguage } from "@shared/i18n";

export const settingsCopy = {
  ru: {
    title: "Настройки",
    subtitle: "Язык, тема, уведомления и безопасность.",
    mobileHint: "Язык, тема, уведомления и безопасность аккаунта.",
    pushConfigCheckFailed: "Не удалось быстро проверить настройки push на сервере.",
    reminderSaveFailed: "Не удалось сохранить время дополнительного напоминания.",
    devicePushCheckFailed: "Не удалось быстро проверить push на этом устройстве.",
    passwordUpdated: "Пароль обновлён.",
    passwordChangeFailed: "Не удалось сменить пароль.",
    pushServerNotReady: "Push-уведомления ещё не настроены на сервере.",
    pushUnsupported: "На этом устройстве push-уведомления недоступны.",
    permissionTimeout: "Браузер не завершил запрос разрешения на уведомления.",
    permissionDenied: "Браузер не дал разрешение на уведомления.",
    nativePermissionBlockedTitle: "Уведомления выключены в iOS",
    nativePermissionBlockedDescription:
      "Откройте настройки iPhone и включите уведомления для приложения.",
    openSystemSettings: "Открыть настройки",
    nativePermissionManualHint:
      "Если настройки не открылись автоматически: iPhone → Настройки → PillPath → Уведомления.",
    subscribeTimeout: "Не удалось завершить подписку устройства на push.",
    serverAcceptFailed: "Сервер не принял подписку устройства.",
    enablePushFailed: "Не удалось включить уведомления на этом устройстве.",
    disablePushFailed: "Не удалось отключить уведомления.",
    fillAllPasswordFields: "Заполните все поля пароля.",
    passwordsMismatch: "Новый пароль и подтверждение не совпадают.",
    passwordTooShort: "Новый пароль должен быть не короче 6 символов.",
    changePassword: "Сменить пароль",
    changePasswordHint: "Обновите пароль для входа в аккаунт.",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmNewPassword: "Повтори новый пароль",
    saving: "Сохраняем…",
    updatePassword: "Обновить пароль",
    medicationPlans: "Планы лекарств",
    medicationPlansHint: "Как показывать интервал в планах: в часах или в минутах.",
    hours: "Часы",
    minutes: "Минуты",
    interfaceLanguage: "Язык",
    interfaceLanguageHint: "Выберите язык интерфейса приложения.",
    interfaceTheme: "Тема",
    interfaceThemeHint: "Светлая, тёмная или автоматически как в системе.",
    themeLight: "Светлая",
    themeDark: "Тёмная",
    themeAuto: "Авто",
    notifications: "Уведомления",
    notificationsHint:
      "Здесь настраиваются только напоминания заранее.",
    childrenReminders: "По детям",
    pillboxReminders: "По таблетнице",
    childrenRemindersSoftText: "Напомнить заранее перед событием.",
    pillboxRemindersSoftText: "Короткое напоминание заранее.",
    pushServerMissing: "Push на сервере пока не настроен.",
    disableNotifications: "Выключить уведомления",
    enableNotifications: "Включить уведомления",
    minShort: "мин",
    cabinetReminders: "По аптечке",
    cabinetRemindersSoftText: "Напомнить заранее проверить аптечку.",
    confirmDisableNotifications: "Точно выключить push-уведомления на этом устройстве?",
    cancel: "Отмена",
    confirmDisable: "Да, выключить",
    days10: "За 10 дней",
    days7: "За 7 дней",
    days3: "За 3 дня",
    dangerZone: "Опасная зона",
    dangerZoneHint:
      "Эти действия нельзя отменить.",
    deleteAccount: "Удалить аккаунт",
    deleteAccountDescription:
      "Вы выйдете из приложения, а доступ к аккаунту будет закрыт.",
    deleteAccountConfirmTitle: "Точно удалить аккаунт?",
    deleteAccountConfirmDescription:
      "Аккаунт будет деактивирован. Вход в него станет недоступен, восстановление не предусмотрено.",
    deleteAccountConfirmAction: "Да, удалить аккаунт",
    deleteAccountFailed: "Не удалось удалить аккаунт.",
    deleteFamily: "Удалить семью",
    deleteFamilyDescription:
      "Удалит семью и отключит доступ для всех участников.",
    deleteFamilyConfirmTitle: "Точно удалить семью?",
    deleteFamilyConfirmDescription: "Все аккаунты семьи будут деактивированы. Действие необратимо.",
    deleteFamilyConfirmAction: "Да, удалить семью",
    deleteFamilyFailed: "Не удалось удалить семью.",
  },
  en: {
    title: "Settings",
    subtitle: "Language, theme, reminders and security.",
    mobileHint: "Language, theme, notifications and account security.",
    pushConfigCheckFailed: "Could not quickly verify push settings on the server.",
    reminderSaveFailed: "Could not save the advance reminder time.",
    devicePushCheckFailed: "Could not quickly verify push on this device.",
    passwordUpdated: "Password updated.",
    passwordChangeFailed: "Could not change the password.",
    pushServerNotReady: "Push notifications are not configured on the server yet.",
    pushUnsupported: "Push notifications are not available on this device.",
    permissionTimeout: "The browser did not finish the notification permission request.",
    permissionDenied: "The browser did not grant notification permission.",
    nativePermissionBlockedTitle: "Notifications are off in iOS",
    nativePermissionBlockedDescription:
      "Open iPhone settings and enable notifications for the app.",
    openSystemSettings: "Open Settings",
    nativePermissionManualHint:
      "If Settings did not open automatically: iPhone → Settings → PillPath → Notifications.",
    subscribeTimeout: "Could not finish subscribing this device to push.",
    serverAcceptFailed: "The server did not accept the device subscription.",
    enablePushFailed: "Could not enable notifications on this device.",
    disablePushFailed: "Could not disable notifications.",
    fillAllPasswordFields: "Fill in all password fields.",
    passwordsMismatch: "New password and confirmation do not match.",
    passwordTooShort: "The new password must be at least 6 characters long.",
    changePassword: "Change password",
    changePasswordHint: "Update the password used to sign in.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmNewPassword: "Repeat new password",
    saving: "Saving…",
    updatePassword: "Update password",
    medicationPlans: "Medication plans",
    medicationPlansHint: "How to show interval values in plans: hours or minutes.",
    hours: "Hours",
    minutes: "Minutes",
    interfaceLanguage: "Language",
    interfaceLanguageHint: "Choose the language used across the app interface.",
    interfaceTheme: "Theme",
    interfaceThemeHint: "Light, dark, or automatically follow the system.",
    themeLight: "Light",
    themeDark: "Dark",
    themeAuto: "Auto",
    notifications: "Notifications",
    notificationsHint:
      "Only advance reminders are configured here.",
    childrenReminders: "For children",
    pillboxReminders: "For pillbox",
    childrenRemindersSoftText: "Remind me before the event.",
    pillboxRemindersSoftText: "A short reminder in advance.",
    pushServerMissing: "Push is not configured on the server yet.",
    disableNotifications: "Turn off notifications",
    enableNotifications: "Turn on notifications",
    minShort: "min",
    cabinetReminders: "For cabinet",
    cabinetRemindersSoftText: "Remind me to check the cabinet.",
    confirmDisableNotifications: "Turn off push notifications on this device?",
    cancel: "Cancel",
    confirmDisable: "Yes, turn off",
    days10: "10 days before",
    days7: "7 days before",
    days3: "3 days before",
    dangerZone: "Danger zone",
    dangerZoneHint:
      "These actions cannot be undone.",
    deleteAccount: "Delete account",
    deleteAccountDescription:
      "You will be signed out and access to this account will be removed.",
    deleteAccountConfirmTitle: "Delete account permanently?",
    deleteAccountConfirmDescription:
      "The account will be deactivated. Login will no longer be possible.",
    deleteAccountConfirmAction: "Yes, delete account",
    deleteAccountFailed: "Could not delete the account.",
    deleteFamily: "Delete family",
    deleteFamilyDescription:
      "Deletes the family and removes access for all members.",
    deleteFamilyConfirmTitle: "Delete family completely?",
    deleteFamilyConfirmDescription:
      "All family accounts will be deactivated. This action cannot be undone.",
    deleteFamilyConfirmAction: "Yes, delete family",
    deleteFamilyFailed: "Could not delete the family.",
  },
} satisfies Record<AppLanguage, Record<string, string>>;

export function tSettings(language: AppLanguage, key: keyof (typeof settingsCopy)["ru"]) {
  return settingsCopy[language][key];
}
