import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 21,
    backgroundColor: "#FFF4EC",
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  background: {
    flex: 1,
    backgroundColor: "#FFF4EC",
  },
  backgroundImage: {
    opacity: 0.18,
  },
  overlayGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  root: {
    flex: 1,
  },
  innerOverlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 38,
    gap: 0,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  introBlock: {
    gap: 8,
    paddingRight: 12,
  },
  screenBlock: {
    marginTop: 16,
  },
  introHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  introTitleWrap: {
    flex: 1,
    gap: 4,
  },
  titleIconAssetWrap: {
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  titleIconAsset: {
    width: 60,
    height: 60,
  },
  title: {
    fontSize: 34,
    lineHeight: 38,
    fontWeight: "800",
    letterSpacing: -1,
  },
  subtitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    maxWidth: 324,
  },
  card: {
    borderRadius: 28,
    borderWidth: 1,
    padding: 18,
  },
  surfaceCard: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 16,
    gap: 14,
  },
  familyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  familyHeaderLeft: {
    flex: 1,
  },
  familyHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  familyLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  familyName: {
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  badge: {
    minHeight: 28,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    alignSelf: "flex-start",
  },
  badgeText: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "700",
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  statsRowCompact: {
    flexWrap: "wrap",
  },
  statCard: {
    flex: 1,
    minHeight: 88,
    borderRadius: 20,
    borderWidth: 1,
    padding: 14,
    gap: 10,
  },
  statCardCompact: {
    minWidth: "48%",
  },
  statIconTile: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  statAssetIcon: {
    width: 22,
    height: 22,
  },
  statCopy: {
    gap: 4,
  },
  statTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  statValue: {
    fontSize: 22,
    lineHeight: 24,
    fontWeight: "600",
    letterSpacing: -0.3,
  },
  statLabel: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "600",
  },
  sectionWrap: {
    gap: 8,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionIconButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
  },
  listCard: {
    borderRadius: 28,
    borderWidth: 1,
    overflow: "hidden",
  },
  memberRow: {
    minHeight: 118,
    paddingLeft: 16,
    paddingRight: 14,
    paddingTop: 14,
    paddingBottom: 14,
    flexDirection: "row",
    gap: 14,
    alignItems: "flex-start",
  },
  memberAvatar: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  memberAvatarText: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
  },
  memberContent: {
    flex: 1,
    gap: 8,
  },
  memberHeader: {
    gap: 4,
  },
  memberNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  memberName: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    letterSpacing: -0.3,
    flexShrink: 1,
  },
  memberRole: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
  },
  memberPhone: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
  },
  memberEditButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#E9D6CD",
    backgroundColor: "#FFF8F3",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    flexShrink: 0,
  },
  smallBadge: {
    minHeight: 24,
    paddingHorizontal: 9,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  smallBadgeText: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "700",
  },
  memberDescription: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  chevronWrap: {
    width: 22,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 18,
    flexShrink: 0,
  },
  rowDivider: {
    height: 1,
    marginLeft: 96,
  },
  inviteTopRow: {
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
  },
  inviteHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  inviteHeaderPressable: {
    flex: 1,
  },
  inviteIconTile: {
    width: 60,
    height: 60,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  inviteTopCopy: {
    flex: 1,
    gap: 4,
  },
  inviteRefreshButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  inviteRefreshButtonLocked: {
    borderColor: "#F4BDD7",
  },
  inviteTitle: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
  },
  inviteDescription: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  inviteCodeBox: {
    marginTop: 16,
    minHeight: 82,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: "center",
    gap: 6,
  },
  inviteCode: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  inviteStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  inviteStatusText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  inviteButtonsRow: {
    marginTop: 14,
    flexDirection: "row",
    gap: 10,
  },
  inviteFeedback: {
    marginTop: 12,
    minHeight: 38,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
  },
  inviteFeedbackText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "700",
  },
  inviteButtonsStack: {
    flexDirection: "column",
  },
  actionButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  actionButtonPressed: {
    opacity: 0.92,
  },
  actionButtonPrimary: {
    shadowColor: "rgba(245, 111, 104, 0.16)",
    shadowOpacity: 1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
  },
  actionButtonSecondary: {
    borderWidth: 1.5,
  },
  actionButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  rulesCard: {
    borderRadius: 24,
    borderWidth: 1,
    overflow: "hidden",
  },
  ruleRow: {
    minHeight: 76,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
    paddingBottom: 12,
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  ruleIconTile: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  ruleCopy: {
    flex: 1,
    gap: 4,
  },
  ruleTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  ruleDescription: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  memberDetailsTopRow: {
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
  },
  memberDetailsAvatar: {
    width: 72,
    height: 72,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  memberDetailsAvatarText: {
    fontSize: 26,
    lineHeight: 30,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  memberDetailsCopy: {
    flex: 1,
    gap: 6,
  },
  memberDetailsBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  factRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  factCopy: {
    flex: 1,
    gap: 4,
  },
  factLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  factValue: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600",
  },
  factDivider: {
    height: 1,
  },
  accessSummaryChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  accessSummaryChip: {
    minHeight: 32,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  accessSummaryChipText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  floatingSheetCard: {
    marginHorizontal: 16,
    marginBottom: 22,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#EBCFC4",
    backgroundColor: "rgba(255,253,249,0.98)",
    padding: 16,
    gap: 10,
  },
  floatingSheetTitle: {
    color: "#243142",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
  },
  floatingSheetDescription: {
    color: "#6A7889",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  floatingSheetActions: {
    gap: 10,
  },
  floatingSheetAction: {
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E9D6CD",
    backgroundColor: "#FFF8F3",
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  floatingSheetActionLead: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  floatingSheetActionLeadAccess: {
    backgroundColor: "#FDEADF",
  },
  floatingSheetActionLeadEdit: {
    backgroundColor: "#EAF1FF",
  },
  floatingSheetActionText: {
    color: "#243142",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  profileAttentionCard: {
    minHeight: 84,
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profileAttentionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  profileAttentionCopy: {
    flex: 1,
    gap: 4,
  },
  profileAttentionTitle: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
  },
  profileAttentionDescription: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
  },
  accessAttentionCard: {
    minHeight: 78,
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  accessAttentionIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  accessAttentionCopy: {
    flex: 1,
    gap: 3,
  },
  accessAttentionTitle: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
  },
  accessAttentionDescription: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
  },
  inlineAccessHeader: {
    gap: 4,
  },
  inlineAccessTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
  },
  inlineAccessHint: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
  },
  accessTargetCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  accessTargetAvatar: {
    width: 40,
    height: 40,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  },
  accessTargetAvatarText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
  },
  accessTargetCopy: {
    flex: 1,
    gap: 1,
  },
  accessTargetName: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
  accessTargetRelationship: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
  },
  accessPickerRow: {
    minHeight: 56,
    paddingHorizontal: 2,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  accessPickerLead: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  accessPickerLeadBlue: {
    backgroundColor: "#EAF1FF",
  },
  accessPickerLeadPurple: {
    backgroundColor: "#F3ECFF",
  },
  accessPickerLeadMint: {
    backgroundColor: "#E8F6EE",
  },
  accessPickerCopy: {
    flex: 1,
    gap: 2,
  },
  accessPickerList: {
    gap: 0,
  },
  accessPickerDivider: {
    height: 1,
    marginLeft: 54,
  },
  accessPickerValue: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  switchLead: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sheetOverlay: {
    backgroundColor: "rgba(30,42,58,0.06)",
  },
  sheetBackdrop: {
    backgroundColor: "rgba(30,42,58,0.18)",
  },
  familySheetCard: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: "rgba(255,253,249,0.98)",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
  },
  sheetDragZone: {
    alignItems: "center",
    gap: 8,
    paddingBottom: 10,
  },
  sheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#E6D4CB",
  },
  sheetTitle: {
    color: "#243142",
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  familySheetOptions: {
    gap: 8,
  },
  familySheetOption: {
    minHeight: 56,
    paddingHorizontal: 2,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  familySheetOptionLead: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  familySheetOptionLeadBlue: {
    backgroundColor: "#EAF1FF",
  },
  familySheetOptionLeadBlueActive: {
    backgroundColor: "#6D8FE8",
  },
  familySheetOptionLeadMint: {
    backgroundColor: "#E8F6EE",
  },
  familySheetOptionLeadPurple: {
    backgroundColor: "#F3ECFF",
  },
  familySheetOptionLeadGold: {
    backgroundColor: "#FFF2E1",
  },
  familySheetOptionText: {
    color: "#243142",
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
  },
  profileEditField: {
    gap: 6,
  },
  profileEditFieldRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profileEditInput: {
    minHeight: 42,
    paddingHorizontal: 0,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  profileEditInputFlex: {
    flex: 1,
  },
  profileEditAccentIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  profileEditAccentIconRose: {
    backgroundColor: "#FDEADF",
  },
  profileEditAccentIconBlue: {
    backgroundColor: "#EAF1FF",
  },
  profileEditAccentIconGold: {
    backgroundColor: "#FFF2E1",
  },
  secondaryActionRow: {
    minHeight: 50,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E9D6CD",
    backgroundColor: "#FFF8F3",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  secondaryActionRowDanger: {
    minHeight: 50,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0C6C2",
    backgroundColor: "#FFF2F0",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  secondaryActionRowText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  accessCard: {
    borderRadius: 28,
    borderWidth: 1,
    padding: 18,
    gap: 18,
  },
  accessSection: {
    gap: 10,
  },
  accessSectionTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
  },
  accessChoicesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  accessChoice: {
    minHeight: 38,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  accessChoiceActive: {
    backgroundColor: "#FCE8E1",
    borderColor: "#F1B9AA",
  },
  accessChoiceInactive: {
    backgroundColor: "#FFF8F2",
    borderColor: "#E9D6CD",
  },
  accessChoiceText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "700",
  },
  switchRow: {
    minHeight: 64,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E9D6CD",
    backgroundColor: "#FFF8F3",
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  switchCopy: {
    flex: 1,
    gap: 3,
  },
  switchHint: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
  },
  primaryFooterAction: {
    minHeight: 54,
    borderRadius: 20,
    backgroundColor: "#F56F68",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    shadowColor: "rgba(245, 111, 104, 0.18)",
    shadowOpacity: 1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
  },
  primaryFooterActionText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
});
