import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const styles = StyleSheet.create({
  screenRoot: {
    ...StyleSheet.absoluteFillObject,
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F1D9CF",
    backgroundColor: "#F3F5FF",
    padding: 18,
    marginBottom: 24,
    shadowColor: "#E8CBBE",
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    minHeight: 140,
    marginBottom: 14,
  },
  heroCopy: {
    flex: 1,
    paddingRight: 10,
    paddingTop: 4,
  },
  heroTitle: {
    color: "#1E2A38",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    letterSpacing: -0.4,
    marginBottom: 5,
    maxWidth: 176,
  },
  heroSubtitle: {
    color: "#66758A",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    maxWidth: 164,
  },
  heroDecorArea: {
    width: 136,
    height: 128,
    position: "relative",
    marginTop: 0,
  },
  heroDecorAsset: {
    position: "absolute",
    width: 208,
    height: 208,
    top: -26,
    right: -24,
    opacity: 0.98,
  },
  metricsPanel: {
    borderRadius: 24,
    backgroundColor: "#FFFDFC",
    borderWidth: 1,
    borderColor: "#D8D3F5",
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  metricsTopRow: {
    flexDirection: "row",
    marginBottom: 12,
  },
  metricColumn: {
    flex: 1,
    position: "relative",
  },
  metricInner: {
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 108,
    paddingHorizontal: 6,
  },
  metricIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  metricDivider: {
    position: "absolute",
    right: 0,
    top: 16,
    bottom: 16,
    width: 1,
    backgroundColor: "#E9E6F8",
  },
  metricValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  metricValue: {
    color: "#6F67C9",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  metricSuffix: {
    color: "#6F67C9",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    marginBottom: 2,
  },
  metricLabel: {
    color: "#66758A",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    textAlign: "center",
  },
  ctaButton: {
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#8F89D8",
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  ctaButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  ctaButtonDisabled: {
    opacity: 0.55,
  },
  ctaIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F1EEFF",
    alignItems: "center",
    justifyContent: "center",
  },
  ctaLabel: {
    color: "#6F67C9",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  historyTitle: {
    color: "#1E2A38",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    letterSpacing: -0.4,
    marginBottom: 14,
  },
  timelineList: {
    gap: 12,
  },
  timelineRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  timelineLeftColumn: {
    width: 86,
  },
  dateCard: {
    minHeight: 96,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    padding: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  dateValue: {
    color: "#1E2A38",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
    fontFamily: journalTypography.body,
    textAlign: "center",
  },
  timelineCenterColumn: {
    width: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineSwipeRow: {
    flex: 1,
    minWidth: 0,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#8F89D8",
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: "#DDD8F4",
    marginTop: 6,
    marginBottom: 14,
  },
  entryCard: {
    flex: 1,
    minHeight: 96,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  entryCardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
    backgroundColor: "#FBFAFF",
  },
  entryCopy: {
    flex: 1,
    minWidth: 0,
  },
  entryValue: {
    color: "#1E2A38",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    marginBottom: 2,
    textAlign: "left",
  },
  entryMeta: {
    color: "#66758A",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
    textAlign: "left",
  },
  confirmOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    zIndex: 60,
  },
  confirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(22, 32, 43, 0.24)",
  },
  confirmCard: {
    width: "100%",
    borderRadius: 28,
    backgroundColor: "#FBFAFF",
    padding: 22,
    borderWidth: 1,
    borderColor: "#D8D3F5",
  },
  confirmTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: "#1E2A3A",
    fontFamily: journalTypography.display,
  },
  confirmDescription: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
    color: "#5F7382",
    fontFamily: journalTypography.body,
  },
  confirmActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  confirmButtonSecondary: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D8D3F5",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPrimary: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: "#8F89D8",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  confirmButtonSecondaryText: {
    color: "#554E94",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  confirmButtonPrimaryText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  sheetOverlay: {
    justifyContent: "flex-end",
  },
  sheetBackdrop: {
    backgroundColor: "rgba(28, 31, 53, 0.2)",
  },
  measurementSheetCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FBFAFF",
    borderWidth: 1,
    borderColor: "#D8D3F5",
    borderBottomWidth: 0,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 24,
  },
  sheetDragZone: {
    alignItems: "center",
    paddingBottom: 14,
  },
  sheetHandle: {
    width: 48,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#DCD8F4",
    marginBottom: 14,
  },
  sheetTitle: {
    color: "#1E2A38",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "800",
    fontFamily: journalTypography.display,
    letterSpacing: -0.4,
    textAlign: "center",
  },
  sheetSubtitle: {
    marginTop: 6,
    color: "#60737E",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    textAlign: "center",
    maxWidth: 280,
  },
  sheetBody: {
    gap: 16,
  },
  sheetField: {
    gap: 8,
  },
  sheetFieldLabel: {
    color: "#4F4A85",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  sheetInputWrap: {
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D8D3F5",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sheetInput: {
    flex: 1,
    color: "#1E2A38",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    paddingVertical: 0,
  },
  sheetInputSuffix: {
    color: "#6A6795",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  sheetErrorText: {
    color: "#C35E55",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  sheetActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  sheetSecondaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D8D3F5",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetSecondaryButtonText: {
    color: "#554E94",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  sheetPrimaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: "#8F89D8",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetPrimaryButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
});
