import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const pillboxHomeScreenStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  background: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(255,248,241,0.54)",
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 58,
    paddingHorizontal: 22,
    paddingBottom: 132,
  },
  header: {
    gap: 8,
  },
  title: {
    color: "#172033",
    fontSize: 36,
    lineHeight: 41,
    fontWeight: "700",
    letterSpacing: -0.8,
    fontFamily: journalTypography.display,
  },
  subtitle: {
    maxWidth: 304,
    color: "#5F6B7A",
    fontSize: 16,
    lineHeight: 23,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  quickActionsRow: {
    flexDirection: "row",
    gap: 14,
    marginTop: 28,
  },
  quickActionButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingHorizontal: 18,
  },
  quickActionPrimary: {
    backgroundColor: "#F56565",
    shadowColor: "rgba(245,101,101,0.24)",
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
  },
  quickActionSecondary: {
    backgroundColor: "rgba(255,255,255,0.82)",
    borderWidth: 1,
    borderColor: "#F0D8CC",
    shadowColor: "#172033",
    shadowOpacity: 0.04,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
  },
  buttonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  quickActionPlus: {
    color: "#FFFFFF",
    fontSize: 24,
    lineHeight: 24,
    fontWeight: "700",
    marginTop: -1,
    fontFamily: journalTypography.display,
  },
  quickActionPrimaryText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  quickActionSecondaryText: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  sectionHeader: {
    marginTop: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: "#172033",
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  sectionCounter: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.74)",
    borderWidth: 1,
    borderColor: "#F4E3D9",
  },
  sectionCounterText: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  carouselWrap: {
    marginTop: 12,
  },
  carouselPage: {
    paddingRight: 10,
  },
  intakeCard: {
    minHeight: 190,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.88)",
    padding: 20,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 10 },
    justifyContent: "space-between",
  },
  intakeCardTop: {
    gap: 6,
  },
  intakeLabel: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  intakeTime: {
    color: "#172033",
    fontSize: 42,
    lineHeight: 48,
    fontWeight: "700",
    letterSpacing: -0.9,
    fontFamily: journalTypography.display,
  },
  intakeDateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  intakeDate: {
    color: "#172033",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "600",
    fontFamily: journalTypography.body,
    flex: 1,
  },
  countdownChip: {
    minHeight: 24,
    borderRadius: 12,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
  },
  countdownChipText: {
    color: "#8A6A5E",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  intakePlanTitle: {
    marginTop: 6,
    color: "#172033",
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  intakeMedicine: {
    marginTop: 4,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  intakeActionButton: {
    marginTop: 14,
    minHeight: 50,
    borderRadius: 22,
    backgroundColor: "#F56565",
    alignItems: "center",
    justifyContent: "center",
  },
  intakeActionText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  dotsRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "#E7DDD7",
  },
  dotActive: {
    backgroundColor: "#F56565",
  },
  statsRow: {
    marginTop: 22,
    flexDirection: "row",
    gap: 10,
  },
  statCard: {
    flex: 1,
    minHeight: 86,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.82)",
    paddingHorizontal: 14,
    paddingVertical: 14,
    shadowColor: "#172033",
    shadowOpacity: 0.05,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
    justifyContent: "space-between",
  },
  statNumber: {
    color: "#F56565",
    fontSize: 28,
    lineHeight: 31,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  statLabel: {
    color: "#5F6B7A",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  plansList: {
    marginTop: 22,
    gap: 10,
  },
  planCard: {
    minHeight: 76,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.86)",
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: "#172033",
    shadowOpacity: 0.05,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  planAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
    flexShrink: 0,
  },
  planAvatarText: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  planMain: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  planTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  planMeta: {
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  planMetaAttention: {
    color: "#F56565",
    fontWeight: "600",
  },
  planRight: {
    alignItems: "flex-end",
    gap: 8,
    flexShrink: 0,
  },
  statusChip: {
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  statusChipActive: {
    backgroundColor: "#E7F7EF",
  },
  statusChipAttention: {
    backgroundColor: "#FFF0D9",
  },
  statusChipMissed: {
    backgroundColor: "#FFE1E1",
  },
  statusChipCompleted: {
    backgroundColor: "#F2F2F2",
  },
  statusChipText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  statusTextActive: {
    color: "#1F8A5B",
  },
  statusTextAttention: {
    color: "#D77A16",
  },
  statusTextMissed: {
    color: "#E85D5D",
  },
  statusTextCompleted: {
    color: "#8A94A6",
  },
  chevron: {
    color: "#A0A8B5",
    fontSize: 18,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  emptyCard: {
    marginTop: 12,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.86)",
    padding: 20,
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
    gap: 10,
  },
  emptyTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  emptyDescription: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
});
