import { journalTypography } from "../../../shared/theme/journalTypography";
import { pillboxStyleTokens as tokens } from "./pillboxStyleTokens";

export const pillboxPlanOnboardingListStyleParts = {
  sectionWrap: {
    marginTop: 26,
  },
  sectionTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    marginBottom: 10,
  },
  participantListCard: {
    borderRadius: 24,
    ...tokens.border.default,
    backgroundColor: tokens.colors.surfacePrimary,
    overflow: "hidden",
    ...tokens.shadow.cardMedium,
  },
  participantRow: {
    minHeight: 62,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F4E3D9",
  },
  participantRowLast: {
    borderBottomWidth: 0,
  },
  participantRowSelected: {
    backgroundColor: "#FFF4EE",
  },
  participantAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
  },
  participantAvatarText: {
    color: "#172033",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.display,
  },
  participantCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  participantTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  participantSubtitle: {
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  chevronText: {
    color: "#A0A8B5",
    fontSize: 17,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.display,
  },
  addMedicineInlineRow: {
    minHeight: 68,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F4E3D9",
    backgroundColor: "rgba(245, 249, 255, 0.58)",
  },
  addMedicinePlusWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7E97D8",
  },
  addMedicinePlusText: {
    color: "#FFFFFF",
    fontSize: 18,
    lineHeight: 18,
    fontWeight: "400",
    fontFamily: journalTypography.display,
  },
  addMedicineLabel: {
    color: "#5C78B8",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  medicineListBlock: {
    marginTop: 12,
    borderRadius: 24,
    ...tokens.border.default,
    backgroundColor: tokens.colors.surfacePrimary,
    overflow: "hidden",
    ...tokens.shadow.cardMedium,
  },
  medicineRow: {
    minHeight: 76,
    borderBottomWidth: 1,
    borderBottomColor: "#F4E3D9",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: tokens.colors.surfacePrimary,
  },
  medicineRowPressable: {
    flex: 1,
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  medicineRowLast: {
    borderBottomWidth: 0,
  },
  medicineEmptyState: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  medicineIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  medicineIconImage: {
    width: 30,
    height: 30,
  },
  medicineCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  medicineTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  medicineSubtitle: {
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  reviewMedicineSection: {
    marginTop: 14,
  },
  reviewMedicineHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  reviewMedicineNameList: {
    marginTop: 12,
    gap: 10,
  },
  reviewMedicineCountChip: {
    minWidth: 34,
    height: 34,
    paddingHorizontal: 10,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E6F0FF",
    borderWidth: 1,
    borderColor: "#C6D7F4",
  },
  reviewMedicineCountChipText: {
    color: "#3E6CA9",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  reviewMedicineSummaryCard: {
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  reviewMedicineSummaryCardBlue: {
    backgroundColor: "#F5F9FF",
    borderColor: "#D5E3F8",
  },
  reviewMedicineSummaryCardPeach: {
    backgroundColor: "#FFF7F2",
    borderColor: "#F1DED2",
  },
  reviewMedicineSummaryCardMint: {
    backgroundColor: "#F4FBF7",
    borderColor: "#D7E8DE",
  },
  reviewMedicineNameCopy: {
    flex: 1,
    minWidth: 0,
  },
  reviewMedicineNameHint: {
    marginTop: 2,
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  summaryCard: {
    borderRadius: 22,
    ...tokens.border.default,
    backgroundColor: tokens.colors.surfacePrimary,
    ...tokens.shadow.cardMedium,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  summaryActionCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  summaryActionCopy: {
    flex: 1,
    minWidth: 0,
  },
  summaryTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  summaryHint: {
    color: "#6F7B89",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  privacyNote: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  privacyText: {
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    flex: 1,
  },
} as const;
