import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const pillboxPlanOnboardingStyles = StyleSheet.create({
  modalRoot: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  background: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(255,248,243,0.56)",
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 58,
    paddingHorizontal: 22,
    paddingBottom: 132,
  },
  topNav: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topNavButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: "#F0D8CC",
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
  },
  topNavButtonPressed: {
    opacity: 0.88,
  },
  topNavButtonText: {
    color: "#172033",
    fontSize: 20,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: journalTypography.display,
  },
  topNavSpacer: {
    width: 42,
    height: 42,
  },
  stepper: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  stepCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFFFF",
  },
  stepCircleActive: {
    borderColor: "#F56565",
    backgroundColor: "#F56565",
  },
  stepCircleCompleted: {
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFFFF",
  },
  stepCircleText: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "600",
    color: "#8A94A6",
    fontFamily: journalTypography.body,
  },
  stepCircleTextActive: {
    color: "#FFFFFF",
  },
  stepCircleTextCompleted: {
    color: "#F56565",
  },
  stepConnector: {
    width: 28,
    height: 1,
    backgroundColor: "#EEDBD1",
    marginHorizontal: 6,
  },
  stepConnectorActive: {
    backgroundColor: "#F56565",
  },
  heroRow: {
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
  },
  headingBlock: {
    flex: 1,
    gap: 8,
    paddingTop: 4,
  },
  title: {
    color: "#172033",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700",
    letterSpacing: -0.45,
    fontFamily: journalTypography.display,
  },
  subtitle: {
    color: "#5F6B7A",
    fontSize: 16,
    lineHeight: 23,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    maxWidth: 236,
  },
  heroIconWrap: {
    width: 92,
    height: 92,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.76)",
    borderWidth: 1,
    borderColor: "#F0D8CC",
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 8 },
  },
  sectionWrap: {
    marginTop: 26,
  },
  sectionTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    marginBottom: 10,
  },
  participantListCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.88)",
    overflow: "hidden",
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 10 },
  },
  participantRow: {
    minHeight: 62,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F4E3D9",
  },
  participantRowLast: {
    borderBottomWidth: 0,
  },
  participantRowSelected: {
    backgroundColor: "#FFF4EE",
  },
  participantAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
  },
  participantAvatarText: {
    color: "#172033",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.display,
  },
  participantCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  participantTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  participantSubtitle: {
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  chevronText: {
    color: "#A0A8B5",
    fontSize: 17,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.display,
  },
  dashedButton: {
    marginTop: 14,
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F56565",
    borderStyle: "dashed",
    backgroundColor: "rgba(255,255,255,0.55)",
    alignItems: "center",
    justifyContent: "center",
  },
  dashedButtonText: {
    color: "#F56565",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  addMedicineCard: {
    minHeight: 92,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0B8AC",
    borderStyle: "dashed",
    backgroundColor: "rgba(255,255,255,0.66)",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  addMedicinePlusWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F56565",
  },
  addMedicinePlusText: {
    color: "#FFFFFF",
    fontSize: 20,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: journalTypography.display,
  },
  addMedicineLabel: {
    color: "#F56565",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  medicineList: {
    marginTop: 12,
    gap: 10,
  },
  medicineRow: {
    minHeight: 76,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.88)",
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 10 },
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  medicineIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  medicineCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  medicineTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  medicineSubtitle: {
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  formCard: {
    marginTop: 22,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.90)",
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 10 },
    padding: 18,
  },
  fieldGroup: {
    marginBottom: 16,
    gap: 8,
  },
  fieldLabel: {
    color: "#172033",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  input: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: "#FFFBF7",
    borderWidth: 1,
    borderColor: "#EEDBD1",
    paddingHorizontal: 16,
    color: "#172033",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  segmentedRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  segmentedItem: {
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
  },
  segmentedItemWide: {
    minWidth: 84,
    minHeight: 46,
    borderRadius: 16,
  },
  segmentedItemActive: {
    borderColor: "#F56565",
    backgroundColor: "#FFF0E8",
  },
  segmentedText: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  segmentedTextActive: {
    color: "#F56565",
    fontWeight: "600",
  },
  daypartsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  daypartCard: {
    width: "47%",
    minHeight: 64,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  daypartCardActive: {
    borderColor: "#F56565",
    backgroundColor: "#FFF0E8",
  },
  daypartTitle: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  daypartTitleActive: {
    color: "#172033",
    fontWeight: "600",
  },
  timeChipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  timeChip: {
    minHeight: 34,
    borderRadius: 17,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
  },
  timeChipText: {
    color: "#F56565",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  addTimeChip: {
    backgroundColor: "rgba(255,255,255,0.82)",
    borderWidth: 1,
    borderColor: "#F0D8CC",
  },
  addTimeChipText: {
    color: "#172033",
  },
  weekdaysRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  weekdayChip: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
  },
  weekdayChipInactive: {
    backgroundColor: "#FFFBF7",
  },
  weekdayText: {
    color: "#F56565",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  weekdayTextInactive: {
    color: "#5F6B7A",
  },
  summaryCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.88)",
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 10 },
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  summaryLabel: {
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  summaryTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  summaryListCard: {
    marginTop: 14,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "rgba(255,255,255,0.88)",
    shadowColor: "#172033",
    shadowOpacity: 0.06,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 10 },
    padding: 16,
    gap: 14,
  },
  privacyNote: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  privacyText: {
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    flex: 1,
  },
  bottomActionDock: {
    position: "absolute",
    left: 22,
    right: 22,
    bottom: 22,
    gap: 10,
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F56565",
    shadowColor: "rgba(245,101,101,0.24)",
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
  },
  primaryButtonDisabled: {
    opacity: 0.45,
    shadowOpacity: 0,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  secondaryTextButton: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 24,
  },
  secondaryTextButtonText: {
    color: "#F56565",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  overlayScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(23,32,51,0.26)",
    justifyContent: "center",
    paddingHorizontal: 22,
  },
  alertCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#F0D8CC",
    backgroundColor: "#FFFBF7",
    padding: 20,
    gap: 10,
  },
  alertTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  alertText: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  alertActions: {
    marginTop: 8,
    flexDirection: "row",
    gap: 10,
  },
  alertAction: {
    flex: 1,
    minHeight: 48,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "#F0D8CC",
  },
  alertActionDanger: {
    backgroundColor: "#F56565",
    borderColor: "#F56565",
  },
  alertActionText: {
    color: "#172033",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  alertActionTextDanger: {
    color: "#FFFFFF",
  },
});
