import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";
import { pillboxStyleTokens as tokens } from "./pillboxStyleTokens";

export const pillboxHomeScreenStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: tokens.colors.canvas,
  },
  background: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: tokens.colors.overlayHome,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 58,
    paddingHorizontal: 22,
    paddingBottom: 132,
  },
  header: {
    gap: 8,
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  headerTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  title: {
    color: "#172033",
    fontSize: 36,
    lineHeight: 41,
    fontWeight: "700",
    letterSpacing: -0.8,
    fontFamily: journalTypography.display,
  },
  subtitle: {
    color: "#5F6B7A",
    fontSize: 16,
    lineHeight: 23,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  headerGhostAction: {
    minHeight: 38,
    borderRadius: 19,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.76)",
    borderWidth: 1,
    borderColor: "#EADBD2",
  },
  headerGhostActionIcon: {
    width: 20,
    height: 20,
  },
  headerGhostActionText: {
    color: "#556274",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  quickActionsRow: {
    gap: 10,
    marginTop: 20,
  },
  createPlanCta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    minHeight: 74,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#F2C2B8",
    backgroundColor: "#FFF7F1",
  },
  createPlanCtaLocked: {
    borderColor: "#F3C8DE",
    backgroundColor: "#FFF4F8",
  },
  createPlanCtaPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  buttonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  createPlanIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F26F6C",
    alignItems: "center",
    justifyContent: "center",
  },
  createPlanLabel: {
    color: "#F26F6C",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "800",
    fontFamily: journalTypography.body,
  },
  createPlanLabelWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  createPlanLockedBadge: {
    minHeight: 24,
    borderRadius: 12,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFE4F0",
    borderWidth: 1,
    borderColor: "#F4BDD7",
  },
  createPlanLockedBadgeText: {
    color: "#C9588D",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  createPlanLockedHint: {
    paddingHorizontal: 6,
    color: "#A35C7E",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  sectionHeader: {
    marginTop: 26,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    color: "#172033",
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  sectionCounterInline: {
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: "#F4E3D9",
  },
  sectionCounterInlineText: {
    color: "#172033",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  carouselWrap: {
    marginTop: 12,
  },
  carouselPage: {
    paddingRight: 10,
  },
  intakeCard: {
    minHeight: 190,
    borderRadius: 28,
    ...tokens.border.default,
    backgroundColor: tokens.colors.surfacePrimary,
    padding: 20,
    ...tokens.shadow.cardLarge,
    gap: 14,
  },
  intakeCardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  intakeLabelPill: {
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF6F0",
    borderWidth: 1,
    borderColor: "#F4E3D9",
  },
  intakeLabel: {
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  intakeHeroRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
  },
  intakeTimeBlock: {
    width: 112,
    paddingTop: 4,
  },
  intakeTime: {
    color: "#172033",
    fontSize: 42,
    lineHeight: 48,
    fontWeight: "700",
    letterSpacing: -0.9,
    fontFamily: journalTypography.display,
  },
  intakeDate: {
    marginTop: 6,
    color: "#6C7888",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  countdownChip: {
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
  },
  countdownChipText: {
    color: "#8A6A5E",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  intakeBody: {
    flex: 1,
    minWidth: 0,
    gap: 6,
    paddingTop: 6,
  },
  intakePlanTitle: {
    color: "#172033",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  intakeMedicine: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  intakeActionButton: {
    marginTop: "auto",
    minHeight: 50,
    borderRadius: 22,
    backgroundColor: "#F56565",
    alignItems: "center",
    justifyContent: "center",
  },
  intakeActionText: {
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  dotsRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "#E7DDD7",
  },
  dotActive: {
    backgroundColor: "#F56565",
  },
  statsRow: {
    marginTop: 18,
  },
  statsCard: {
    borderRadius: 22,
    ...tokens.border.default,
    backgroundColor: "rgba(255,255,255,0.72)",
    ...tokens.shadow.cardSoft,
    paddingVertical: 8,
    paddingHorizontal: 8,
    flexDirection: "row",
  },
  statColumn: {
    flex: 1,
    position: "relative",
  },
  statInner: {
    minHeight: 78,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 6,
  },
  statDivider: {
    position: "absolute",
    top: 14,
    bottom: 14,
    right: 0,
    width: 1,
    backgroundColor: "#F1E1D8",
  },
  statCard: {
    minHeight: 86,
  },
  statNumber: {
    color: "#172033",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  statLabel: {
    color: "#5F6B7A",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    textAlign: "center",
  },
  plansList: {
    marginTop: 22,
    gap: 10,
  },
  swipePlanCardWrap: {
    position: "relative",
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#FFFDF9",
    ...tokens.border.default,
    ...tokens.shadow.cardSoft,
  },
  swipeCardAnimatedLayer: {
    zIndex: 1,
    borderRadius: 24,
    backgroundColor: "#FFFDF9",
  },
  swipeDeleteActionWrap: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: 92,
    overflow: "hidden",
  },
  swipeDeleteAction: {
    flex: 1,
    backgroundColor: "#E45B5B",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  swipeDeleteActionPressed: {
    opacity: 0.92,
  },
  swipeDeleteActionDisabled: {
    opacity: 0.72,
  },
  swipeDeleteActionText: {
    color: "#FFFFFF",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  planCard: {
    minHeight: 84,
    borderRadius: 24,
    backgroundColor: "#FFFDF9",
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  planCardExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  planAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
    flexShrink: 0,
  },
  planAvatarText: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    fontFamily: journalTypography.display,
  },
  planMain: {
    flex: 1,
    minWidth: 0,
    gap: 7,
  },
  planTitleRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  planTitle: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  planMetaPill: {
    alignSelf: "flex-start",
    minHeight: 24,
    borderRadius: 12,
    paddingHorizontal: 10,
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
    borderWidth: 1,
    borderColor: "#F3D7C9",
  },
  planMetaPillText: {
    color: "#C96C53",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  planNextInfo: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  planMetaAttention: {
    color: "#F56565",
    fontWeight: "600",
  },
  planRight: {
    alignItems: "flex-end",
    gap: 8,
    flexShrink: 0,
  },
  statusChip: {
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  statusChipActive: {
    backgroundColor: "#E7F7EF",
  },
  statusChipAttention: {
    backgroundColor: "#FFF0D9",
  },
  statusChipMissed: {
    backgroundColor: "#FFE1E1",
  },
  statusChipCompleted: {
    backgroundColor: "#F2F2F2",
  },
  statusChipText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  statusTextActive: {
    color: "#1F8A5B",
  },
  statusTextAttention: {
    color: "#D77A16",
  },
  statusTextMissed: {
    color: "#E85D5D",
  },
  statusTextCompleted: {
    color: "#8A94A6",
  },
  chevron: {
    color: "#A0A8B5",
    fontSize: 18,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  chevronExpanded: {
    transform: [{ rotate: "180deg" }],
  },
  planExpandedSection: {
    borderTopWidth: 1,
    borderTopColor: "#F1E3DA",
    backgroundColor: "#FFFDF9",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  planExpandedScrollContent: {
    paddingRight: 4,
    gap: 10,
  },
  planExpandedMedicineList: {
    marginTop: 12,
    gap: 10,
  },
  planExpandedMedicineCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F0D8D8",
    backgroundColor: "#FFF6F6",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 7,
  },
  planExpandedMedicineTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
    minWidth: 0,
  },
  planExpandedMedicineCardSpaced: {
    marginBottom: 0,
  },
  planExpandedMedicineTitle: {
    flex: 1,
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  planExpandedMetaItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 7,
    minWidth: 0,
  },
  planExpandedMetaIcon: {
    width: 19,
    height: 19,
    flexShrink: 0,
  },
  planExpandedMedicineSummary: {
    flexShrink: 1,
    color: "#7A6874",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  planExpandedMedicineCourse: {
    flexShrink: 1,
    color: "#3F638D",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  planExpandedLoading: {
    marginTop: 12,
    color: "#6B7585",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  planExpandedActions: {
    marginTop: 14,
    gap: 10,
  },
  planExpandedPrimaryAction: {
    minHeight: 46,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F56565",
  },
  planExpandedPrimaryActionText: {
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  planExpandedSecondaryAction: {
    minHeight: 44,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF8F2",
    borderWidth: 1,
    borderColor: "#EFDCD1",
  },
  planExpandedSecondaryRow: {
    flexDirection: "row",
    gap: 10,
  },
  planExpandedSecondaryActionHalf: {
    flex: 1,
  },
  planExpandedSecondaryActionText: {
    color: "#556274",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  planExpandedActionDisabled: {
    opacity: 0.72,
  },
  emptyCard: {
    marginTop: 12,
    borderRadius: 28,
    ...tokens.border.default,
    backgroundColor: tokens.colors.surfaceSoft,
    padding: 20,
    ...tokens.shadow.cardSoft,
    gap: 10,
  },
  emptyRetryButton: {
    marginTop: 4,
    minHeight: 48,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E8DAD1",
    backgroundColor: "rgba(255,255,255,0.84)",
  },
  emptyRetryButtonText: {
    color: "#172033",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  overlayScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(23,32,51,0.26)",
    justifyContent: "center",
    paddingHorizontal: 22,
    zIndex: 40,
  },
  alertCard: {
    borderRadius: 26,
    ...tokens.border.default,
    backgroundColor: "#FFFBF7",
    padding: 20,
    gap: 10,
  },
  alertTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  alertText: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  alertActions: {
    marginTop: 8,
    flexDirection: "row",
    gap: 10,
  },
  alertAction: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  alertActionSecondary: {
    borderWidth: 1,
    borderColor: "#E7D8CF",
    backgroundColor: "#FFFFFF",
  },
  alertActionSecondaryText: {
    color: "#4D5A6B",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  alertActionPrimary: {
    backgroundColor: "#E45B5B",
  },
  alertActionPrimaryText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  alertActionDisabled: {
    opacity: 0.7,
  },
  emptyTitle: {
    color: "#172033",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  emptyDescription: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
});
