import { journalTypography } from "../../../shared/theme/journalTypography";
import { pillboxStyleTokens as tokens } from "./pillboxStyleTokens";

export const pillboxPlanOnboardingEditorStyleParts = {
  formCard: {
    marginTop: 18,
  },
  editorHeader: {
    marginTop: 10,
    gap: 4,
  },
  editorTitle: {
    color: "#172033",
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "700",
    letterSpacing: -0.3,
    fontFamily: journalTypography.display,
  },
  editorMeta: {
    color: "#6D7988",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  editorSurface: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EEDCD1",
    backgroundColor: "rgba(255,255,255,0.94)",
    ...tokens.shadow.cardMedium,
    padding: 18,
  },
  editorDivider: {
    height: 1,
    backgroundColor: "rgba(227, 212, 204, 0.9)",
    marginVertical: 12,
  },
  fieldGroup: {
    marginBottom: 18,
    gap: 8,
  },
  fieldHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  fieldHeaderIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7E7D7",
  },
  fieldHeaderIconWrapLarge: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  fieldHeaderIconImage: {
    width: 18,
    height: 18,
  },
  fieldHeaderIconImageLarge: {
    width: 22,
    height: 22,
  },
  fieldLabel: {
    color: "#172033",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  fieldHint: {
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    marginTop: 6,
  },
  fieldMeta: {
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    marginTop: 8,
  },
  input: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: tokens.colors.borderInput,
    paddingHorizontal: 16,
    color: tokens.colors.textPrimary,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  modeSegmentedRow: {
    flexDirection: "row",
    gap: 10,
  },
  segmentedItem: {
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E2D9D2",
    backgroundColor: "#FFFFFF",
  },
  mealSegmentedGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  mealSegmentedItem: {
    width: "48%",
    minHeight: 60,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 10,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 16,
  },
  mealSegmentBefore: {
    backgroundColor: "#F7FAFF",
    borderColor: "#CAD6EA",
  },
  mealSegmentBeforeActive: {
    backgroundColor: "#DEE9FF",
    borderColor: "#789BE0",
  },
  mealSegmentWith: {
    backgroundColor: "#FAF7FF",
    borderColor: "#D7CBF1",
  },
  mealSegmentWithActive: {
    backgroundColor: "#E7DAFF",
    borderColor: "#9879E2",
  },
  mealSegmentAfter: {
    backgroundColor: "#F5FCF8",
    borderColor: "#C9E2D4",
  },
  mealSegmentAfterActive: {
    backgroundColor: "#DCEFE5",
    borderColor: "#69BA91",
  },
  mealSegmentNeutral: {
    backgroundColor: "#F7F9FC",
    borderColor: "#D4DCE6",
  },
  mealSegmentNeutralActive: {
    backgroundColor: "#E8EEF5",
    borderColor: "#97A8BC",
  },
  segmentedItemWide: {
    minHeight: 58,
    borderRadius: 16,
  },
  segmentedItemActive: {
    borderColor: "#AE95E5",
    backgroundColor: "#E8DEFF",
  },
  modeSegment: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 10,
  },
  modeSegmentIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    backgroundColor: "#F7E7D7",
  },
  modeSegmentIcon: {
    width: 22,
    height: 22,
  },
  modeSegmentCopy: {
    flex: 1,
    minWidth: 0,
  },
  modeSegmentTitle: {
    color: "#172033",
    fontWeight: "600",
  },
  modeSegmentCaption: {
    color: "#8A94A6",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    marginTop: 2,
  },
  modeSegmentCaptionActive: {
    color: "#7C69B4",
  },
  courseSegmentedItem: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#F1E9FF",
    borderColor: "#CDBAF2",
  },
  courseSegmentedItemActive: {
    backgroundColor: "#E2D6FF",
    borderColor: "#9F84E5",
  },
  courseSegmentContent: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  courseSegmentTitle: {
    color: "#172033",
    fontWeight: "600",
  },
  courseSegmentTitleActive: {
    color: "#172033",
  },
  courseSegmentValue: {
    color: "#7A6C9A",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  courseSegmentValueActive: {
    color: "#6A55A8",
  },
  courseSegmentChevron: {
    color: "#9688B7",
    fontSize: 18,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.display,
    marginLeft: 10,
  },
  courseSegmentChevronActive: {
    color: "#6A55A8",
  },
  segmentedText: {
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  mealSegmentedText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
  },
  mealSegmentBeforeText: {
    color: "#486BA9",
  },
  mealSegmentBeforeTextActive: {
    color: "#294E90",
  },
  mealSegmentWithText: {
    color: "#7760B2",
  },
  mealSegmentWithTextActive: {
    color: "#5D43A1",
  },
  mealSegmentAfterText: {
    color: "#2E8960",
  },
  mealSegmentAfterTextActive: {
    color: "#1F6F4C",
  },
  mealSegmentNeutralText: {
    color: "#697787",
  },
  mealSegmentNeutralTextActive: {
    color: "#4A5868",
  },
  segmentedTextActive: {
    color: "#5E4B9A",
    fontWeight: "500",
  },
  mealSegmentedIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7E7D7",
  },
  mealSegmentedIconWrapNeutral: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7E7D7",
  },
  mealSegmentedIcon: {
    width: 28,
    height: 28,
    opacity: 1,
  },
  mealSegmentedIconNeutral: {
    width: 24,
    height: 24,
  },
  timeChipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  timeChip: {
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: 16,
    paddingRight: 10,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    backgroundColor: "#EEF5FF",
    borderWidth: 1,
    borderColor: "#C9D9F2",
  },
  timeChipText: {
    color: "#3F6CA8",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  addTimeChip: {
    backgroundColor: "rgba(255,255,255,0.82)",
    borderWidth: 1,
    borderColor: "#F0D8CC",
  },
  addTimeChipText: {
    color: "#172033",
  },
  timeChipIconWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7E7D7",
  },
  timeChipIcon: {
    width: 16,
    height: 16,
  },
  timeChipRemove: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.72)",
  },
  timeChipRemoveText: {
    color: "#4E79B7",
    fontSize: 13,
    lineHeight: 13,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  weekdaysRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 4,
    justifyContent: "space-between",
  },
  weekdayChip: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  weekdayChipActive: {
    backgroundColor: "#E6F0FF",
    borderColor: "#93B7EA",
  },
  weekdayChipInactive: {
    backgroundColor: "#FFFFFF",
    borderColor: "#D8E1EC",
  },
  weekdayText: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  weekdayTextActive: {
    color: "#3E6CA9",
  },
  weekdayTextInactive: {
    color: "#6C7888",
  },
} as const;
