import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";
import { pillboxStyleTokens as tokens } from "./pillboxStyleTokens";

export const pillboxPlanDetailsStyles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 70,
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  screenRoot: {
    flex: 1,
  },
  background: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 54,
    paddingHorizontal: 22,
    paddingBottom: 120,
  },
  topNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backLink: {
    minHeight: 32,
    justifyContent: "center",
  },
  backLinkPressed: {
    opacity: 0.86,
  },
  backLinkText: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  topNavSpacer: {
    width: 44,
  },
  headerCard: {
    marginTop: 16,
    borderRadius: 28,
    ...tokens.border.default,
    backgroundColor: tokens.colors.surfaceStrong,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    ...tokens.shadow.cardSoft,
  },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E8",
  },
  avatarText: {
    color: "#172033",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "600",
    fontFamily: journalTypography.display,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: "#172033",
    fontSize: 23,
    lineHeight: 28,
    fontWeight: "600",
    fontFamily: journalTypography.display,
  },
  subtitle: {
    marginTop: 4,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  statusChip: {
    minHeight: 30,
    borderRadius: 15,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E7F7EF",
  },
  statusChipPaused: {
    minHeight: 30,
    borderRadius: 15,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EEF1F5",
  },
  statusChipText: {
    color: "#1F8A5B",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  statusChipTextPaused: {
    color: "#6C7888",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  summaryRow: {
    marginTop: 14,
    flexDirection: "row",
    gap: 10,
  },
  summaryCard: {
    flex: 1,
    minHeight: 82,
    borderRadius: 22,
    ...tokens.border.default,
    backgroundColor: tokens.colors.surfaceSoft,
    padding: 14,
    justifyContent: "space-between",
  },
  summaryCardPeach: {
    backgroundColor: "#FFF8F2",
    borderColor: "#F1DED2",
  },
  summaryCardBlue: {
    backgroundColor: "#F5F9FF",
    borderColor: "#D6E2F5",
  },
  summaryLabel: {
    color: "#8A94A6",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  summaryValue: {
    color: "#172033",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  sectionCard: {
    marginTop: 14,
    borderRadius: 26,
    ...tokens.border.default,
    backgroundColor: tokens.colors.surfacePrimary,
    padding: 16,
    ...tokens.shadow.cardSoft,
  },
  notificationCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  notificationCopy: {
    flex: 1,
    minWidth: 0,
  },
  notificationHint: {
    marginTop: 4,
    color: "#5F6B7A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  notificationChevron: {
    color: "#A0A8B5",
    fontSize: 18,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.display,
  },
  sectionTitle: {
    color: "#172033",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "600",
    fontFamily: journalTypography.display,
  },
  medicineList: {
    marginTop: 10,
  },
  medicineRow: {
    minHeight: 68,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F4E3D9",
    flexDirection: "row",
    gap: 12,
  },
  medicineRowLast: {
    borderBottomWidth: 0,
  },
  medicineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#8EA9E1",
    marginTop: 7,
  },
  medicineCopy: {
    flex: 1,
    minWidth: 0,
  },
  medicineTitle: {
    color: "#172033",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  medicineMeta: {
    marginTop: 3,
    color: "#5F6B7A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  medicineScheduleChip: {
    alignSelf: "flex-start",
    marginTop: 8,
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 10,
    justifyContent: "center",
    backgroundColor: "#EEF5FF",
    borderWidth: 1,
    borderColor: "#CEDCF3",
  },
  medicineSchedule: {
    color: "#4E73B3",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  bottomDock: {
    position: "absolute",
    left: 22,
    right: 22,
    bottom: 22,
  },
  primaryAction: {
    minHeight: 56,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: tokens.colors.cta,
    ...tokens.shadow.cta,
  },
  primaryActionDisabled: {
    opacity: 0.74,
  },
  primaryActionText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    zIndex: 90,
  },
});
