import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";
import { pillboxStyleTokens as tokens } from "./pillboxStyleTokens";

export const pillboxAnalyticsScreenStyles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 14,
    backgroundColor: tokens.colors.canvas,
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: tokens.colors.overlayHome,
  },
  root: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 36,
  },
  topBar: {
    minHeight: 40,
    justifyContent: "center",
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  hero: {
    marginTop: 6,
    gap: 8,
  },
  title: {
    color: "#1E2A38",
    fontSize: 34,
    lineHeight: 38,
    fontWeight: "700",
    letterSpacing: -0.7,
    fontFamily: journalTypography.display,
  },
  subtitle: {
    color: "#66758A",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    maxWidth: 320,
  },
  card: {
    marginTop: 14,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#EFDCD2",
    backgroundColor: "rgba(255,252,248,0.9)",
    padding: 16,
  },
  cardTitle: {
    color: "#1E2A38",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  cardSubtitle: {
    marginTop: 4,
    color: "#66758A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  planPickerButton: {
    marginTop: 12,
    minHeight: 50,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EBDDD4",
    backgroundColor: "#FFFDFC",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  planPickerText: {
    flex: 1,
    color: "#1E2A38",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  planPickerChevron: {
    color: "#9AA5B5",
    fontSize: 16,
    lineHeight: 16,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  periodTabsWrap: {
    marginTop: 14,
    minHeight: 58,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#EFDCD2",
    backgroundColor: "#FFFDFC",
    overflow: "hidden",
    paddingRight: 6,
  },
  periodTabs: {
    paddingLeft: 6,
    paddingRight: 12,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  periodTab: {
    minHeight: 44,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    flexShrink: 0,
  },
  periodTabActive: {
    backgroundColor: "#EAF2FF",
  },
  periodTabText: {
    color: "#58687C",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  periodTabTextActive: {
    color: "#356AA8",
    fontWeight: "700",
  },
  summaryHero: {
    marginTop: 14,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "#E7D9CF",
    backgroundColor: "#FFF8F3",
    padding: 18,
    gap: 14,
    shadowColor: "#D7AFA0",
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  summaryTitle: {
    color: "#1E2A38",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  summaryMeta: {
    color: "#66758A",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  summaryInsight: {
    borderRadius: 20,
    backgroundColor: "#FFFDFC",
    borderWidth: 1,
    borderColor: "#EEE0D7",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  summaryInsightText: {
    color: "#31475C",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  kpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  kpiCard: {
    width: "47.8%",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EEE0D7",
    backgroundColor: "#FFFDFC",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  kpiCardBlue: {
    backgroundColor: "#EEF5FF",
    borderColor: "#D9E8FF",
  },
  kpiCardGreen: {
    backgroundColor: "#EEF9F2",
    borderColor: "#D7EEDD",
  },
  kpiCardAmber: {
    backgroundColor: "#FFF6EA",
    borderColor: "#F5E1BE",
  },
  kpiCardRed: {
    backgroundColor: "#FFF0F0",
    borderColor: "#F2D2D5",
  },
  kpiLabel: {
    color: "#66758A",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  kpiLabelBlue: {
    color: "#4B6F9A",
  },
  kpiLabelGreen: {
    color: "#4A7A5C",
  },
  kpiLabelAmber: {
    color: "#8B6A33",
  },
  kpiLabelRed: {
    color: "#8B5960",
  },
  kpiValue: {
    color: "#1E2A38",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  kpiValueBlue: {
    color: "#2F5E95",
  },
  kpiValueGreen: {
    color: "#2F7A55",
  },
  kpiValueAmber: {
    color: "#B0711B",
  },
  kpiValueRed: {
    color: "#C15A63",
  },
  timelineBars: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 8,
  },
  timelineItem: {
    flex: 1,
    alignItems: "center",
    gap: 8,
  },
  timelineBarWrap: {
    width: "100%",
    height: 104,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  timelineBar: {
    width: "100%",
    maxWidth: 28,
    minHeight: 6,
    borderRadius: 14,
    backgroundColor: "#8FB7F2",
  },
  timelineValue: {
    color: "#1E2A38",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  timelineLabel: {
    color: "#66758A",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    textAlign: "center",
  },
  topMissedList: {
    marginTop: 12,
    gap: 10,
  },
  topMissedRow: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F0E1D6",
    backgroundColor: "#FFFDFC",
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  topMissedCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  topMissedName: {
    color: "#1E2A38",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  topMissedMeta: {
    color: "#6B7585",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  topMissedBadge: {
    minHeight: 30,
    borderRadius: 15,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF0E3",
  },
  topMissedBadgeText: {
    color: "#C9772C",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.body,
  },
  mutedStateCard: {
    marginTop: 14,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#EEDDD4",
    backgroundColor: "rgba(255,252,248,0.88)",
    padding: 18,
    gap: 8,
  },
  mutedStateTitle: {
    color: "#1E2A38",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  mutedStateText: {
    color: "#6B7585",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  pickerSheetCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFFCF8",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 18,
    gap: 12,
  },
  pickerSheetTitle: {
    color: "#1E2A38",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  pickerSheetSubtitle: {
    color: "#6B7585",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  pickerSheetList: {
    gap: 10,
  },
  pickerOption: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EEDFD5",
    backgroundColor: "#FFFDFC",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  pickerOptionActive: {
    backgroundColor: "#EEF5FF",
    borderColor: "#D8E6F8",
  },
  pickerOptionText: {
    flex: 1,
    color: "#1E2A38",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  pickerOptionCheck: {
    color: "#356AA8",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
});
