import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#F8F3EE",
  },
  screenInner: {
    flex: 1,
  },
  screenBackgroundImage: {
    opacity: 0.32,
  },
  screenOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(248,243,238,0.84)",
  },
  topBar: {
    position: "absolute",
    top: Platform.select({ ios: 50, default: 14 }),
    left: 16,
    right: 16,
    height: 34,
    zIndex: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: "rgba(244,91,166,0.18)",
  },
  closeButtonPressed: {
    opacity: 0.82,
  },
  closeButtonText: {
    color: "#F25797",
    fontSize: 22,
    lineHeight: 22,
    fontWeight: "700",
    marginTop: -2,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 12,
    paddingBottom: 12,
    paddingTop: Platform.select({ ios: 60, default: 34 }),
  },
  scrollInner: {
    gap: 10,
  },
  topSection: {
    gap: 10,
  },
  bottomSection: {
    gap: 8,
    marginTop: 2,
  },
  heroCard: {
    alignItems: "flex-start",
    gap: 8,
    paddingTop: 0,
    paddingLeft: 10,
    paddingRight: 56,
  },
  title: {
    color: "#1E1B2E",
    fontSize: 26,
    lineHeight: 31,
    fontWeight: "800",
    textAlign: "left",
    letterSpacing: -0.6,
  },
  subtitle: {
    color: "#6A7889",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "500",
    textAlign: "left",
  },
  comparisonGrid: {
    flexDirection: "row",
    gap: 6,
    alignItems: "stretch",
  },
  comparisonCard: {
    flex: 1,
    minHeight: 228,
    borderRadius: 18,
    padding: 14,
    gap: 8,
  },
  comparisonBody: {
    gap: 8,
    flex: 1,
  },
  comparisonHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  comparisonBadgeText: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "700",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: "hidden",
  },
  comparisonBadgeTextFree: {
    color: "#4677DA",
    backgroundColor: "rgba(70,119,218,0.14)",
  },
  comparisonBadgeTextPlus: {
    color: "#F25797",
    backgroundColor: "rgba(242,87,151,0.14)",
  },
  comparisonItems: {
    gap: 8,
  },
  comparisonItemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  comparisonIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
  },
  comparisonIconWrapFree: {
    backgroundColor: "rgba(70,119,218,0.12)",
  },
  comparisonIconWrapPlus: {
    backgroundColor: "rgba(242,87,151,0.12)",
  },
  freeCard: {
    borderWidth: 1,
    borderColor: "rgba(86,134,255,0.16)",
    backgroundColor: "rgba(234,242,255,0.86)",
  },
  plusCard: {
    borderWidth: 1,
    borderColor: "rgba(244,91,166,0.16)",
    backgroundColor: "rgba(255,215,232,0.84)",
  },
  comparisonTitle: {
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "800",
  },
  freeTitle: {
    color: "#4677DA",
  },
  plusTitle: {
    color: "#F25797",
  },
  comparisonItem: {
    flex: 1,
    color: "#314155",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  freeForever: {
    marginTop: 8,
    color: "#3F6FD1",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
  },
  plusFooter: {
    marginTop: 8,
    color: "#D85A97",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
  },
  loadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  loadingText: {
    color: "#6A7889",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  planGrid: {
    flexDirection: "row",
    gap: 6,
    marginTop: 0,
  },
  planCard: {
    flex: 1,
    minHeight: 106,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(229,214,236,0.9)",
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  planCardSelected: {
    borderWidth: 1,
    borderColor: "rgba(244,91,166,0.28)",
    backgroundColor: "rgba(244,91,166,0.08)",
  },
  planBadge: {
    position: "absolute",
    top: -1,
    right: -1,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 16,
    backgroundColor: "#F06AA8",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  planBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "800",
  },
  planTitle: {
    width: "100%",
    color: "#243142",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  planTitleWrap: {
    width: "100%",
    minHeight: 22,
    paddingTop: 8,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  planPrice: {
    width: "100%",
    color: "#243142",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    textAlign: "center",
  },
  planDescription: {
    width: "100%",
    color: "#7A8596",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "600",
    textAlign: "center",
    minHeight: 22,
  },
  planCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#E8D8F5",
    alignItems: "center",
    justifyContent: "center",
  },
  planCheckSelected: {
    borderColor: "#F06AA8",
    backgroundColor: "#F45BA6",
  },
  planCheckText: {
    color: "transparent",
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "800",
  },
  planCheckTextSelected: {
    color: "#FFFFFF",
  },
  primaryAction: {
    marginTop: 6,
    minHeight: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(244,91,166,0.16)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F45BA6",
  },
  primaryActionPressed: {
    opacity: 0.92,
  },
  disabled: {
    opacity: 0.7,
  },
  primaryActionText: {
    color: "#FFFFFF",
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "800",
  },
  secondaryAction: {
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(86,134,255,0.16)",
    backgroundColor: "rgba(255,255,255,0.78)",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryActionText: {
    color: "#1E1B2E",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "700",
  },
  legalNote: {
    marginTop: 2,
    color: "#64748B",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "center",
  },
  inlineMessage: {
    marginTop: 4,
    color: "#C73F70",
    fontSize: 13,
    lineHeight: 17,
    textAlign: "center",
  },
  footerLinks: {
    marginTop: 2,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    paddingBottom: 0,
  },
  footerLink: {
    color: "#F25797",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "700",
  },
  footerLinkDisabled: {
    color: "rgba(242,87,151,0.42)",
  },
  footerSeparator: {
    color: "rgba(242,87,151,0.4)",
    fontSize: 13,
  },
});
