import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#F8F3EE",
  },
  screenInner: {
    flex: 1,
  },
  screenBackgroundImage: {
    opacity: 0.32,
  },
  screenOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(248,243,238,0.84)",
  },
  heroTouchZone: {
    position: "absolute",
    top: Platform.select({ ios: 66, default: 24 }),
    left: 0,
    right: 0,
    height: 44,
    zIndex: 20,
    justifyContent: "center",
    alignItems: "flex-end",
    paddingHorizontal: 18,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: "rgba(244,91,166,0.18)",
  },
  closeButtonPressed: {
    opacity: 0.82,
  },
  closeButtonText: {
    color: "#F25797",
    fontSize: 22,
    lineHeight: 22,
    fontWeight: "700",
    marginTop: -2,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingBottom: 22,
    paddingTop: Platform.select({ ios: 126, default: 74 }),
    gap: 10,
  },
  heroCard: {
    alignItems: "center",
    gap: 6,
    paddingTop: 0,
  },
  title: {
    color: "#1E1B2E",
    fontSize: 24,
    lineHeight: 27,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: -0.7,
  },
  subtitle: {
    color: "#6A7889",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    textAlign: "center",
  },
  comparisonGrid: {
    flexDirection: "row",
    gap: 8,
    alignItems: "stretch",
  },
  comparisonCard: {
    flex: 1,
    minHeight: 220,
    borderRadius: 20,
    padding: 12,
    gap: 5,
  },
  freeCard: {
    borderWidth: 1,
    borderColor: "rgba(86,134,255,0.16)",
    backgroundColor: "rgba(234,242,255,0.86)",
  },
  plusCard: {
    borderWidth: 1,
    borderColor: "rgba(244,91,166,0.16)",
    backgroundColor: "rgba(255,215,232,0.84)",
  },
  comparisonTitle: {
    fontSize: 18,
    lineHeight: 21,
    fontWeight: "800",
  },
  freeTitle: {
    color: "#4677DA",
  },
  plusTitle: {
    color: "#F25797",
  },
  plusHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  plusMiniPill: {
    borderRadius: 999,
    backgroundColor: "#F25797",
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  plusMiniPillText: {
    color: "#FFFFFF",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "800",
  },
  comparisonItem: {
    color: "#4B5563",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  plusLeadItem: {
    color: "#F25797",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  freeForever: {
    marginTop: 2,
    color: "#3F6FD1",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
  },
  planLabel: {
    textAlign: "center",
    color: "#C25A95",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  loadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  loadingText: {
    color: "#6A7889",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  planGrid: {
    flexDirection: "row",
    gap: 8,
    marginTop: 0,
  },
  planCard: {
    flex: 1,
    minHeight: 122,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(229,214,236,0.9)",
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  planCardSelected: {
    borderWidth: 2,
    borderColor: "rgba(244,91,166,0.55)",
    backgroundColor: "rgba(244,91,166,0.06)",
  },
  planBadge: {
    position: "absolute",
    top: -1,
    right: -1,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 16,
    backgroundColor: "#F06AA8",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  planBadgeText: {
    color: "#FFFFFF",
    fontSize: 9,
    lineHeight: 11,
    fontWeight: "800",
  },
  planTitle: {
    width: "100%",
    color: "#243142",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  planTitleWrap: {
    width: "100%",
    minHeight: 24,
    paddingTop: 12,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  planPrice: {
    width: "100%",
    color: "#243142",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    textAlign: "center",
  },
  planDescription: {
    width: "100%",
    color: "#7A8596",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "500",
    textAlign: "center",
    minHeight: 26,
  },
  planCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#E8D8F5",
    alignItems: "center",
    justifyContent: "center",
  },
  planCheckSelected: {
    borderColor: "#F06AA8",
    backgroundColor: "#F45BA6",
  },
  planCheckText: {
    color: "transparent",
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "800",
  },
  planCheckTextSelected: {
    color: "#FFFFFF",
  },
  primaryAction: {
    minHeight: 50,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F45BA6",
  },
  primaryActionPressed: {
    opacity: 0.92,
  },
  disabled: {
    opacity: 0.7,
  },
  primaryActionText: {
    color: "#FFFFFF",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "800",
  },
  secondaryAction: {
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(233,213,255,0.9)",
    backgroundColor: "rgba(255,255,255,0.78)",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryActionText: {
    color: "#1E1B2E",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "700",
  },
  legalNote: {
    marginTop: 4,
    color: "#64748B",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "center",
  },
  inlineMessage: {
    marginTop: 6,
    color: "#C73F70",
    fontSize: 13,
    lineHeight: 17,
    textAlign: "center",
  },
  footerLinks: {
    marginTop: 4,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    paddingBottom: 2,
  },
  footerLink: {
    color: "#F25797",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  footerSeparator: {
    color: "rgba(242,87,151,0.4)",
    fontSize: 13,
  },
});
