import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 16,
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  root: {
    flex: 1,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.58)",
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 36,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkPressed: {
    opacity: 0.88,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  headerBlock: {
    marginTop: 6,
    marginBottom: 20,
  },
  title: {
    color: "#1E2A38",
    fontSize: 27,
    lineHeight: 31,
    fontWeight: "600",
    fontFamily: journalTypography.display,
    letterSpacing: -0.5,
    marginBottom: 6,
    maxWidth: 270,
  },
  subtitle: {
    color: "#66758A",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    maxWidth: 326,
  },
  summaryCard: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#432215",
    shadowOpacity: 0.045,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 5 },
  },
  summaryTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 14,
  },
  summaryTitle: {
    flex: 1,
    color: "#1F2A44",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "600",
    fontFamily: journalTypography.display,
    letterSpacing: -0.2,
  },
  periodChip: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: "center",
    backgroundColor: "#FFFDFC",
  },
  periodChipOpen: {
    backgroundColor: "#FFFDFC",
  },
  periodChipPressed: {
    opacity: 0.9,
  },
  periodChipText: {
    color: "#1F2A44",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  periodDropdown: {
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    overflow: "hidden",
    shadowColor: "#432215",
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
  },
  periodDropdownItem: {
    position: "relative",
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  periodDropdownItemActive: {
    backgroundColor: "#FFFDFC",
  },
  periodDropdownItemPressed: {
    opacity: 0.92,
  },
  periodDropdownCopy: {
    flex: 1,
    paddingRight: 12,
  },
  periodDropdownLabel: {
    color: "#1F2A44",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
    marginBottom: 2,
  },
  periodDropdownLabelActive: {
    color: "#FF7E6B",
  },
  periodDropdownHelper: {
    color: "#6F7C91",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  periodDropdownDivider: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 0,
    height: 1,
  },
  summaryContentRow: {
    flexDirection: "row",
    gap: 12,
    alignItems: "stretch",
  },
  summaryContentRowCompact: {
    marginTop: -2,
  },
  insightList: {
    flex: 1,
    gap: 10,
  },
  insightRow: {
    flexDirection: "row",
    gap: 9,
    alignItems: "flex-start",
  },
  insightIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
    flexShrink: 0,
  },
  insightCopy: {
    flex: 1,
    gap: 2,
  },
  insightTitle: {
    color: "#1F2A44",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  insightSubtitle: {
    color: "#6F7C91",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  avatarHeroWrap: {
    width: 114,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  avatarBlob: {
    width: 116,
    height: 138,
    borderTopLeftRadius: 56,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 62,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    transform: [{ rotate: "-11deg" }, { scaleX: 1.04 }, { scaleY: 0.97 }],
  },
  avatarImage: {
    width: 98,
    height: 120,
    transform: [{ rotate: "11deg" }, { scale: 0.98 }],
  },
  decorIcon: {
    position: "absolute",
    opacity: 0.82,
  },
  decorHeartTop: {
    top: -4,
    right: 2,
    transform: [{ rotate: "8deg" }],
  },
  decorLeafTopLeft: {
    top: 10,
    left: -10,
    transform: [{ rotate: "-24deg" }],
  },
  decorHeartUpperLeft: {
    top: -8,
    left: 28,
    transform: [{ rotate: "-12deg" }],
  },
  decorHeartLeft: {
    top: 58,
    left: -12,
    transform: [{ rotate: "-16deg" }],
  },
  decorLeafMidLeft: {
    top: 96,
    left: -12,
    transform: [{ rotate: "18deg" }],
  },
  decorLeafRight: {
    top: 54,
    right: -12,
    transform: [{ rotate: "20deg" }],
  },
  decorHeartBottom: {
    bottom: 10,
    left: 8,
    transform: [{ rotate: "10deg" }],
  },
  decorLeafLowerRight: {
    bottom: -2,
    right: 2,
    transform: [{ rotate: "-30deg" }],
  },
  decorHeartLowerRight: {
    bottom: 18,
    right: -12,
    transform: [{ rotate: "16deg" }],
  },
  decorLeafBottomLeft: {
    bottom: -4,
    left: -4,
    transform: [{ rotate: "-20deg" }],
  },
  tabsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  tabButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 22,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFDFC",
  },
  tabPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  tabText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  calendarCard: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
    marginBottom: 14,
    shadowColor: "#432215",
    shadowOpacity: 0.045,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 5 },
  },
  calendarHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  calendarMonthTitle: {
    flex: 1,
    color: "#1F2A44",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "600",
    fontFamily: journalTypography.display,
  },
  calendarNavButtons: {
    flexDirection: "row",
    gap: 6,
  },
  calendarNavButton: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFDFC",
  },
  calendarNavButtonDisabled: {
    opacity: 0.45,
  },
  calendarWeekdaysRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  calendarWeekdayLabel: {
    width: 44,
    textAlign: "center",
    color: "#6F7C91",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  calendarDayCell: {
    width: 47,
    minHeight: 58,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#F7E9E3",
    backgroundColor: "#FFFDFC",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 8,
    paddingBottom: 8,
  },
  calendarDayCellMuted: {
    borderColor: "transparent",
    backgroundColor: "transparent",
  },
  calendarDayCellSelected: {
    borderColor: "#F2DDD6",
    backgroundColor: "#FCE7E2",
  },
  calendarDayNumber: {
    color: "#15345B",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.display,
  },
  calendarDayNumberMuted: {
    color: "#9AA5B5",
  },
  calendarDayNumberSelected: {
    color: "#FF7E6B",
  },
  calendarDayDots: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 10,
  },
  calendarDayDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  calendarSummaryCard: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
    marginBottom: 8,
    shadowColor: "#432215",
    shadowOpacity: 0.045,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 5 },
  },
  calendarSummaryHeader: {
    marginBottom: 12,
  },
  calendarSummaryTitle: {
    color: "#1F2A44",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "600",
    fontFamily: journalTypography.display,
    marginBottom: 4,
  },
  calendarSummaryHint: {
    color: "#6F7C91",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  calendarSummaryStats: {
    flexDirection: "row",
    gap: 8,
  },
  calendarStatCard: {
    flex: 1,
    minHeight: 82,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F2DDD6",
    backgroundColor: "#FFFDFC",
    padding: 12,
  },
  calendarStatIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  calendarStatLabel: {
    color: "#6F7C91",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "600",
    fontFamily: journalTypography.body,
    marginBottom: 3,
  },
  calendarStatValue: {
    color: "#1F2A44",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  calendarSummaryList: {
    gap: 7,
  },
  calendarSummaryEmpty: {
    color: "#6F7C91",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    paddingVertical: 8,
  },
  graphicsSectionTitle: {
    color: "#1F2A44",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "600",
    fontFamily: journalTypography.display,
    marginBottom: 12,
  },
  graphicsCard: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
    marginBottom: 14,
    shadowColor: "#432215",
    shadowOpacity: 0.045,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 5 },
  },
  graphicsCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 12,
  },
  graphicsCardHeaderCopy: {
    flex: 1,
  },
  graphicsCardSubtitle: {
    color: "#6F7C91",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  graphicsCardMeta: {
    color: "#1F2A44",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  graphicsPeakLabel: {
    color: "#6F7C91",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    marginTop: -2,
    marginBottom: 10,
  },
  barChartList: {
    gap: 14,
    paddingTop: 4,
  },
  barChartRow: {
    gap: 7,
  },
  barChartRowHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  barChartCategoryLabel: {
    flex: 1,
    color: "#1F2A44",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  barChartCategoryLabelActive: {
    color: "#C9701B",
  },
  barChartRowValue: {
    color: "#62728C",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "600",
    fontFamily: journalTypography.body,
    textAlign: "right",
    paddingLeft: 8,
  },
  barChartRowValueActive: {
    color: "#C9701B",
  },
  barChartRowTrack: {
    height: 13,
    borderRadius: 999,
    backgroundColor: "#F8EEE8",
    overflow: "hidden",
  },
  barChartRowFill: {
    height: "100%",
    borderRadius: 999,
  },
  graphicsCategoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
  },
  graphicsCategoryCard: {
    width: "48%",
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
  },
  graphicsCategoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  graphicsCategoryIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  graphicsCategoryLabel: {
    flex: 1,
    color: "#1F2A44",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  graphicsCategoryValue: {
    color: "#1F2A44",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    fontFamily: journalTypography.display,
    marginBottom: 4,
  },
  graphicsCategoryMeta: {
    color: "#6F7C91",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    minHeight: 30,
    marginBottom: 10,
  },
  graphicsCategoryTrendRow: {
    height: 28,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
    marginBottom: 10,
  },
  graphicsCategoryTrendBar: {
    flex: 1,
    borderRadius: 999,
    minHeight: 6,
  },
  graphicsCategoryFootnote: {
    color: "#7A8698",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  filtersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  filterChip: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 11,
    borderRadius: 17,
    borderWidth: 1,
    backgroundColor: "#FFFDFC",
  },
  filterChipPressed: {
    opacity: 0.9,
  },
  filterDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  filterText: {
    color: "#1F2A44",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  eventsTitle: {
    color: "#1F2A44",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "600",
    fontFamily: journalTypography.display,
    letterSpacing: -0.2,
    marginBottom: 7,
  },
  eventSection: {
    marginBottom: 14,
  },
  eventDate: {
    color: "#FF7E6B",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
    marginBottom: 7,
  },
  eventList: {
    gap: 7,
  },
  eventRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 9,
  },
  eventTime: {
    width: 48,
    paddingTop: 13,
    color: "#6F7C91",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  eventTimelineColumn: {
    width: 12,
    alignItems: "center",
    paddingTop: 17,
  },
  eventDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F2DDD6",
  },
  eventLine: {
    flex: 1,
    width: 1,
    backgroundColor: "#F2DDD6",
    marginTop: 6,
    marginBottom: -2,
  },
  eventCard: {
    flex: 1,
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F2DDD6",
    paddingHorizontal: 13,
    paddingVertical: 11,
    backgroundColor: "#FFFDFC",
  },
  eventCardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  eventIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  eventCopy: {
    flex: 1,
    gap: 2,
  },
  eventType: {
    color: "#1F2A44",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily: journalTypography.body,
  },
  eventDetail: {
    color: "#6F7C91",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
});
