import { StyleSheet } from "react-native";
import { journalTypography } from "../../../shared/theme/journalTypography";

export const styles = StyleSheet.create({
  heroCard: {
    borderRadius: 28,
    borderWidth: 2,
    borderColor: "#F1D9CF",
    backgroundColor: "#F6F2FF",
    padding: 16,
    marginBottom: 24,
    shadowColor: "#E8CBBE",
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    minHeight: 134,
    marginBottom: 13,
  },
  heroCopy: {
    flex: 1,
    paddingRight: 12,
    zIndex: 2,
    paddingTop: 4,
  },
  heroTitle: {
    color: "#1E2A38",
    fontSize: 21,
    lineHeight: 25,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    letterSpacing: -0.4,
    marginBottom: 4,
    maxWidth: 180,
  },
  heroSubtitle: {
    color: "#66758A",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    maxWidth: 164,
  },
  heroDecorArea: {
    width: 130,
    height: 122,
    position: "relative",
  },
  heroDecorAsset: {
    position: "absolute",
    width: 186,
    height: 186,
    top: -24,
    right: -8,
    opacity: 0.98,
  },
  metricsPanel: {
    borderRadius: 24,
    backgroundColor: "#FFFDFC",
    borderWidth: 1.5,
    borderColor: "#F1D9CF",
    paddingVertical: 12,
    paddingHorizontal: 8,
    flexDirection: "row",
  },
  metricColumn: {
    flex: 1,
    position: "relative",
  },
  metricInner: {
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 102,
    paddingHorizontal: 4,
  },
  metricIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  metricDivider: {
    position: "absolute",
    right: 0,
    top: 16,
    bottom: 16,
    width: 1.5,
    backgroundColor: "#F3E6DE",
  },
  metricValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  metricValue: {
    color: "#7E69C7",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "700",
    fontFamily: journalTypography.display,
  },
  metricSuffix: {
    color: "#7E69C7",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    marginBottom: 2,
  },
  metricLabel: {
    color: "#66758A",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "500",
    fontFamily: journalTypography.body,
    textAlign: "center",
  },
  historyTitle: {
    color: "#1E2A38",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    letterSpacing: -0.4,
    marginBottom: 14,
  },
  timelineList: {
    gap: 12,
  },
  timelineRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  timelineLeftColumn: {
    width: 86,
  },
  timeCard: {
    minHeight: 96,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    padding: 12,
    justifyContent: "center",
  },
  timeValue: {
    color: "#1E2A38",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    marginBottom: 2,
  },
  dayValue: {
    color: "#66758A",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
  timelineCenterColumn: {
    width: 18,
    alignItems: "center",
    paddingTop: 14,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#8F89D8",
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: "#DDD8F4",
    marginTop: 6,
  },
  entryCard: {
    flex: 1,
    minHeight: 96,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    padding: 12,
    marginLeft: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  entryBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  entryBadgeImage: {
    width: 26,
    height: 26,
  },
  entryCopy: {
    flex: 1,
    minWidth: 0,
  },
  entryTitle: {
    color: "#1E2A38",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: journalTypography.display,
    marginBottom: 2,
  },
  entryMeta: {
    color: "#66758A",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "500",
    fontFamily: journalTypography.body,
  },
});
