import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
    backgroundColor: "#FBF3EC",
  },
  overlayLayerHidden: { opacity: 0 },
  overlayLayerVisible: { opacity: 1 },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 5,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#FBF3EC",
  },
  backgroundImage: { width: "100%", height: "100%" },
  backgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.72)",
  },
  screen: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  root: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  scroll: { flex: 1 },
  scrollContent: { paddingTop: 54, paddingHorizontal: 16, paddingBottom: 150 },
  title: { fontSize: 44, lineHeight: 48, fontWeight: "800", letterSpacing: -1, color: "#1E2A3A" },
  subtitle: { marginTop: 6, fontSize: 17, lineHeight: 24, fontWeight: "500", color: "#6B7585", marginBottom: 24 },
  emptyCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EED8CE",
    backgroundColor: "#FFFCF8",
    padding: 22,
  },
  emptyTitle: { fontSize: 24, lineHeight: 30, fontWeight: "800", color: "#1E2A3A" },
  emptySubtitle: { marginTop: 8, fontSize: 15, lineHeight: 22, fontWeight: "500", color: "#6B7585" },
  emptyButton: { marginTop: 18, minHeight: 52, borderRadius: 999, backgroundColor: "#F56F68", alignItems: "center", justifyContent: "center" },
  emptyButtonText: { fontSize: 16, lineHeight: 22, fontWeight: "800", color: "#FFFFFF" },
  card: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EED8CE",
    backgroundColor: "#FFFCF8",
    padding: 20,
    marginBottom: 18,
  },
  cardHeader: { gap: 10 },
  cardMainRow: { flexDirection: "row", gap: 14, alignItems: "flex-start" },
  avatarWrap: {
    width: 82,
    height: 82,
    borderRadius: 22,
    backgroundColor: "#F8EDE6",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatar: { width: 72, height: 72 },
  cardHeaderCopy: { flex: 1, minWidth: 0 },
  headerTopRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  nameRow: { flex: 1, flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8, minWidth: 0 },
  statusDot: { width: 10, height: 10, borderRadius: 999, backgroundColor: "#18A7E0" },
  childName: { flexShrink: 1, fontSize: 24, lineHeight: 30, fontWeight: "800", color: "#1E2A3A" },
  childStats: { marginTop: 6, fontSize: 16, lineHeight: 22, fontWeight: "500", color: "#6B7585" },
  observationSince: { marginTop: 4, fontSize: 15, lineHeight: 21, fontWeight: "500", color: "#6B7585" },
  finishButton: {
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#F56F68",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    flexShrink: 0,
  },
  finishButtonText: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: "#1E2A3A" },
  reminderLeadCard: {
    marginTop: 12,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#DCE6F2",
    backgroundColor: "#F8FBFF",
    padding: 14,
    gap: 12,
  },
  reminderLeadHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  reminderLeadIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#EAF1FF",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  reminderLeadIconImage: {
    width: 22,
    height: 22,
    transform: [{ scale: 1.28 }],
  },
  reminderLeadCopy: {
    flex: 1,
    minWidth: 0,
  },
  reminderLeadTitle: {
    color: "#1E2A3A",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "700",
  },
  reminderLeadStatus: {
    marginTop: 3,
    color: "#667386",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  reminderLeadActions: {
    flexDirection: "row",
    gap: 10,
  },
  reminderLeadPrimaryButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#C9D9F2",
    backgroundColor: "#EEF5FF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  reminderLeadPrimaryButtonText: {
    color: "#4C6FA8",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  quickActionsGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 10, marginTop: 14 },
  quickActionButton: {
    width: "48%",
    minHeight: 92,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  quickActionIconWrap: { width: 38, height: 38, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  quickActionIconImage: { width: 38, height: 38, transform: [{ scale: 1.18 }] },
  temperatureQuickActionIconImage: { transform: [{ scale: 1.62 }] },
  quickActionLabel: { fontSize: 12, lineHeight: 16, fontWeight: "800", color: "#1E2A3A", textAlign: "center" },
  feedButton: {
    marginTop: 14,
    minHeight: 54,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EFDCD2",
    backgroundColor: "#FFFBF8",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  feedLeft: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1, paddingRight: 10 },
  feedIconWrap: { width: 34, height: 34, borderRadius: 999, backgroundColor: "#FFE3DD", alignItems: "center", justifyContent: "center" },
  feedLabel: { flexShrink: 1, fontSize: 16, lineHeight: 21, fontWeight: "700", color: "#1E2A3A" },
  entriesWrap: { marginTop: 12, gap: 14 },
  entrySection: { gap: 10 },
  entrySectionTitle: { color: "#1F2A44", fontSize: 15, lineHeight: 20, fontWeight: "800" },
  entrySectionRows: { gap: 10 },
  entryRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 0,
  },
  entryTimeColumn: {
    width: 78,
    alignItems: "flex-start",
  },
  entryTimeCard: {
    width: "100%",
    minHeight: 84,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  entryTime: {
    color: "#1E2A38",
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "800",
    textAlign: "center",
  },
  entryDate: {
    marginTop: 3,
    color: "#66758A",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "600",
    textAlign: "center",
  },
  entryTimelineColumn: {
    width: 18,
    minHeight: 84,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 37,
  },
  entryDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: "#F2DDD6",
  },
  entryCard: {
    flex: 1,
    minHeight: 84,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F6E7E0",
    backgroundColor: "#FFFDFC",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  entryIconWrap: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  entryIconImage: { width: 26, height: 26, transform: [{ scale: 1.4 }] },
  temperatureEntryIconImage: { transform: [{ scale: 1.88 }] },
  entryCopy: { flex: 1, gap: 3 },
  entryType: {
    color: "#1F2A44",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  entryDetail: {
    color: "#5F7088",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  confirmOverlay: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center", paddingHorizontal: 24, zIndex: 60 },
  confirmBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(22, 32, 43, 0.24)" },
  confirmCard: { width: "100%", borderRadius: 28, backgroundColor: "#FFFCF8", padding: 22, borderWidth: 1, borderColor: "#EED8CE" },
  confirmTitle: { fontSize: 22, lineHeight: 28, fontWeight: "800", color: "#1E2A3A" },
  confirmDescription: { marginTop: 8, fontSize: 15, lineHeight: 22, fontWeight: "500", color: "#6B7585" },
  confirmActions: { flexDirection: "row", gap: 10, marginTop: 18 },
  secondaryButton: { flex: 1, minHeight: 54, borderRadius: 999, borderWidth: 1, borderColor: "#F56F68", alignItems: "center", justifyContent: "center" },
  secondaryButtonText: { fontSize: 17, lineHeight: 22, fontWeight: "800", color: "#F56F68" },
  primaryButton: { flex: 1, minHeight: 54, borderRadius: 999, backgroundColor: "#F56F68", alignItems: "center", justifyContent: "center" },
  primaryButtonText: { fontSize: 17, lineHeight: 22, fontWeight: "800", color: "#FFFFFF" },
});
