import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
    backgroundColor: "#FBF3EC",
  },
  overlayLayerHidden: { opacity: 0 },
  overlayLayerVisible: { opacity: 1 },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#FBF3EC",
  },
  backgroundImage: { width: "100%", height: "100%" },
  backgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.72)",
  },
  screen: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  root: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  scroll: { flex: 1 },
  scrollContent: { paddingTop: 54, paddingHorizontal: 16, paddingBottom: 150 },
  bottomBarLayer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 8,
  },
  title: { fontSize: 44, lineHeight: 48, fontWeight: "800", letterSpacing: -1, color: "#1E2A3A" },
  subtitle: { marginTop: 6, fontSize: 17, lineHeight: 24, fontWeight: "500", color: "#6B7585", marginBottom: 24 },
  emptyCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EED8CE",
    backgroundColor: "#FFFCF8",
    padding: 22,
  },
  emptyTitle: { fontSize: 24, lineHeight: 30, fontWeight: "800", color: "#1E2A3A" },
  emptySubtitle: { marginTop: 8, fontSize: 15, lineHeight: 22, fontWeight: "500", color: "#6B7585" },
  emptyButton: { marginTop: 18, minHeight: 52, borderRadius: 999, backgroundColor: "#F56F68", alignItems: "center", justifyContent: "center" },
  emptyButtonText: { fontSize: 16, lineHeight: 22, fontWeight: "800", color: "#FFFFFF" },
  card: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EED8CE",
    backgroundColor: "#FFFCF8",
    padding: 20,
    marginBottom: 18,
  },
  cardHeader: { gap: 10 },
  cardMainRow: { flexDirection: "row", gap: 14, alignItems: "flex-start" },
  avatarWrap: {
    width: 82,
    height: 82,
    borderRadius: 22,
    backgroundColor: "#F8EDE6",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatar: { width: 72, height: 72 },
  cardHeaderCopy: { flex: 1, minWidth: 0 },
  headerTopRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  nameRow: { flex: 1, flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8, minWidth: 0 },
  statusDot: { width: 10, height: 10, borderRadius: 999, backgroundColor: "#18A7E0" },
  childName: { flexShrink: 1, fontSize: 24, lineHeight: 30, fontWeight: "800", color: "#1E2A3A" },
  childStats: { marginTop: 6, fontSize: 16, lineHeight: 22, fontWeight: "500", color: "#6B7585" },
  observationSince: { marginTop: 4, fontSize: 15, lineHeight: 21, fontWeight: "500", color: "#6B7585" },
  finishButton: {
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#F56F68",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    flexShrink: 0,
  },
  finishButtonText: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: "#1E2A3A" },
  chipsRow: { flexDirection: "row", gap: 6, marginTop: 4, alignItems: "stretch" },
  chip: {
    flex: 1,
    minHeight: 34,
    borderRadius: 12,
    borderWidth: 1,
    paddingLeft: 8,
    paddingRight: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 6,
  },
  chipIconWrap: { width: 18, height: 18, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  chipIconImage: { width: 16, height: 16, transform: [{ scale: 1.55 }] },
  temperatureChipIconImage: { transform: [{ scale: 2.25 }] },
  chipText: { fontSize: 10, lineHeight: 12, fontWeight: "700", color: "#1E2A3A", flexShrink: 1, textAlign: "center" },
  quickActionsGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 10, marginTop: 14 },
  quickActionButton: {
    width: "48%",
    minHeight: 92,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  quickActionIconWrap: { width: 38, height: 38, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  quickActionIconImage: { width: 38, height: 38, transform: [{ scale: 1.18 }] },
  temperatureQuickActionIconImage: { transform: [{ scale: 1.62 }] },
  quickActionLabel: { fontSize: 12, lineHeight: 16, fontWeight: "800", color: "#1E2A3A", textAlign: "center" },
  feedButton: {
    marginTop: 14,
    minHeight: 54,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EFDCD2",
    backgroundColor: "#FFFBF8",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  feedLeft: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1, paddingRight: 10 },
  feedIconWrap: { width: 34, height: 34, borderRadius: 999, backgroundColor: "#FFE3DD", alignItems: "center", justifyContent: "center" },
  feedLabel: { flexShrink: 1, fontSize: 16, lineHeight: 21, fontWeight: "700", color: "#1E2A3A" },
  entriesWrap: { marginTop: 12, gap: 14 },
  entrySection: { gap: 10 },
  entrySectionTitle: { color: "#1F2A44", fontSize: 15, lineHeight: 20, fontWeight: "800" },
  entrySectionRows: { gap: 10 },
  entryRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 9,
  },
  entryTime: {
    width: 48,
    paddingTop: 13,
    color: "#6F7C91",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  entryTimelineColumn: {
    width: 12,
    alignItems: "center",
    paddingTop: 17,
  },
  entryDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F2DDD6",
  },
  entryLine: {
    flex: 1,
    width: 1,
    backgroundColor: "#F2DDD6",
    marginTop: 6,
    marginBottom: -2,
  },
  entryCard: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F2DDD6",
    backgroundColor: "#FFFDFC",
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  entryIconWrap: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  entryIconImage: { width: 26, height: 26, transform: [{ scale: 1.34 }] },
  temperatureEntryIconImage: { transform: [{ scale: 1.88 }] },
  entryCopy: { flex: 1, gap: 2 },
  entryType: { color: "#1F2A44", fontSize: 13, lineHeight: 17, fontWeight: "600" },
  entryDetail: { color: "#6F7C91", fontSize: 11, lineHeight: 15, fontWeight: "500" },
  confirmOverlay: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center", paddingHorizontal: 24, zIndex: 60 },
  confirmBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(22, 32, 43, 0.24)" },
  confirmCard: { width: "100%", borderRadius: 28, backgroundColor: "#FFFCF8", padding: 22, borderWidth: 1, borderColor: "#EED8CE" },
  confirmTitle: { fontSize: 22, lineHeight: 28, fontWeight: "800", color: "#1E2A3A" },
  confirmDescription: { marginTop: 8, fontSize: 15, lineHeight: 22, fontWeight: "500", color: "#6B7585" },
  confirmActions: { flexDirection: "row", gap: 10, marginTop: 18 },
  secondaryButton: { flex: 1, minHeight: 54, borderRadius: 999, borderWidth: 1, borderColor: "#F56F68", alignItems: "center", justifyContent: "center" },
  secondaryButtonText: { fontSize: 17, lineHeight: 22, fontWeight: "800", color: "#F56F68" },
  primaryButton: { flex: 1, minHeight: 54, borderRadius: 999, backgroundColor: "#F56F68", alignItems: "center", justifyContent: "center" },
  primaryButtonText: { fontSize: 17, lineHeight: 22, fontWeight: "800", color: "#FFFFFF" },
});
