import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: { ...StyleSheet.absoluteFillObject, zIndex: 30 },
  overlayLayerHidden: { opacity: 0 },
  overlayLayerVisible: { opacity: 1 },
  background: { flex: 1, backgroundColor: "#FFF8F3" },
  root: { flex: 1, paddingHorizontal: 24, paddingTop: 72 },
  swipeBackEdge: { position: "absolute", top: 0, bottom: 0, left: 0, zIndex: 2 },
  scrollContent: { paddingBottom: 120 },
  topBar: { marginBottom: 28 },
  backLink: { alignSelf: "flex-start", paddingVertical: 8 },
  backLinkText: { fontSize: 17, lineHeight: 22, fontWeight: "700", color: "#F56F68" },
  title: { fontSize: 44, lineHeight: 48, fontWeight: "800", letterSpacing: -1, color: "#1E2A3A" },
  subtitle: { marginTop: 6, fontSize: 17, lineHeight: 24, fontWeight: "500", color: "#6B7585", marginBottom: 24 },
  emptyCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EED8CE",
    backgroundColor: "#FFFCF8",
    padding: 22,
  },
  emptyTitle: { fontSize: 24, lineHeight: 30, fontWeight: "800", color: "#1E2A3A" },
  emptySubtitle: { marginTop: 8, fontSize: 15, lineHeight: 22, fontWeight: "500", color: "#6B7585" },
  emptyButton: { marginTop: 18, minHeight: 52, borderRadius: 999, backgroundColor: "#F56F68", alignItems: "center", justifyContent: "center" },
  emptyButtonText: { fontSize: 16, lineHeight: 22, fontWeight: "800", color: "#FFFFFF" },
  card: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EED8CE",
    backgroundColor: "#FFFCF8",
    padding: 18,
    marginBottom: 16,
  },
  cardHeader: { flexDirection: "row", gap: 16, alignItems: "flex-start" },
  avatarWrap: {
    width: 82,
    height: 82,
    borderRadius: 22,
    backgroundColor: "#F8EDE6",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatar: { width: 72, height: 72 },
  cardHeaderCopy: { flex: 1 },
  nameRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 },
  statusDot: { width: 10, height: 10, borderRadius: 999, backgroundColor: "#18A7E0" },
  childName: { fontSize: 26, lineHeight: 32, fontWeight: "800", color: "#1E2A3A" },
  illnessBadge: {
    height: 26,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "#FFE8E6",
    alignItems: "center",
    justifyContent: "center",
  },
  illnessBadgeText: { fontSize: 13, lineHeight: 17, fontWeight: "700", color: "#B74B58" },
  childStats: { marginTop: 6, fontSize: 17, lineHeight: 24, fontWeight: "500", color: "#6B7585" },
  observationSince: { marginTop: 4, fontSize: 17, lineHeight: 24, fontWeight: "500", color: "#6B7585" },
  finishButton: {
    minWidth: 108,
    minHeight: 44,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#F56F68",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  finishButtonText: { fontSize: 15, lineHeight: 20, fontWeight: "700", color: "#1E2A3A" },
  chipsRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 14 },
  chip: {
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    paddingLeft: 9,
    paddingRight: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  chipIconWrap: { width: 28, height: 28, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  chipText: { fontSize: 14, lineHeight: 18, fontWeight: "700", color: "#1E2A3A" },
  quickActionsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 14 },
  quickActionButton: {
    width: "23%",
    minWidth: 72,
    minHeight: 84,
    borderRadius: 18,
    borderWidth: 1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  quickActionIconWrap: { width: 44, height: 44, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  quickActionIconImage: { width: 34, height: 34 },
  quickActionLabel: { fontSize: 12, lineHeight: 16, fontWeight: "800", color: "#1E2A3A", textAlign: "center" },
  feedButton: {
    marginTop: 14,
    minHeight: 54,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EFDCD2",
    backgroundColor: "#FFFBF8",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  feedLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  feedIconWrap: { width: 34, height: 34, borderRadius: 999, backgroundColor: "#FFE3DD", alignItems: "center", justifyContent: "center" },
  feedLabel: { fontSize: 17, lineHeight: 22, fontWeight: "700", color: "#1E2A3A" },
  entriesWrap: { marginTop: 12, gap: 10 },
  entryRow: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EFDCD2",
    backgroundColor: "#FFFBF8",
    padding: 14,
  },
  entryTitle: { fontSize: 15, lineHeight: 20, fontWeight: "800", color: "#1E2A3A" },
  entrySubtitle: { marginTop: 4, fontSize: 14, lineHeight: 20, fontWeight: "500", color: "#6B7585" },
  confirmOverlay: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center", paddingHorizontal: 24, zIndex: 60 },
  confirmBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(22, 32, 43, 0.24)" },
  confirmCard: { width: "100%", borderRadius: 28, backgroundColor: "#FFFCF8", padding: 22, borderWidth: 1, borderColor: "#EED8CE" },
  confirmTitle: { fontSize: 22, lineHeight: 28, fontWeight: "800", color: "#1E2A3A" },
  confirmDescription: { marginTop: 8, fontSize: 15, lineHeight: 22, fontWeight: "500", color: "#6B7585" },
  confirmActions: { flexDirection: "row", gap: 10, marginTop: 18 },
  secondaryButton: { flex: 1, minHeight: 54, borderRadius: 999, borderWidth: 1, borderColor: "#F56F68", alignItems: "center", justifyContent: "center" },
  secondaryButtonText: { fontSize: 17, lineHeight: 22, fontWeight: "800", color: "#F56F68" },
  primaryButton: { flex: 1, minHeight: 54, borderRadius: 999, backgroundColor: "#F56F68", alignItems: "center", justifyContent: "center" },
  primaryButtonText: { fontSize: 17, lineHeight: 22, fontWeight: "800", color: "#FFFFFF" },
});
