import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
    backgroundColor: "#FBF3EC",
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#FBF3EC",
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
  },
  root: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  screen: {
    flex: 1,
  },
  contentWrap: {
    flex: 1,
    paddingHorizontal: 16,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 2,
  },
  scrollContent: {
    flexGrow: 1,
    paddingTop: 46,
    paddingBottom: 40,
  },
  topBar: {
    height: 32,
    justifyContent: "center",
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 0,
  },
  backLinkText: {
    color: "#31485C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  hero: {
    marginBottom: 14,
  },
  title: {
    color: "#252B35",
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "700",
    letterSpacing: -0.45,
  },
  hintSection: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 16,
    borderRadius: 18,
    backgroundColor: "rgba(239,244,252,0.88)",
    borderWidth: 1,
    borderColor: "rgba(207,219,233,0.95)",
  },
  hintTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  hintIconImage: {
    width: 32,
    height: 32,
  },
  hintTitle: {
    color: "#334155",
    fontSize: 16,
    lineHeight: 22,
    fontFamily: Platform.OS === "ios" ? "System" : undefined,
    fontStyle: "italic",
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  hintBody: {
    marginTop: 10,
    paddingLeft: 2,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: Platform.OS === "ios" ? "System" : undefined,
    fontStyle: "italic",
    fontWeight: "400",
    letterSpacing: -0.05,
    color: "#6B7280",
  },
  formCard: {
    backgroundColor: "rgba(255,249,244,0.94)",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EFDDD2",
    padding: 18,
    shadowColor: "#CFAE9F",
    shadowOpacity: 0.08,
    shadowRadius: 11,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  fieldGroup: {
    marginBottom: 12,
  },
  fieldLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  fieldIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#FFF2E8",
    alignItems: "center",
    justifyContent: "center",
  },
  fieldIconImage: {
    width: 28,
    height: 28,
  },
  fieldLabel: {
    color: "#23364A",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
  },
  fieldShell: {
    minHeight: 58,
    borderRadius: 20,
    backgroundColor: "#FFFDF8",
    borderWidth: 1,
    borderColor: "#E5D7CE",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fieldValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  fieldValue: {
    color: "#252B35",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "500",
  },
  textArea: {
    minHeight: 104,
    borderRadius: 20,
    backgroundColor: "#FFFDF8",
    borderWidth: 1,
    borderColor: "#E5D7CE",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
    color: "#252B35",
    textAlignVertical: "top",
  },
  textCounter: {
    alignSelf: "flex-end",
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    color: "#9AA3AF",
  },
  suggestionsCard: {
    marginTop: 0,
    marginBottom: 8,
    borderRadius: 18,
    backgroundColor: "rgba(239,244,252,0.88)",
    borderWidth: 1,
    borderColor: "rgba(207,219,233,0.95)",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  suggestionsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  suggestionsIconImage: {
    width: 32,
    height: 32,
  },
  suggestionsLabel: {
    color: "#23364A",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
  },
  suggestionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  suggestionChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingLeft: 10,
    paddingRight: 14,
    paddingVertical: 10,
    borderRadius: 18,
    backgroundColor: "#FFF4EC",
    borderWidth: 1,
    borderColor: "#E9CFC1",
    width: "48%",
    minHeight: 56,
  },
  suggestionChipActive: {
    backgroundColor: "#F56F68",
    borderColor: "transparent",
  },
  suggestionChipIconWrap: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  suggestionChipIconImage: {
    width: 56,
    height: 56,
    marginLeft: -7,
  },
  suggestionChipText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
    color: "#9A5D50",
    flexShrink: 1,
  },
  suggestionChipTextActive: {
    color: "#FFFFFF",
  },
  buttonsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F1C7BD",
    backgroundColor: "#FFF4F0",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
    color: "#E06356",
  },
  primaryButton: {
    flex: 1.2,
    minHeight: 56,
    borderRadius: 22,
    backgroundColor: "#F26F6C",
    borderWidth: 1,
    borderColor: "#E66561",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 40,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.24)",
  },
  dateSheetCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFFCF8",
    borderWidth: 1,
    borderColor: "#EAD9CE",
    paddingTop: 14,
    paddingHorizontal: 18,
    paddingBottom: 32,
    minHeight: 420,
    shadowColor: "#B98E7E",
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -8 },
  },
  sheetDragZone: {
    paddingBottom: 14,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 54,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#E8D1C7",
    marginBottom: 12,
  },
  sheetTitle: {
    color: "#23364A",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "700",
  },
  sheetSubtitle: {
    marginTop: 4,
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
  },
  dateSheetPreview: {
    minHeight: 58,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5D7CE",
    backgroundColor: "#FFF7F1",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  dateSheetPreviewText: {
    color: "#23364A",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
    textAlign: "center",
  },
  sheetScrollContent: {
    paddingBottom: 6,
  },
  dateOption: {
    minHeight: 54,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5D7CE",
    paddingHorizontal: 16,
    justifyContent: "center",
    marginBottom: 10,
    backgroundColor: "#FFFDF8",
  },
  dateOptionActive: {
    borderColor: "#F26F6C",
    backgroundColor: "#FFF1E9",
  },
  dateOptionText: {
    color: "#252B35",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
  },
  dateOptionTextActive: {
    color: "#F26F6C",
  },
  confirmOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    zIndex: 60,
  },
  confirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(22, 32, 43, 0.24)",
  },
  confirmCard: {
    width: "100%",
    borderRadius: 28,
    backgroundColor: "#FFFDF9",
    padding: 20,
    borderWidth: 1,
    borderColor: "#EBCFC4",
    shadowColor: "#CFAE9F",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  confirmTitle: {
    color: "#252B35",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
  },
  confirmDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    color: "#6F7178",
  },
  confirmActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
});
