import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#FFF7F2",
  },
  background: {
    flex: 1,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  imageSoftener: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,247,242,0.08)",
  },
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 40,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(34,26,22,0.2)",
  },
  keyboard: {
    flex: 1,
  },
  screen: {
    flex: 1,
  },
  screenScrollContent: {
    flex: 1,
    paddingBottom: 156,
  },
  headlineTop: {
    marginTop: 60,
    marginBottom: 18,
    paddingHorizontal: 42,
    textAlign: "center",
    color: "#5F6F7D",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
    letterSpacing: 0.1,
  },
  sheet: {
    width: "100%",
    position: "relative",
    backgroundColor: "transparent",
    marginTop: 316,
    paddingTop: 0,
    paddingHorizontal: 22,
    paddingBottom: 12,
    alignItems: "center",
  },
  switchWrap: {
    width: "100%",
    marginBottom: 14,
    zIndex: 2,
  },
  tabsShell: {
    position: "relative",
    flexDirection: "row",
    minHeight: 54,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(248,220,211,0.92)",
    backgroundColor: "rgba(255,255,255,0.34)",
    padding: 4,
  },
  tabIndicator: {
    position: "absolute",
    top: 4,
    bottom: 4,
    left: 4,
    borderRadius: 24,
    backgroundColor: "#F87566",
    borderWidth: 1,
    borderColor: "#EF6658",
    shadowColor: "#F87566",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  tabButton: {
    flex: 1,
    minHeight: 46,
    zIndex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  tabButtonPressed: {
    opacity: 0.92,
  },
  tabLabel: {
    color: "#8C7D75",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "500",
  },
  tabLabelActive: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  formGroup: {
    width: "100%",
    zIndex: 2,
  },
  familyCodeCard: {
    width: "100%",
    marginTop: 4,
    marginBottom: 4,
    zIndex: 2,
  },
  familyCodeToggle: {
    minHeight: 52,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(239,218,210,0.92)",
    backgroundColor: "rgba(255,253,249,0.88)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  familyCodeTogglePressed: {
    opacity: 0.94,
  },
  familyCodeToggleCopy: {
    flex: 1,
    paddingRight: 12,
  },
  familyCodeToggleTitle: {
    color: "#24384F",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  familyCodeToggleMeta: {
    marginTop: 3,
    color: "#8D7A73",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  familyCodeBody: {
    marginTop: 8,
    gap: 8,
  },
  familyCodeVerifiedCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(239,218,210,0.92)",
    backgroundColor: "rgba(255,253,249,0.96)",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  familyCodeVerifiedLabel: {
    color: "#F87566",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  familyCodeVerifiedName: {
    marginTop: 4,
    color: "#24384F",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  familyCodeActionButton: {
    alignSelf: "flex-start",
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: "rgba(248,117,102,0.12)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    marginTop: 2,
  },
  familyCodeActionButtonDisabled: {
    opacity: 0.6,
  },
  familyCodeActionButtonPressed: {
    opacity: 0.88,
  },
  familyCodeActionLabel: {
    color: "#F87566",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  familyCodeInlineStatus: {
    color: "#F87566",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "800",
    marginLeft: 8,
  },
  fieldBlock: {
    gap: 6,
  },
  fieldShell: {
    minHeight: 56,
    borderWidth: 1,
    borderColor: "rgba(239,218,210,0.92)",
    backgroundColor: "rgba(255,253,249,0.96)",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 16,
    paddingRight: 16,
  },
  fieldSingle: {
    borderRadius: 20,
  },
  fieldTop: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  fieldMiddle: {
    borderTopWidth: 0,
  },
  fieldBottom: {
    borderTopWidth: 0,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  fieldShellError: {
    borderColor: "#E6A399",
    backgroundColor: "rgba(255,246,244,0.96)",
  },
  fieldShellSuccess: {
    borderColor: "#7DBB86",
    backgroundColor: "rgba(246,255,247,0.96)",
  },
  fieldIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    color: "#24384F",
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "400",
    paddingVertical: 10,
  },
  eyeButton: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  fieldError: {
    color: "#D36C59",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    paddingHorizontal: 2,
  },
  formErrorSlot: {
    width: "100%",
    minHeight: 18,
    marginTop: 6,
  },
  authOptionsRow: {
    width: "100%",
    alignItems: "flex-end",
    marginTop: 12,
    marginBottom: 14,
    zIndex: 2,
  },
  forgotPasswordButton: {
    paddingVertical: 4,
  },
  forgotPasswordText: {
    color: "#F87566",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "500",
  },
  primaryButton: {
    width: "100%",
    minHeight: 60,
    borderRadius: 22,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    zIndex: 2,
    shadowColor: "#F87566",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  primaryButtonGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  primaryButtonDisabled: {
    opacity: 0.55,
  },
  primaryButtonPressed: {
    transform: [{ scale: 0.992 }],
  },
  primaryButtonLabel: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
  bottomLegalWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 28,
    width: "100%",
    paddingHorizontal: 14,
    alignItems: "center",
  },
  supportLinkButton: {
    paddingVertical: 6,
    marginBottom: 8,
  },
  supportLinkText: {
    color: "#8D7A73",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    textAlign: "center",
  },
  legalFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    zIndex: 2,
  },
  legalFooterLink: {
    color: "#8D7A73",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  legalFooterDot: {
    color: "#C7B1A7",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  forgotPasswordSheetCard: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFFCF8",
    width: "100%",
    paddingTop: 14,
    paddingHorizontal: 18,
    paddingBottom: 0,
    minHeight: 452,
    maxHeight: 620,
    shadowColor: "#B98E7E",
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -8 },
  },
  forgotPasswordSheetScroll: {
    width: "100%",
  },
  forgotPasswordSheetScrollContent: {
    paddingBottom: 28,
  },
  forgotPasswordSheetInner: {
    width: "100%",
  },
  forgotPasswordFields: {
    gap: 10,
    marginTop: 12,
  },
  sheetDragZone: {
    paddingTop: 4,
    paddingBottom: 16,
    marginBottom: 2,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 54,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#E8D1C7",
    marginBottom: 12,
  },
  forgotPasswordSheetTitle: {
    color: "#23364A",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
  },
  forgotPasswordSheetSubtitle: {
    marginTop: 4,
    color: "#6F7E8D",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
  },
  forgotPasswordField: {
    minHeight: 54,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(239,218,210,0.92)",
    backgroundColor: "rgba(255,253,249,0.96)",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 16,
    paddingRight: 16,
  },
  forgotPasswordSubmitButton: {
    width: "100%",
    minHeight: 56,
    borderRadius: 20,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
    shadowColor: "#F87566",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
});
