import { redesignSharedIcons } from "../../shared/icons";

export const childrenScreenSpec = require("./child_page.json");

export const childrenScreenAssets = {
  background: require("../../shared/backgrounds/children_module_background_1179x2556.webp"),
  icons: {
    sleep: redesignSharedIcons.sleep,
    feeding: redesignSharedIcons.feeding,
    observation: redesignSharedIcons.observation,
    profile: redesignSharedIcons.profile,
  },
  avatars: {
    boy: require("./avatars/boy_transparent.png"),
    boyBlackHair: require("./avatars/boy_black_hair_transparent.png"),
    boyRedHair: require("./avatars/boy_red_hair_transparent.png"),
    boyGlasses: require("./avatars/boy_glasses_transparent.png"),
    boyCurlsDark: require("./avatars/boy_curls_dark_transparent.png"),
    boyCurlsLight: require("./avatars/boy_curls_light_transparent.png"),
    girl: require("./avatars/girl_transparent.png"),
    girlBlonde: require("./avatars/girl_blonde_transparent.png"),
    girlPigtails: require("./avatars/girl_pigtails_transparent.png"),
    girlBraidGlasses: require("./avatars/girl_braid_glasses_transparent.png"),
    girlHeadband: require("./avatars/girl_headband_transparent.png"),
    girlRedCurls: require("./avatars/girl_red_curls_transparent.png"),
    girlDarkBob: require("./avatars/girl_dark_bob_transparent.png"),
    girlDarkCurlsBow: require("./avatars/girl_dark_curls_bow_transparent.png"),
    babyBoy: require("./avatars/baby_boy_transparent.png"),
    babyBoyCurls: require("./avatars/baby_boy_curls_transparent.png"),
    babyBoyBlondeBlue: require("./avatars/baby_boy_blonde_blue_transparent.png"),
    babyBoyDarkSide: require("./avatars/baby_boy_dark_side_transparent.png"),
    babyBoyBlondeShort: require("./avatars/baby_boy_blonde_short_transparent.png"),
    babyBoyBrownCurls: require("./avatars/baby_boy_brown_curls_transparent.png"),
    babyGirlCurls: require("./avatars/baby_girl_curls_transparent.png"),
    babyGirlBlondePigtails: require("./avatars/baby_girl_blonde_pigtails_transparent.png"),
    babyGirlBlondePigtailsAlt: require("./avatars/baby_girl_blonde_pigtails_alt_transparent.png"),
    babyGirlDarkSideclip: require("./avatars/baby_girl_dark_sideclip_transparent.png"),
    babyGirlDarkPuffBuns: require("./avatars/baby_girl_dark_puff_buns_transparent.png"),
    babyGirlCurlsBow: require("./avatars/baby_girl_curls_bow_transparent.png"),
    babyGirlRedBobFlower: require("./avatars/baby_girl_red_bob_flower_transparent.png"),
    child1: require("./avatars/child_icon_transparent_1.png"),
    child2: require("./avatars/child_icon_transparent_2.png"),
    child3: require("./avatars/child_icon_transparent_3.png"),
  },
} as const;
