import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 40,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.24)",
  },
  sheet: {
    position: "relative",
    zIndex: 2,
    minHeight: "61%",
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    backgroundColor: "#FFFCF7",
    paddingTop: 16,
    paddingHorizontal: 18,
    paddingBottom: 18,
    shadowColor: "#B98E7E",
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -8 },
  },
  handle: {
    alignSelf: "center",
    width: 54,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#E8D1C7",
    marginBottom: 14,
  },
  eyebrow: {
    color: "#B98575",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  title: {
    marginTop: 10,
    color: "#233246",
    fontSize: 29,
    lineHeight: 33,
    fontWeight: "800",
  },
  subtitle: {
    marginTop: 10,
    color: "#6E7B8C",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "500",
  },
  section: {
    marginTop: 18,
  },
  sectionTitle: {
    color: "#233246",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "800",
    marginBottom: 12,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  optionCard: {
    width: "48.5%",
    minHeight: 68,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#EBD2C6",
    backgroundColor: "#FFFDF8",
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  optionCardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.985 }],
  },
  optionCardActive: {
    borderColor: "#F5A095",
    backgroundColor: "#FFF2EC",
  },
  optionIconBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  optionLabel: {
    flex: 1,
    color: "#233246",
    fontSize: 17,
    lineHeight: 20,
    fontWeight: "700",
  },
  infoCard: {
    marginTop: 14,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#EBD2C6",
    backgroundColor: "#FFF3EC",
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  infoText: {
    flex: 1,
    color: "#6E7B8C",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "500",
  },
  periodCard: {
    width: "48.5%",
    minHeight: 62,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#EBD2C6",
    backgroundColor: "#FFFDF8",
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  periodCardActive: {
    borderColor: "#F5A095",
    backgroundColor: "#FFF2EC",
  },
  periodIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    backgroundColor: "#FFF6F1",
  },
  periodIconBadgeActive: {
    backgroundColor: "#FFF0E8",
  },
  periodLabel: {
    flex: 1,
    color: "#233246",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
  actionsRow: {
    marginTop: 18,
    flexDirection: "row",
    gap: 10,
  },
  actionButtonShell: {
    flex: 1,
  },
  actionButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  actionButtonSecondary: {
    borderWidth: 1.5,
    borderColor: "#EBD2C6",
    backgroundColor: "#FFFDF8",
  },
  actionButtonPrimary: {
    overflow: "hidden",
    shadowColor: "#F8766D",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  actionButtonDisabled: {
    opacity: 0.52,
  },
  actionGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  actionLabel: {
    color: "#233246",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
  },
  actionLabelPrimary: {
    color: "#FFFFFF",
  },
  actionLabelDisabled: {
    color: "#7F8892",
  },
  actionLabelDisabledPrimary: {
    color: "rgba(255,255,255,0.88)",
  },
});
