import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 40,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.24)",
  },
  sheet: {
    position: "relative",
    zIndex: 2,
    height: "66%",
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    backgroundColor: "#FFFCF7",
    shadowColor: "#B98E7E",
    shadowOpacity: 0.16,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -8 },
    overflow: "hidden",
  },
  topSwipeZone: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 126,
    zIndex: 3,
  },
  content: {
    flex: 1,
    paddingTop: 12,
    paddingHorizontal: 18,
    paddingBottom: 18,
  },
  headerDragZone: {
    paddingBottom: 10,
  },
  handle: {
    alignSelf: "center",
    width: 54,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#E8D1C7",
    marginBottom: 10,
  },
  eyebrow: {
    color: "#B98575",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  title: {
    marginTop: 6,
    color: "#233246",
    fontSize: 23,
    lineHeight: 27,
    fontWeight: "800",
  },
  subtitle: {
    marginTop: 6,
    color: "#6E7B8C",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
  },
  body: {
    paddingBottom: 4,
  },
  section: {
    marginTop: 12,
  },
  sectionTitle: {
    color: "#233246",
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "800",
    marginBottom: 8,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  optionCard: {
    width: "48.5%",
    minHeight: 58,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EBD2C6",
    backgroundColor: "#FFFDF8",
    paddingHorizontal: 10,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
  },
  optionCardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.985 }],
  },
  optionCardActive: {
    borderColor: "#F5A095",
    backgroundColor: "#FFF2EC",
  },
  optionIconBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  optionLabel: {
    flex: 1,
    color: "#233246",
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "700",
  },
  infoCard: {
    marginTop: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EBD2C6",
    backgroundColor: "#FFF3EC",
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  infoText: {
    flex: 1,
    color: "#6E7B8C",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  periodCard: {
    width: "48.5%",
    minHeight: 54,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EBD2C6",
    backgroundColor: "#FFFDF8",
    paddingHorizontal: 10,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
  },
  periodCardActive: {
    borderColor: "#F5A095",
    backgroundColor: "#FFF2EC",
  },
  periodIconBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    backgroundColor: "#FFF6F1",
  },
  periodIconBadgeActive: {
    backgroundColor: "#FFF0E8",
  },
  periodLabel: {
    flex: 1,
    color: "#233246",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  footer: {
    marginTop: 4,
    paddingTop: 0,
    flexDirection: "row",
    gap: 10,
  },
  actionButtonShell: {
    flex: 1,
  },
  actionButton: {
    minHeight: 44,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  actionButtonSecondary: {
    borderWidth: 1,
    borderColor: "#EBD2C6",
    backgroundColor: "#FFFDF8",
  },
  actionButtonPrimary: {
    overflow: "hidden",
    shadowColor: "#F8766D",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  actionButtonDisabled: {
    opacity: 0.52,
  },
  actionGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  actionLabel: {
    color: "#233246",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "800",
    textAlign: "center",
  },
  actionLabelPrimary: {
    color: "#FFFFFF",
  },
  actionLabelDisabled: {
    color: "#7F8892",
  },
  actionLabelDisabledPrimary: {
    color: "rgba(255,255,255,0.88)",
  },
});
