import type { AppLanguage } from "@shared/i18n";

export const familyCopy = {
  ru: {
    title: "Семья",
    subtitle: "Родители и близкие работают в одном семейном пространстве.",
    loadFamilyFailed: "Не удалось загрузить семью.",
    loadMembersFailed: "Не удалось загрузить участников.",
    updateFamilyFailed: "Не удалось обновить название семьи.",
    createInviteFailed: "Не удалось создать ссылку приглашения.",
    updateRoleFailed: "Не удалось обновить роль участника.",
    deleteMemberFailed: "Не удалось удалить участника из семьи.",
    updateProfileFailed: "Не удалось обновить профиль участника.",
    familyNameTitle: "Название семьи",
    familyNameDescription: "Общее название, которое видят все участники семьи.",
    edit: "Изменить",
    hide: "Скрыть",
    familyNameMissing: "Название пока не указано",
    newFamilyName: "Новое название",
    newFamilyNamePlaceholder: "Например: Семья Ивановых",
    saving: "Сохраняем…",
    save: "Сохранить",
    cancel: "Отмена",
    membersTitle: "Участники семьи",
    membersDescription:
      "Владельцы могут приглашать новых взрослых, менять роли и отзывать доступ.",
    peopleShort: "чел.",
    membersLoading: "Загружаем участников…",
    noMembers: "У семьи пока нет подключённых участников.",
    inviteTitle: "Пригласить в приложение",
    inviteDescription:
      "Отправьте приглашение близкому. Он установит приложение или откроет ссылку и подключится к вашей семье под своим аккаунтом.",
    ownerOnly: "Только для владельца",
    creatingInvite: "Готовим приглашение…",
    createInvite: "Пригласить",
    newLink: "Новая ссылка",
    validUntil: "Действует до",
    inviteCopied: "Ссылка скопирована",
    inviteShareReady: "Открылось меню «Поделиться».",
    inviteCopyFailed: "Не удалось скопировать ссылку.",
    inviteShareFailed: "Не удалось открыть меню «Поделиться».",
    shareInvite: "Поделиться",
    copyInvite: "Скопировать ссылку",
    owner: "Владелец",
    member: "Участник",
    noName: "Без имени",
    thisIsYou: "Это вы",
    emailMissing: "Email не указан",
    phoneMissing: "Телефон не указан",
    hideProfile: "Скрыть профиль",
    editProfile: "Редактировать профиль",
    makeOwner: "Сделать владельцем",
    makeAdult: "Сделать участником",
    removeFromFamily: "Удалить из семьи",
    confirmPromoteTitle: "Сделать участника владельцем?",
    confirmPromoteDescription:
      "Участник получит права владельца семьи: сможет приглашать и удалять участников, а также менять роли.",
    confirmPromoteAction: "Да, сделать владельцем",
    confirmDemoteTitle: "Снять роль владельца?",
    confirmDemoteDescription:
      "Участник останется в семье, но потеряет права владельца и станет обычным участником.",
    confirmDemoteAction: "Да, сделать участником",
    confirmRemoveTitle: "Удалить участника из семьи?",
    confirmRemoveDescription:
      "Участник потеряет доступ к вашей семейной базе. Это действие можно будет вернуть только новым приглашением.",
    confirmRemoveAction: "Да, удалить",
    displayName: "Имя в семье",
    displayNamePlaceholder: "Например: Оля",
    relationship: "Кто это в семье",
    relationshipPlaceholder: "Например: няня",
    phone: "Телефон",
    email: "Email",
    emailPlaceholder: "you@example.com",
    invalidEmail: "Введите корректный email или оставьте поле пустым.",
    saveProfile: "Сохранить профиль",
  },
  en: {
    title: "Family",
    subtitle: "Parents and relatives work together in one family space.",
    loadFamilyFailed: "Could not load family.",
    loadMembersFailed: "Could not load members.",
    updateFamilyFailed: "Could not update the family name.",
    createInviteFailed: "Could not create an invite link.",
    updateRoleFailed: "Could not update the member role.",
    deleteMemberFailed: "Could not remove the member from the family.",
    updateProfileFailed: "Could not update the member profile.",
    familyNameTitle: "Family name",
    familyNameDescription: "Shared name visible to everyone in your family space.",
    edit: "Edit",
    hide: "Hide",
    familyNameMissing: "Family name is not set yet",
    newFamilyName: "New family name",
    newFamilyNamePlaceholder: "Example: The Ivanov Family",
    saving: "Saving…",
    save: "Save",
    cancel: "Cancel",
    membersTitle: "Family members",
    membersDescription: "Owners can invite new adults, change roles and revoke access.",
    peopleShort: "people",
    membersLoading: "Loading members…",
    noMembers: "No family members are connected yet.",
    inviteTitle: "Invite to the app",
    inviteDescription:
      "Send an invite to a family member. They can install the app or open the link and join your family with their own account.",
    ownerOnly: "Owners only",
    creatingInvite: "Preparing invite…",
    createInvite: "Invite",
    newLink: "New link",
    validUntil: "Valid until",
    inviteCopied: "Link copied",
    inviteShareReady: "Share sheet opened.",
    inviteCopyFailed: "Could not copy the link.",
    inviteShareFailed: "Could not open the share sheet.",
    shareInvite: "Share",
    copyInvite: "Copy link",
    owner: "Owner",
    member: "Member",
    noName: "No name",
    thisIsYou: "You",
    emailMissing: "Email is not set",
    phoneMissing: "Phone is not set",
    hideProfile: "Hide profile",
    editProfile: "Edit profile",
    makeOwner: "Make owner",
    makeAdult: "Make adult",
    removeFromFamily: "Remove from family",
    confirmPromoteTitle: "Promote this member to owner?",
    confirmPromoteDescription:
      "The member will get family owner permissions: invite/remove members and manage roles.",
    confirmPromoteAction: "Yes, make owner",
    confirmDemoteTitle: "Remove owner role?",
    confirmDemoteDescription:
      "The member will stay in the family but lose owner permissions and become an adult.",
    confirmDemoteAction: "Yes, make adult",
    confirmRemoveTitle: "Remove this member from family?",
    confirmRemoveDescription:
      "The member will lose access to your family workspace. Access can be restored only with a new invite.",
    confirmRemoveAction: "Yes, remove",
    displayName: "Family name",
    displayNamePlaceholder: "Example: Olivia",
    relationship: "Relationship",
    relationshipPlaceholder: "Example: nanny",
    phone: "Phone",
    email: "Email",
    emailPlaceholder: "you@example.com",
    invalidEmail: "Enter a valid email or leave the field empty.",
    saveProfile: "Save profile",
  },
} satisfies Record<AppLanguage, Record<string, string>>;

export function tFamily(language: AppLanguage, key: keyof (typeof familyCopy)["ru"]) {
  return familyCopy[language][key];
}

export function roleLabel(role: string, language: AppLanguage): string {
  return role === "owner" ? tFamily(language, "owner") : tFamily(language, "member");
}
