import type { AppLanguage } from "@shared/i18n";

export const cabinetCopy = {
  ru: {
    title: "Аптечка",
    subtitle:
      "Реальные упаковки дома: срок годности, дата вскрытия и можно ли использовать препарат сейчас.",
    mobileHint: "Домашние лекарства, сроки и статус.",
    addTab: "Добавить",
    cabinetTab: "Упаковки",
    addChoiceTitle: "Добавить препарат",
    addChoiceSubtitle: "Выберите, откуда добавить препарат. Дальше откроется отдельное окно.",
    addFromCatalog: "Из справочника",
    addFromCatalogHint:
      "Быстрее и безопаснее: форма, дозировка и срок после вскрытия подтянутся из базы.",
    addOwnMedicine: "Свой препарат",
    addOwnMedicineHint:
      "Если препарата нет в справочнике или нужно завести домашнюю заготовку вручную.",
    back: "Назад",
    loading: "Загрузка...",
    loadError: "Ошибка загрузки",
    empty: "В аптечке пока нет препаратов. Нажмите «Добавить препарат».",
    searchLabel: "Найти в аптечке",
    searchPlaceholder: "Название, форма или комментарий",
    foundCount: "Найдено: {{count}}",
    nothingFound: "По запросу ничего не найдено.",
    emptyFilter: "В этом разделе пока пусто.",
    filterAttention: "Проверить",
    filterReady: "Можно",
    filterAll: "Все",
    attentionSectionTitle: "Проверить сейчас",
    attentionSectionHint: "Сначала проверьте просроченные и те, что нужно оценить после вскрытия.",
    readySectionTitle: "Можно использовать",
    readySectionHint: "Упаковки, которые сейчас выглядят безопасными.",
    allSectionTitle: "Все упаковки",
    allSectionHint: "Полный список домашних лекарств и сроков.",
    sectionCount: "{{count}}",
    statusExpired: "Просрочен",
    statusCheckOpened: "Проверьте после вскрытия",
    statusExpiringSoon: "Скоро закончится срок",
    statusOk: "Можно использовать",
    untilOpened: "После вскрытия до {{date}}",
    untilExpiry: "Годен до {{date}}",
    addPack: "Добавить упаковку",
    catalogSearch: "Поиск по справочнику",
    catalogSearchPlaceholder: "Название препарата",
    searching: "Поиск...",
    catalogSearchHint: "Начните вводить название, затем выберите препарат из списка.",
    catalogNoResults: "В справочнике ничего не найдено. Попробуйте другое название.",
    catalogPickFirst: "Сначала выберите препарат из справочника.",
    manualMainSection: "Основное",
    manualTextSection: "Описание и применение",
    packageSection: "Упаковка",
    dosageHint: "Как применять: {{value}}",
    descriptionLabel: "Описание: {{value}}",
    openedShelfHint: "После вскрытия: {{days}} дн.",
    switchMedicine: "Сменить препарат",
    newMedicineName: "Название нового препарата",
    newMedicineNamePlaceholder: "Название нового препарата",
    medicineForm: "Форма препарата",
    concentration: "Концентрация",
    concentrationPlaceholder: "Концентрация",
    description: "Описание",
    descriptionPlaceholder: "Для чего препарат и в каких случаях нужен",
    usage: "Как применять",
    usagePlaceholder: "Например: по 5 мл 3 раза в день после еды",
    expiryDate: "Срок годности",
    openedAt: "Дата вскрытия",
    openedShelfDays: "Сколько хранится после вскрытия",
    openedShelfDaysUnknown: "Если не знаете, оставьте пустым",
    openedShelfDaysAuto:
      "Если у препарата есть срок после вскрытия в справочнике, он подставится автоматически.",
    openedShelfDaysError: "Срок после вскрытия укажите числом от 1 до 3650 дней.",
    expiredWarning:
      "Срок годности уже истёк. Препарат можно сохранить в аптечку для учёта, но Safety Engine не даст использовать его в приёмах.",
    openedUnknownWarning:
      "Дата вскрытия указана, но срок после вскрытия не задан. Препарат сохранится, но оценка после вскрытия будет считаться неизвестной.",
    comment: "Комментарий",
    commentPlaceholder: "Необязательно. Например: хранить в холодильнике",
    addToKit: "Добавить в аптечку",
    addOwnToKit: "Добавить свой препарат в аптечку",
    reset: "Сбросить",
    expiryDateError: "Укажите корректный срок годности через календарь.",
    openedAtError: "Укажите корректную дату вскрытия через календарь.",
    addError: "Не удалось добавить препарат.",
    writeOffTitle: "Убрать упаковку · {{name}}",
    writeOffDescription:
      "Упаковка исчезнет из аптечки. Используйте это, если лекарство закончилось, испортилось или вы его выбросили.",
    writeOffPending: "Убираем...",
    writeOff: "Убрать упаковку",
    hide: "Скрыть",
    details: "Подробнее",
    newPack: "Новая упаковка",
    close: "Закрыть",
    formField: "Форма: {{value}}",
    openedFieldKnown: "Вскрыто: {{date}} · После вскрытия: {{days}} дн.{{untilText}}",
    openedFieldUnknown: "Вскрыто: {{date}} · Срок после вскрытия не указан{{untilText}}",
    useUntil: " · Использовать до: {{date}}",
    usageField: "Как применять: {{value}}",
    descriptionField: "Описание: {{value}}",
    commentField: "Комментарий: {{value}}",
    newPackHint: "Здесь обновляются только данные новой упаковки. Название и форма уже сохранены.",
    save: "Сохранить",
    expiredCardWarning:
      "Срок годности уже истёк. Препарат останется в аптечке для учёта, но использовать его в приёмах нельзя.",
    openedCardWarning:
      "Дата вскрытия указана, но срок после вскрытия не задан. Статус после вскрытия будет считаться неизвестным.",
    tablets: "Таблетки",
    syrup: "Сироп",
    drops: "Капли",
    suspension: "Суспензия",
    solution: "Раствор",
    suppositories: "Суппозитории (свечи)",
  },
  en: {
    title: "First aid kit",
    subtitle:
      "Real packs at home: expiry dates, opened dates and whether a medicine can be used right now.",
    mobileHint: "Home medicines, expiry dates and status.",
    addTab: "Add",
    cabinetTab: "Packs",
    addChoiceTitle: "Add medicine",
    addChoiceSubtitle: "Choose how to add the medicine. The next step opens in a separate screen.",
    addFromCatalog: "From catalog",
    addFromCatalogHint:
      "Faster and safer: form, dosage and post-opening shelf life come from the catalog.",
    addOwnMedicine: "Custom medicine",
    addOwnMedicineHint:
      "Use this when the medicine is not in the catalog or you need a manual item.",
    back: "Back",
    loading: "Loading...",
    loadError: "Failed to load data",
    empty: "There are no medicines in your first aid kit yet. Tap “Add medicine”.",
    searchLabel: "Search first aid kit",
    searchPlaceholder: "Name, form or comment",
    foundCount: "Found: {{count}}",
    nothingFound: "Nothing matches this search.",
    emptyFilter: "There is nothing in this section yet.",
    filterAttention: "Review",
    filterReady: "Ready",
    filterAll: "All",
    attentionSectionTitle: "Review now",
    attentionSectionHint:
      "Check expired medicines and the ones that need review after opening first.",
    readySectionTitle: "Ready to use",
    readySectionHint: "Packs that look safe to use right now.",
    allSectionTitle: "All packs",
    allSectionHint: "The full list of home medicines and dates.",
    sectionCount: "{{count}}",
    statusExpired: "Expired",
    statusCheckOpened: "Check after opening",
    statusExpiringSoon: "Expiring soon",
    statusOk: "Can be used",
    untilOpened: "After opening until {{date}}",
    untilExpiry: "Good until {{date}}",
    addPack: "Add pack",
    catalogSearch: "Catalog search",
    catalogSearchPlaceholder: "Medicine name",
    searching: "Searching...",
    catalogSearchHint: "Start typing the name, then choose a medicine from the list.",
    catalogNoResults: "Nothing found in the catalog. Try another name.",
    catalogPickFirst: "Choose a medicine from the catalog first.",
    manualMainSection: "Main details",
    manualTextSection: "Description and use",
    packageSection: "Pack",
    dosageHint: "How to use: {{value}}",
    descriptionLabel: "Description: {{value}}",
    openedShelfHint: "After opening: {{days}} days",
    switchMedicine: "Change medicine",
    newMedicineName: "New medicine name",
    newMedicineNamePlaceholder: "New medicine name",
    medicineForm: "Medicine form",
    concentration: "Concentration",
    concentrationPlaceholder: "Concentration",
    description: "Description",
    descriptionPlaceholder: "What it is for and when it is used",
    usage: "How to use",
    usagePlaceholder: "Example: 5 ml 3 times a day after meals",
    expiryDate: "Expiry date",
    openedAt: "Opened date",
    openedShelfDays: "How long it keeps after opening",
    openedShelfDaysUnknown: "Leave empty if you do not know it",
    openedShelfDaysAuto:
      "If the catalog already has a shelf life after opening, it will be filled in automatically.",
    openedShelfDaysError: "Shelf life after opening must be a number from 1 to 3650 days.",
    expiredWarning:
      "The expiry date has already passed. You can still keep the medicine in the first aid kit for reference, but the Safety Engine will not allow it in medication plans.",
    openedUnknownWarning:
      "Opened date is set, but shelf life after opening is missing. The medicine will be saved, but post-opening status will stay unknown.",
    comment: "Comment",
    commentPlaceholder: "Optional. For example: keep in the fridge",
    addToKit: "Add to first aid kit",
    addOwnToKit: "Add your own medicine to the first aid kit",
    reset: "Reset",
    expiryDateError: "Pick a valid expiry date from the calendar.",
    openedAtError: "Pick a valid opened date from the calendar.",
    addError: "Could not add the medicine.",
    writeOffTitle: "Remove pack · {{name}}",
    writeOffDescription:
      "The pack will disappear from the first aid kit. Use this when it is finished, spoiled or discarded.",
    writeOffPending: "Removing...",
    writeOff: "Remove pack",
    hide: "Hide",
    details: "Details",
    newPack: "New pack",
    close: "Close",
    formField: "Form: {{value}}",
    openedFieldKnown: "Opened: {{date}} · After opening: {{days}} days{{untilText}}",
    openedFieldUnknown: "Opened: {{date}} · Shelf life after opening is unknown{{untilText}}",
    useUntil: " · Use until: {{date}}",
    usageField: "How to use: {{value}}",
    descriptionField: "Description: {{value}}",
    commentField: "Comment: {{value}}",
    newPackHint: "Only the new pack data changes here. Name and form are already saved.",
    save: "Save",
    expiredCardWarning:
      "The expiry date has already passed. The medicine stays in the first aid kit for reference, but it cannot be used in medication plans.",
    openedCardWarning:
      "Opened date is set, but shelf life after opening is missing. Post-opening status will stay unknown.",
    tablets: "Tablets",
    syrup: "Syrup",
    drops: "Drops",
    suspension: "Suspension",
    solution: "Solution",
    suppositories: "Suppositories",
  },
} satisfies Record<AppLanguage, Record<string, string>>;

export type CabinetCopyKey = keyof (typeof cabinetCopy)["ru"];

export function tCabinet(
  language: AppLanguage,
  key: CabinetCopyKey,
  variables?: Record<string, string | number>
) {
  const template = cabinetCopy[language][key];
  if (!variables) return template;
  return Object.entries(variables).reduce(
    (result, [name, value]) => result.replace(`{{${name}}}`, String(value)),
    template
  );
}
