export const childCalendarCopy = {
  ru: {
    loading: "Загрузка…",
    back: "← К профилю ребёнка",
    title: "Обзор",
    hint: "Лента, календарь и графики помогают быстро понять, что происходило с ребёнком.",
    feed: "Лента",
    calendar: "Календарь",
    charts: "Графики",
    day: "День",
    today: "Сегодня",
    week: "7 дней",
    twoWeeks: "14 дней",
    month: "30 дней",
    date: "Дата",
    customPeriod: "Свой период",
    editCustomPeriod: "Изменить",
    dateFrom: "Начало",
    dateTo: "Конец",
    customPeriodTitle: "Свой период",
    customPeriodHint: "Выберите даты, за которые нужно показать ленту, календарь и графики.",
    choosePeriod: "Выберите период",
    select: "Выбрать",
    periodAffectsFeed: "Это влияет на ленту, календарь и графики.",
    customDatesTitle: "Выбор даты",
    customDatesHint: "Выберите период для ленты и краткой аналитики.",
    apply: "Применить",
    cancel: "Отмена",
    closePeriodDialog: "Закрыть выбор периода",
    summaryPeriodPrefix: "За период",
    all: "Все",
    filters: {
      sleep: "Сон",
      feeding: "Кормление",
      illness: "Болезни",
      weight: "Вес",
      height: "Рост",
    },
    summary: {
      sleep: "Сон",
      feeding: "Кормление",
      illness: "Болезни",
      weight: "Вес",
      height: "Рост",
      formulaAverage: "Смесь",
      measurements: "Рост/вес",
      events: "Событий",
      noData: "Нет данных",
      none: "Нет",
      calm: "спокойно",
      perDay: "в день",
      episodes: "эп.",
      records: "зап.",
      active: "активно",
      latest: "последнее",
    },
    empty: "За выбранный период событий нет. Измените дату, период или фильтры.",
    calendarHint: "Точки показывают типы событий в дне. Нажмите на день, чтобы открыть ленту дня.",
    dayFeedTitle: "Лента дня",
    backToCalendar: "Назад к календарю",
    dayFeedEmpty: "В этот день событий по выбранным фильтрам нет.",
    chartsHint:
      "Быстрые графики по выбранному периоду. Детальную аналитику добавим следующим этапом.",
    sleepTotal: "Сон за период",
    feedingTotal: "Кормлений",
    feedingFormulaTotal: "Смесь за период",
    illnessTotal: "Болезней",
    measurements: "Замеры",
    chartAverage: "среднее",
    chartTotal: "всего",
    chartDays: "дней с данными",
    chartSleepHint: "Сколько в среднем малыш спит по дням.",
    chartFeedingHint: "Частота кормлений и объем смеси по дням.",
    chartIllnessHint: "Дни, где были события по наблюдениям.",
    chartMeasurementsHint: "Последние замеры за выбранный период.",
    noChartData: "Для этого нет данных.",
    sleepStarted: "Сон",
    feedingRecorded: "Кормление",
    illnessStarted: "Начато наблюдение",
    illnessClosed: "Завершено наблюдение",
    illnessObservation: "Наблюдение",
    illnessNoTitle: "Без названия",
    illnessOpenValue: "активно",
    weightMeasured: "Вес",
    heightMeasured: "Рост",
    activeStatus: "идёт сейчас",
    formula: "смесь",
    breast: "грудь",
  },
  en: {
    loading: "Loading…",
    back: "← Back to child profile",
    title: "Overview",
    hint: "Feed, calendar and charts show what happened with the child across the selected period.",
    feed: "Feed",
    calendar: "Calendar",
    charts: "Charts",
    day: "Day",
    today: "Today",
    week: "7 days",
    twoWeeks: "14 days",
    month: "30 days",
    date: "Date",
    customPeriod: "Custom period",
    editCustomPeriod: "Edit",
    dateFrom: "Start",
    dateTo: "End",
    customPeriodTitle: "Custom period",
    customPeriodHint: "Choose the dates for the feed, calendar and charts.",
    choosePeriod: "Choose period",
    select: "Select",
    periodAffectsFeed: "This updates feed, calendar and charts.",
    customDatesTitle: "Custom dates",
    customDatesHint: "Choose the period for feed and quick summary.",
    apply: "Apply",
    cancel: "Cancel",
    closePeriodDialog: "Close period picker",
    summaryPeriodPrefix: "For period",
    all: "All",
    filters: {
      sleep: "Sleep",
      feeding: "Feeding",
      illness: "Illness",
      weight: "Weight",
      height: "Height",
    },
    summary: {
      sleep: "Sleep",
      feeding: "Feeding",
      illness: "Illness",
      weight: "Weight",
      height: "Height",
      formulaAverage: "Formula",
      measurements: "Growth",
      events: "Events",
      noData: "No data",
      none: "None",
      calm: "calm",
      perDay: "per day",
      episodes: "ep.",
      records: "rec.",
      active: "active",
      latest: "latest",
    },
    empty: "No events for the selected period. Change date, period or filters.",
    calendarHint: "Dots show event types for each day. Tap a day to open that day's feed.",
    dayFeedTitle: "Day feed",
    backToCalendar: "Back to calendar",
    dayFeedEmpty: "No events for the selected filters on this day.",
    chartsHint: "Quick charts for the selected period. Detailed analytics can be added next.",
    sleepTotal: "Sleep in period",
    feedingTotal: "Feedings",
    feedingFormulaTotal: "Formula in period",
    illnessTotal: "Illnesses",
    measurements: "Measurements",
    chartAverage: "average",
    chartTotal: "total",
    chartDays: "days with data",
    chartSleepHint: "How much the child sleeps by day on average.",
    chartFeedingHint: "Feeding frequency and formula volume by day.",
    chartIllnessHint: "Days with observation events.",
    chartMeasurementsHint: "Latest measurements in the selected period.",
    noChartData: "No data for this yet.",
    sleepStarted: "Sleep",
    feedingRecorded: "Feeding",
    illnessStarted: "Tracking started",
    illnessClosed: "Tracking closed",
    illnessObservation: "Observation",
    illnessNoTitle: "Untitled",
    illnessOpenValue: "active",
    weightMeasured: "Weight",
    heightMeasured: "Height",
    activeStatus: "active now",
    formula: "formula",
    breast: "breast",
  },
} as const;
