import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  background: {
    flex: 1,
  },
  backgroundImage: {
    opacity: 0.98,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,247,240,0.34)",
  },
  root: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 42,
    paddingHorizontal: 16,
    paddingBottom: 38,
    gap: 16,
  },
  topBar: {
    height: 40,
    justifyContent: "center",
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#3E4B5C",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  introBlock: {
    gap: 8,
    paddingRight: 12,
  },
  title: {
    color: "#243142",
    fontSize: 34,
    lineHeight: 38,
    fontWeight: "800",
    letterSpacing: -1,
  },
  subtitle: {
    color: "#6A7889",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
    maxWidth: 324,
  },
  sectionWrap: {
    gap: 8,
  },
  sectionHeader: {
    gap: 4,
  },
  sectionTitle: {
    color: "#243142",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
  },
  sectionHint: {
    color: "#6A7889",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  card: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EBCFC4",
    backgroundColor: "rgba(255,253,249,0.93)",
    overflow: "hidden",
  },
  dangerCard: {
    borderColor: "#F1CCC8",
    backgroundColor: "rgba(255,248,246,0.95)",
  },
  settingRow: {
    minHeight: 78,
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingRowCompact: {
    minHeight: 0,
    paddingTop: 10,
    paddingBottom: 12,
  },
  rowDivider: {
    height: 1,
    backgroundColor: "#F0DDD4",
    marginHorizontal: 16,
  },
  insetBlock: {
    paddingHorizontal: 10,
    paddingBottom: 8,
  },
  rowLead: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  rowLeadPlain: {
    width: 52,
    height: 52,
    borderRadius: 0,
    backgroundColor: "transparent",
  },
  rowLeadPlainLarge: {
    width: 58,
    height: 58,
  },
  rowLeadNeutral: {
    backgroundColor: "#F1E7E1",
  },
  rowLeadDanger: {
    backgroundColor: "#FCE6E4",
  },
  moduleRowIconImage: {
    width: 42,
    height: 42,
  },
  moduleRowIconImageLarge: {
    width: 58,
    height: 58,
  },
  rowCopy: {
    flex: 1,
    gap: 3,
  },
  rowTitle: {
    color: "#243142",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  rowHint: {
    color: "#6A7889",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  switchWrap: {
    marginLeft: 8,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  chip: {
    minWidth: 56,
    minHeight: 32,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E9D6CD",
    backgroundColor: "#FFF8F2",
    alignItems: "center",
    justifyContent: "center",
  },
  chipActive: {
    borderColor: "#F1B9AA",
    backgroundColor: "#FCE8E1",
  },
  chipPressed: {
    opacity: 0.88,
  },
  chipDisabled: {
    opacity: 0.45,
  },
  chipText: {
    color: "#7B6B65",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#E06F5C",
  },
  editorBlock: {
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  passwordEditorBlock: {
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  passwordFieldsStack: {
    gap: 8,
  },
  inputGroup: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E7D7CF",
    backgroundColor: "#FFF8F4",
    overflow: "hidden",
  },
  input: {
    minHeight: 48,
    paddingHorizontal: 14,
    color: "#243142",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
    backgroundColor: "#FFF8F4",
  },
  inputStandalone: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E7D7CF",
  },
  inputTop: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  inputMiddle: {},
  inputBottom: {
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  inputDivider: {
    height: 1,
    backgroundColor: "#EEDCD3",
    marginHorizontal: 14,
  },
  primaryAction: {
    minHeight: 46,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F18169",
  },
  primaryActionPressed: {
    opacity: 0.88,
  },
  primaryActionText: {
    color: "#FFFDF9",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "800",
  },
  passwordAction: {
    marginTop: 2,
  },
  subscriptionActionWrap: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 18,
  },
  subscriptionSummaryBlock: {
    marginHorizontal: 16,
    paddingBottom: 2,
    borderRadius: 0,
    overflow: "visible",
  },
  subscriptionSummaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    position: "relative",
  },
  subscriptionSummaryCell: {
    width: "48.5%",
    minHeight: 84,
    paddingHorizontal: 14,
    paddingVertical: 13,
    justifyContent: "center",
    gap: 6,
    borderRadius: 18,
    backgroundColor: "rgba(255,248,243,0.58)",
  },
  subscriptionSummaryCellRight: {
  },
  subscriptionSummaryCellBottom: {
  },
  subscriptionSummaryGridDividerVertical: {
    position: "absolute",
    top: 20,
    bottom: 20,
    left: "50%",
    width: 1,
    marginLeft: -0.5,
    backgroundColor: "rgba(240,221,212,0.28)",
  },
  subscriptionSummaryGridDividerHorizontal: {
    position: "absolute",
    left: 20,
    right: 20,
    top: "50%",
    height: 1,
    marginTop: -0.5,
    backgroundColor: "rgba(240,221,212,0.28)",
  },
  subscriptionSummaryHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  subscriptionSummaryIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7EEE8",
  },
  subscriptionSummaryLabel: {
    color: "#8391A0",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "700",
    flexShrink: 1,
  },
  subscriptionSummaryValue: {
    color: "#243142",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
  },
  inlineNote: {
    color: "#8A6D62",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  fieldError: {
    color: "#C75C52",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  errorNote: {
    borderRadius: 18,
    backgroundColor: "#FFF1EE",
    borderWidth: 1,
    borderColor: "#F4C8C1",
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#C75C52",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  successNote: {
    borderRadius: 18,
    backgroundColor: "#EFF8F1",
    borderWidth: 1,
    borderColor: "#CCE5D0",
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#517A58",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  loadingNote: {
    color: "#8B7A72",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
  },
  rowPressed: {
    opacity: 0.88,
  },
  rowDisabled: {
    opacity: 0.55,
  },
  dropdownValueWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginLeft: 8,
  },
  dropdownValueText: {
    color: "#7B6B65",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  dropdownList: {
    marginHorizontal: 16,
    marginBottom: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EED8CF",
    backgroundColor: "#FFF8F4",
    overflow: "hidden",
  },
  dropdownItem: {
    minHeight: 46,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownItemActive: {
    backgroundColor: "#FDF0EA",
  },
  dropdownItemPressed: {
    opacity: 0.88,
  },
  dropdownItemText: {
    color: "#243142",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  dropdownItemTextActive: {
    color: "#E06F5C",
  },
  dropdownDivider: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 0,
    height: 1,
    backgroundColor: "#F0DDD4",
  },
  lockedStatusWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EAF6ED",
  },
  dangerRow: {
    minHeight: 80,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  dangerRowPressed: {
    opacity: 0.88,
  },
  dangerTitle: {
    color: "#B94A45",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
  },
  dangerHint: {
    color: "#9B6D6A",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
});
