import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#FBF3EC",
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.52)",
  },
  screen: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 54,
    paddingHorizontal: 16,
    paddingBottom: 180,
    gap: 16,
  },
  header: {
    gap: 8,
    paddingHorizontal: 2,
  },
  title: {
    color: "#252B35",
    fontSize: 42,
    lineHeight: 44,
    fontWeight: "800",
    letterSpacing: -1.6,
  },
  subtitle: {
    maxWidth: 280,
    color: "#6F7178",
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "500",
  },
  cardsStack: {
    gap: 16,
  },
  card: {
    position: "relative",
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: "#EFDDD2",
    backgroundColor: "#FFF8F1",
    padding: 18,
    gap: 14,
    shadowColor: "#CFAE9F",
    shadowOpacity: 0.08,
    shadowRadius: 11,
    shadowOffset: { width: 0, height: 5 },
  },
  cardCollapsed: {
    gap: 0,
    paddingBottom: 18,
  },
  cardHeroRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingRight: 36,
  },
  cardHeroRowPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.995 }],
  },
  cardInfo: {
    flex: 1,
    justifyContent: "center",
    gap: 7,
    paddingTop: 12,
  },
  collapseButton: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 2,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FCEBE7",
    alignItems: "center",
    justifyContent: "center",
  },
  collapseButtonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.94 }],
  },
  avatarShell: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: "#F7E6DB",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  avatarImage: {
    width: 78,
    height: 78,
  },
  childName: {
    flexShrink: 1,
    color: "#252B35",
    fontSize: 28,
    lineHeight: 30,
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  childStats: {
    color: "#5F636B",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "600",
  },
  liveChip: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#B7DEC6",
    backgroundColor: "#E4F5EA",
    paddingHorizontal: 8,
    paddingVertical: 6,
    flexShrink: 0,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#7FB79A",
  },
  liveChipText: {
    color: "#4D9A6B",
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "600",
  },
  quickActionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  quickActionCard: {
    alignItems: "center",
    justifyContent: "center",
    width: "47.8%",
    minHeight: 84,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#F1E3DA",
    backgroundColor: "#FFFDF8",
    paddingHorizontal: 12,
    paddingVertical: 12,
    shadowColor: "#D9B7AA",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  quickActionCardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  quickActionCardActive: {
    borderColor: "#B7DEC6",
    backgroundColor: "#F2FBF5",
  },
  quickActionContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
    width: "100%",
  },
  quickActionIconSlot: {
    width: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  quickActionIconSlotSleep: {
    transform: [{ translateX: -3 }],
  },
  quickActionArt: {
    width: 46,
    height: 46,
    flexShrink: 0,
  },
  quickActionLabel: {
    flex: 1,
    paddingRight: 2,
    color: "#202938",
    fontSize: 13,
    lineHeight: 15,
    fontWeight: "700",
    textAlign: "left",
    flexShrink: 1,
  },
  quickActionLabelActive: {
    color: "#4D9A6B",
  },
  addChildCta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    minHeight: 74,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: "#F2C2B8",
    backgroundColor: "#FFF7F1",
    marginTop: 4,
  },
  addChildCtaPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  addChildIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F26F6C",
    alignItems: "center",
    justifyContent: "center",
  },
  addChildLabel: {
    color: "#F26F6C",
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "800",
  },
  bottomNavWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 22,
  },
  bottomNav: {
    flexDirection: "row",
    alignItems: "stretch",
    borderRadius: 26,
    borderWidth: 2,
    borderColor: "#EEDDD5",
    backgroundColor: "#FFF9F4",
    padding: 8,
    gap: 8,
  },
  tabItem: {
    flex: 1,
    minHeight: 64,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  tabItemPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.96 }],
  },
  tabItemActive: {
    backgroundColor: "#FCE8E1",
  },
  tabIconWrap: {
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  tabLabel: {
    color: "#7A746F",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "700",
  },
  tabLabelActive: {
    color: "#F26F6C",
  },
  confirmOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(30,42,56,0.18)",
  },
  confirmCard: {
    width: "86%",
    maxWidth: 340,
    borderRadius: 28,
    backgroundColor: "#FFFDF9",
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderWidth: 1.5,
    borderColor: "#EBCFC4",
    shadowColor: "#CFAE9F",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  confirmContent: {
    gap: 16,
  },
  confirmTitle: {
    color: "#252B35",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
    letterSpacing: -0.4,
    textAlign: "center",
  },
  confirmActions: {
    flexDirection: "row",
    gap: 10,
  },
  confirmButtonSecondary: {
    flex: 1,
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#E9D7CE",
    backgroundColor: "#FFF8F3",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPrimary: {
    flex: 1,
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#F0C8BC",
    backgroundColor: "#FFF0E9",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  confirmButtonSecondaryText: {
    color: "#6F7178",
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "700",
  },
  confirmButtonPrimaryText: {
    color: "#F26F6C",
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "800",
  },
});
