import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlayLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 24,
  },
  overlayLayerVisible: {
    opacity: 1,
  },
  overlayLayerHidden: {
    opacity: 0,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,248,241,0.48)",
  },
  root: {
    flex: 1,
  },
  swipeBackEdge: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 40,
    gap: 14,
  },
  backLink: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backLinkText: {
    color: "#31485C",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
  },
  heroCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#EED8CF",
    backgroundColor: "#FFF8F1",
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  avatarWrap: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: "#F7E6DB",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  avatarWrapPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  avatarPlaceholderWrap: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 1,
    borderColor: "#E9CFC3",
    borderStyle: "dashed",
    backgroundColor: "#FFF4EC",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarPlaceholderPlus: {
    position: "absolute",
    right: 12,
    bottom: 12,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#F76961",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImage: {
    width: 88,
    height: 88,
  },
  heroInfo: {
    flex: 1,
    gap: 6,
  },
  heroGenderPill: {
    alignSelf: "flex-start",
    minWidth: 28,
    height: 24,
    paddingHorizontal: 8,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  heroGenderPillBoy: {
    borderColor: "#C7DCF4",
    backgroundColor: "#EEF6FF",
  },
  heroGenderPillGirl: {
    borderColor: "#F0D2E0",
    backgroundColor: "#FFF1F7",
  },
  heroName: {
    color: "#252B35",
    fontSize: 27,
    lineHeight: 30,
    fontWeight: "800",
    letterSpacing: -0.7,
  },
  heroMeta: {
    color: "#6F7178",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
  },
  sectionWrap: {
    gap: 10,
  },
  sectionTitle: {
    color: "#23364A",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
  },
  cardList: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#EED8CF",
    backgroundColor: "#FFFDF9",
    overflow: "hidden",
  },
  fieldRow: {
    minHeight: 74,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: "center",
    gap: 8,
  },
  fieldDivider: {
    height: 1,
    backgroundColor: "#F0DDD4",
    marginHorizontal: 16,
  },
  fieldLabel: {
    color: "#23364A",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  textInput: {
    color: "#23364A",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
    padding: 0,
  },
  rowDescription: {
    color: "#6F7178",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "500",
    maxWidth: 220,
  },
  switchRow: {
    minHeight: 82,
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  switchTextWrap: {
    flex: 1,
    gap: 4,
  },
  dateButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dateValue: {
    color: "#23364A",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
  },
  placeholderText: {
    color: "#A6AFB8",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "500",
  },
  sheetGenderSwitch: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  genderSwitchOption: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  genderSwitchOptionBoy: {
    borderColor: "#CFE0F4",
    backgroundColor: "#F3F8FE",
  },
  genderSwitchOptionBoyActive: {
    borderColor: "#76AEEA",
    backgroundColor: "#DDEEFF",
  },
  genderSwitchOptionGirl: {
    borderColor: "#F0D5E1",
    backgroundColor: "#FFF3F8",
  },
  genderSwitchOptionGirlActive: {
    borderColor: "#EC9BBE",
    backgroundColor: "#FFE3EF",
  },
  genderSwitchText: {
    color: "#6F7178",
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "700",
  },
  genderSwitchTextActive: {
    color: "#23364A",
  },
  genderChipPressed: {
    opacity: 0.9,
  },
  avatarOption: {
    width: "30.8%",
    aspectRatio: 1,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#EED8CF",
    backgroundColor: "#FFF8F1",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarOptionSelected: {
    borderColor: "#F4A79B",
    backgroundColor: "#FFF0E8",
  },
  avatarOptionPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  avatarOptionImage: {
    width: 78,
    height: 78,
  },
  primaryButton: {
    minHeight: 60,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F76961",
    marginTop: 6,
  },
  primaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButtonPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.988 }],
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 17,
    lineHeight: 20,
    fontWeight: "800",
  },
  sheetOverlay: {
    justifyContent: "flex-end",
  },
  sheetBackdrop: {
    backgroundColor: "rgba(36, 27, 22, 0.18)",
  },
  avatarSheetCard: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#FFF8F1",
  },
  sheetDragZone: {
    alignItems: "center",
    gap: 10,
    paddingBottom: 16,
  },
  sheetHandle: {
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#E4D3C7",
  },
  sheetTitle: {
    color: "#252B35",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "800",
  },
  avatarSheetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
});
